### ISSUE TITLE
Glass Door graphic issue

### ISSUE THREAD

**Issue by sketchmacaw** [sketchmacaw/MacawsModsIssues#1]
When you look into the glas door this happens

https://imgur.com/a/T3WknTa
https://imgur.com/a/10IrR2t

**Comment by sketchmacaw** [comment]
Fixed in 1.0.1

**Comment by Peach774** [comment]
This is an issue again

**Comment by sketchmacaw** [comment]
It is fixed in the upcoming 1.0.1 update
