### ISSUE TITLE
Duplication of doors

### ISSUE THREAD

**Issue by mordobi27** [sketchmacaw/MacawsModsIssues#10]
Hello there,
if I break top of the door it will be duplicate and it's happen to all door type.

Have a nice day,
m27s

**Comment by ExDomino** [comment]
This bug will never being fixed ?

**Comment by sketchmacaw** [comment]
Issue is fixed in the upcoming 1.0.3 update for 1.12.2

**Comment by ExDomino** [comment]
You have a little idea of when it will be released please ?

**Comment by sketchmacaw** [comment]
+- 10 days
