### ISSUE TITLE
Lights duplicate sometimes

### ISSUE THREAD

**Issue by hypnotox** [sketchmacaw/MacawsModsIssues#103]
Title: Lights duplicate sometimes
Description: When placing and breaking lights they sometimes duplicate. The behaviour itself is very inconsistent with new lamp entites spawning in the inventory when it happens. Sometimes placed lamps immediately disappear or don't use an item even though a block entity is spawned. (We are playing with the modpack Valhelsia 3 Version 3.4.2, it might be possible that this is an issue with other mods, but we don't have any problems with other mods that add blocks.)
Labels: 1.16.5, Macaw's Lights and Lamps, Bug, Item Duplication

**Comment by sketchmacaw** [comment]
Could you try if this issue still happens in the newest 1.0.4 Lights update?

**Comment by hypnotox** [comment]
We are currently not running the server anymore, so I'm unfortunately unable to test it right now. The issue was very much reproducible without much of a hassle though, so if you're unable to reproduce it anymore then it's probably fixed 👍🏻 

In that case you can probably close this issue.
