### ISSUE TITLE
Lighting difference on opposite sides of a Lower Roof

### ISSUE THREAD

**Issue by xenoflot** [sketchmacaw/MacawsModsIssues#105]
Description: 

Lower Roof blocks have different lighting/tone processing depending on the direction they're placed. Specifically, the side facing the player is much darker. Further, the shading makes them look quite different from the vanilla blocks they're sitting on. Blocks of other colours (tested with Blue) are similarly affected.

Playing an unaltered All the Mods 6 Skyblock. No shaders.  On of the players has started building with Light Gray Concrete and is incorporating Roof blocks into the build. He's noticed marked colour differences depending on the facing of the block. As illustrated in the linked screenshot. The same block appears much darker when facing the other way. Viewing the build from the opposite side, you see the expected reverse of light and dark. Forcing a lighting update with a torch didn't help.

Forge 31.1.66
Mod: mcw-roofs-2.0.1-mc1.16.5-4

Screenshots: https://i.imgur.com/LEjsZPU.jpg  https://i.imgur.com/lx4Jkp2.jpg

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
