### ISSUE TITLE
Garage door multiplayer

### ISSUE THREAD

**Issue by TheSuperCheese** [sketchmacaw/MacawsModsIssues#107]
When on my GFs lan world when i try opening or closing the garage door it just crashes/kicks me and gives the message

Connection Lost
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "p_130069_" is null

Mod Version: mcw-doors-1.0.3-mc1.17.1

**Comment by Purplo262** [comment]
Can confirm I have also had this issue when a player placed and then tried to open a shoji door. Immediately lost connection with the same error

**Comment by sketchmacaw** [comment]
On it

**Comment by sketchmacaw** [comment]
Fixed in 1.0.4 for 1.17.1
