### ISSUE TITLE
[mcwFurniture 2.0.1] several major Issue with Dresser / Nightstand

### ISSUE THREAD

**Issue by 2ndRecon** [sketchmacaw/MacawsModsIssues#110]
There is a **major** issue with the Dresser / Nightstand.

When accessing Dresser inventory with a held weapon or item, player consumes item / fires weapon while accessing 
tiles inventory. In the case of a food item, player will consume the item perpetually until you cancel the action.

In the case of a bow, the bow is fired into the dresser. You either need to access the dresser with an empty hand, or a non-Ranged weapon. 

**2nd -** When right clicking on the dresser with a placeable block, there is a momentary animation as if the player is placing that block in the same space as the Dresser, before the inventory opens. It's as if the block is placed, then cancelled, then the inventory opens. 

_**3rd - Duplication Glitch**_ - There is a problem with the multi-block. There is a way to duplicate the dresser perpetually. Using the Engineering hammer, Crescent hammer or another tool that allows the rotation of individual blocks of a multi-block; you can rotate one side of a Dresser, break it, then break the other half and you now have 2 dressers. Place both, do it again, and you now have 4. repeat, **profit**

>Labels: 1.16.2, Macaw's Furniture, Bug, Texture

**Comment by 2ndRecon** [comment]
I wanted to add one other thing.. When removing the Dresser from on top of a block. If you place a chest on top of that same block. You're unable to open it. As it something is on top the chest. If you break the block below and then replace it, you can open the chest. It's as if the tile entity for the Dresser is there even though you have removed it.

**Comment by sketchmacaw** [comment]
Everything mentioned is fixed in 3.0.0 Update
