### ISSUE TITLE
***suggestion*** Tradução Português BR (Brazilian Translation pt_br)

### ISSUE THREAD

**Issue by clustermage** [sketchmacaw/MacawsModsIssues#116]
{
	"itemGroup.mcwdoors":"Macaw's Doors",	

	"mcwdoors.crafting.desc":"Itens de Fabricação",
	"mcwdoors.remote.desc":"Clique com o botão direito na porta da garagem para Abrir/Fechar",

	"subtitle.mcwdoors.shoji": "Abra a Porta Shoji",
	"subtitle.mcwdoors.garage": "Abra a Porta da Garagem",

	"item.mcwdoors.garage_remote":"Controle Remoto de Garagem",
   	"item.mcwdoors.print_oak":"Pintura de Porta de Carvalho",
	"item.mcwdoors.print_spruce":"Pintura de Porta de Pinheiro",
	"item.mcwdoors.print_birch":"Pintura de Porta de Bétula",
	"item.mcwdoors.print_jungle":"Pintura de Porta de Madeira da Selva",
	"item.mcwdoors.print_acacia":"Pintura de Porta de Acácia",
	"item.mcwdoors.print_dark_oak":"Pintura de Porta de Carvalho Escuro",
	"item.mcwdoors.print_nether":"Pintura de Porta Carmesim",
	"item.mcwdoors.print_mystic":"Pintura de Porta Distorcida",

	"block.mcwdoors.oak_japanese_door":"Porta Shoji de Carvalho",
	"block.mcwdoors.spruce_japanese_door":"Porta Shoji de Pinheiro",
	"block.mcwdoors.birch_japanese_door":"Porta Shoji de Bétula",
	"block.mcwdoors.jungle_japanese_door":"Porta Shoji de Madeira da Selva",
	"block.mcwdoors.acacia_japanese_door":"Porta Shoji de Acácia",
	"block.mcwdoors.dark_oak_japanese_door":"Porta Shoji de Carvalho Escuro",
	"block.mcwdoors.crimson_japanese_door":"Porta Shoji Carmesim",
	"block.mcwdoors.warped_japanese_door":"Porta Shoji Distorcida",

	"block.mcwdoors.oak_japanese2_door":"Porta Shoji Inteiriça de Carvalho",
	"block.mcwdoors.spruce_japanese2_door":"Porta Shoji Inteiriça de Pinheiro",
	"block.mcwdoors.birch_japanese2_door":"Porta Shoji Inteiriça de Bétula",
	"block.mcwdoors.jungle_japanese2_door":"Porta Shoji Inteiriça de Madeira da Selva",
	"block.mcwdoors.acacia_japanese2_door":"Porta Shoji Inteiriça de Acácia",
	"block.mcwdoors.dark_oak_japanese2_door":"Porta Shoji Inteiriça de Carvalho Escuro",
	"block.mcwdoors.crimson_japanese2_door":"Porta Shoji Inteiriça Carmesim",
	"block.mcwdoors.warped_japanese2_door":"Porta Shoji Inteiriça Distorcida",

	"block.mcwdoors.oak_barn_door":"Porta Celeiro de Carvalho",
	"block.mcwdoors.spruce_barn_door":"Porta Celeiro de Pinheiro",
	"block.mcwdoors.birch_barn_door":"Porta Celeiro de Bétula",
	"block.mcwdoors.jungle_barn_door":"Porta Celeiro de Madeira da Selva",
	"block.mcwdoors.acacia_barn_door":"Porta Celeiro de Acácia",
	"block.mcwdoors.dark_oak_barn_door":"Porta Celeiro de Carvalho Escuro",
	"block.mcwdoors.crimson_barn_door":"Porta Celeiro Carmesim",
	"block.mcwdoors.warped_barn_door":"Porta Celeiro Distorcida",

	"block.mcwdoors.oak_modern_door":"Porta Moderna de Carvalho",
	"block.mcwdoors.spruce_modern_door":"Porta Moderna de Pinheiro",
	"block.mcwdoors.birch_modern_door":"Porta Moderna de Bétula",
	"block.mcwdoors.jungle_modern_door":"Porta Moderna de Madeira da Selva",
	"block.mcwdoors.acacia_modern_door":"Porta Moderna de Acácia",
	"block.mcwdoors.dark_oak_modern_door":"Porta Moderna de Carvalho Escuro",
	"block.mcwdoors.crimson_modern_door":"Porta Moderna Carmesim",
	"block.mcwdoors.warped_modern_door":"Porta Moderna Distorcida",

	"block.mcwdoors.oak_barn_glass_door":"Porta Celeiro com Vidraça de Carvalho",
	"block.mcwdoors.spruce_barn_glass_door":"Porta Celeiro com Vidraça de Pinheiro",
	"block.mcwdoors.birch_barn_glass_door":"Porta Celeiro com Vidraça de Bétula",
	"block.mcwdoors.jungle_barn_glass_door":"Porta Celeiro com Vidraça de Madeira da Selva",
	"block.mcwdoors.acacia_barn_glass_door":"Porta Celeiro com Vidraça de Acácia",
	"block.mcwdoors.dark_oak_barn_glass_door":"Porta Celeiro com Vidraça de Carvalho Escuro",
	"block.mcwdoors.crimson_barn_glass_door":"Porta Celeiro com Vidraça Carmesim",
	"block.mcwdoors.warped_barn_glass_door":"Porta Celeiro com Vidraça Distorcida",

	"block.mcwdoors.oak_cottage_door":"Porta Campestre de Carvalho",
	"block.mcwdoors.birch_cottage_door":"Porta Campestre de Bétula",
	"block.mcwdoors.jungle_cottage_door":"Porta Campestre de Madeira da Selva",
	"block.mcwdoors.acacia_cottage_door":"Porta Campestre de Acácia",
	"block.mcwdoors.dark_oak_cottage_door":"Porta Campestre de Carvalho Escuro",
	"block.mcwdoors.crimson_cottage_door":"Porta Campestre Carmesim",
	"block.mcwdoors.warped_cottage_door":"Porta Campestre Distorcida",

	"block.mcwdoors.spruce_classic_door":"Porta Clássica de Pinheiro",
	"block.mcwdoors.birch_classic_door":"Porta Clássica de Bétula",
	"block.mcwdoors.jungle_classic_door":"Porta Clássica de Madeira da Selva",
	"block.mcwdoors.acacia_classic_door":"Porta Clássica de Acácia",
	"block.mcwdoors.dark_oak_classic_door":"Porta Clássica de Carvalho Escuro",
	"block.mcwdoors.crimson_classic_door":"Porta Clássica Carmesim",
	"block.mcwdoors.warped_classic_door":"Porta Clássica Distorcida",

	"block.mcwdoors.oak_beach_door":"Porta Praiana de Carvalho",
	"block.mcwdoors.spruce_beach_door":"Porta Praiana de Pinheiro",
	"block.mcwdoors.birch_beach_door":"Porta Praiana de Bétula",
	"block.mcwdoors.acacia_beach_door":"Porta Praiana de Acácia",
	"block.mcwdoors.dark_oak_beach_door":"Porta Praiana de Carvalho Escuro",
	"block.mcwdoors.crimson_beach_door":"Porta Praiana Carmesim",
	"block.mcwdoors.warped_beach_door":"Porta Praiana Distorcida",

	"block.mcwdoors.oak_paper_door":"Porta de Papel de Carvalho",
	"block.mcwdoors.spruce_paper_door":"Porta de Papel de Pinheiro",
	"block.mcwdoors.jungle_paper_door":"Porta de Papel de Madeira da Selva",
	"block.mcwdoors.acacia_paper_door":"Porta de Papel de Acácia",
	"block.mcwdoors.dark_oak_paper_door":"Porta de Papel de Carvalho Escuro",
	"block.mcwdoors.crimson_paper_door":"Porta de Papel Carmesim",
	"block.mcwdoors.warped_paper_door":"Porta de Papel Distorcida",

	"block.mcwdoors.oak_four_panel_door":"Porta Quatro Painéis de Carvalho",
	"block.mcwdoors.spruce_four_panel_door":"Porta Quatro Painéis de Pinheiro",
	"block.mcwdoors.birch_four_panel_door":"Porta Quatro Painéis de Bétula",
	"block.mcwdoors.jungle_four_panel_door":"Porta Quatro Painéis de Madeira da Selva",
	"block.mcwdoors.acacia_four_panel_door":"Porta Quatro Painéis de Acácia",
	"block.mcwdoors.dark_oak_four_panel_door":"Porta Quatro Painéis de Carvalho Escuro",
	"block.mcwdoors.crimson_four_panel_door":"Porta Quatro Painéis Carmesim",
	"block.mcwdoors.warped_four_panel_door":"Porta Quatro Painéis Distorcida",

	"block.mcwdoors.oak_tropical_door":"Porta Tropical de Carvalho",
	"block.mcwdoors.spruce_tropical_door":"Porta Tropical de Pinheiro",
	"block.mcwdoors.birch_tropical_door":"Porta Tropical de Bétula",
	"block.mcwdoors.jungle_tropical_door":"Porta Tropical de Madeira da Selva",
	"block.mcwdoors.dark_oak_tropical_door":"Porta Tropical de Carvalho Escuro",
	"block.mcwdoors.crimson_tropical_door":"Porta Tropical Carmesim",
	"block.mcwdoors.warped_tropical_door":"Porta Tropical Distorcida",

	"block.mcwdoors.metal_door":"Porta de Metal",
	"block.mcwdoors.metal_warning_door":"Porta de Metal de Alerta",
	"block.mcwdoors.metal_hospital_door":"Porta de Metal do Hospital",
	"block.mcwdoors.metal_reinforced_door":"Porta de Metal Reforçada",
	"block.mcwdoors.metal_windowed_door":"Porta de Metal Sólido",
	"block.mcwdoors.jail_door":"Porta da Cadeia",

	"block.mcwdoors.oak_glass_door":"Porta de Vidro de Carvalho",
	"block.mcwdoors.oak_mystic_door":"Porta Distorcida de Carvalho",
	"block.mcwdoors.oak_nether_door":"Porta Carmesin de Carvalho",
	"block.mcwdoors.oak_stable_door":"Porta de Estábulo de Carvalho",
	"block.mcwdoors.oak_stable_head_door":"Porta de Estábulo de Cavalo de Carvalho",
	"block.mcwdoors.oak_western_door":"Porta de Velho Oeste de Carvalho",

	"block.mcwdoors.spruce_glass_door":"Porta de Vidro de Pinheiro",
	"block.mcwdoors.spruce_mystic_door":"Porta Distorcida de Pinheiro",
	"block.mcwdoors.spruce_nether_door":"Porta Carmesin de Pinheiro",
	"block.mcwdoors.spruce_stable_door":"Porta de Estábulo de Pinheiro",
	"block.mcwdoors.spruce_stable_head_door":"Porta de Estábulo de Cavalo de Pinheiro",
	"block.mcwdoors.spruce_western_door":"Porta de Velho Oeste de Pinheiro",

	"block.mcwdoors.birch_glass_door":"Porta de Vidro de Bétula",
	"block.mcwdoors.birch_mystic_door":"Porta Distorcida de Bétula",
	"block.mcwdoors.birch_nether_door":"Porta Carmesin de Bétula",
	"block.mcwdoors.birch_stable_door":"Porta de Estábulo de Bétula",
	"block.mcwdoors.birch_stable_head_door":"Porta de Estábulo de Cavalo de Bétula",
	"block.mcwdoors.birch_western_door":"Porta de Velho Oeste de Bétula",

	"block.mcwdoors.jungle_glass_door":"Porta de Vidro de Madeira da Selva",
	"block.mcwdoors.jungle_mystic_door":"Porta Distorcida de Madeira da Selva",
	"block.mcwdoors.jungle_nether_door":"Porta Carmesin de Madeira da Selva",
	"block.mcwdoors.jungle_stable_door":"Porta de Estábulo de Madeira da Selva",
	"block.mcwdoors.jungle_stable_head_door":"Porta de Estábulo de Cavalo de Madeira da Selva",
	"block.mcwdoors.jungle_western_door":"Porta de Velho Oeste de Madeira da Selva",

	"block.mcwdoors.acacia_glass_door":"Porta de Vidro de Acácia",
	"block.mcwdoors.acacia_mystic_door":"Porta Distorcida de Acácia",
	"block.mcwdoors.acacia_nether_door":"Porta Carmesin de Acácia",
	"block.mcwdoors.acacia_stable_door":"Porta de Estábulo de Acácia",
	"block.mcwdoors.acacia_stable_head_door":"Porta de Estábulo de Cavalo de Acácia",
	"block.mcwdoors.acacia_western_door":"Porta de Velho Oeste de Acácia",

	"block.mcwdoors.dark_oak_glass_door":"Porta de Vidro de Carvalho Escuro",
	"block.mcwdoors.dark_oak_mystic_door":"Porta Distorcida de Carvalho Escuro",
	"block.mcwdoors.dark_oak_nether_door":"Porta Carmesin de Carvalho Escuro",
	"block.mcwdoors.dark_oak_stable_door":"Porta de Estábulo de Carvalho Escuro",
	"block.mcwdoors.dark_oak_stable_head_door":"Porta de Estábulo de Cavalo de Carvalho Escuro",
	"block.mcwdoors.dark_oak_western_door":"Porta de Velho Oeste de Carvalho Escuro",

	"block.mcwdoors.warped_glass_door":"Porta de Vidro Distorcida",
	"block.mcwdoors.warped_mystic_door":"Porta Distorcida Distorcida",
	"block.mcwdoors.warped_nether_door":"Porta Carmesin Distorcida",
	"block.mcwdoors.warped_stable_door":"Porta de Estábulo Distorcida",
	"block.mcwdoors.warped_stable_head_door":"Porta de Estábulo de Cavalo Distorcida",
	"block.mcwdoors.warped_western_door":"Porta de Velho Oeste Distorcida",

	"block.mcwdoors.crimson_glass_door":"Porta de Vidro Carmesim",
	"block.mcwdoors.crimson_mystic_door":"Porta Distorcida Carmesim",
	"block.mcwdoors.crimson_nether_door":"Porta Carmesin Carmesim",
	"block.mcwdoors.crimson_stable_door":"Porta de Estábulo Carmesim",
	"block.mcwdoors.crimson_stable_head_door":"Porta de Estábulo de Cavalo Carmesim",
	"block.mcwdoors.crimson_western_door":"Porta de Velho Oeste Carmesim",

	"block.mcwdoors.garage_white_door":"Porta de Garagem Branca",
	"block.mcwdoors.garage_silver_door":"Porta de Garagem Prateada",
	"block.mcwdoors.garage_gray_door":"Porta de Garagem Cinza",
	"block.mcwdoors.garage_black_door":"Porta de Garagem Preta",

	"block.mcwdoors.oak_bark_glass_door":"Porta de Vidro de Casca de Carvalho",
	"block.mcwdoors.spruce_bark_glass_door":"Porta de Vidro de Casca de Pinheiro",
	"block.mcwdoors.birch_bark_glass_door":"Porta de Vidro de Casca de Bétula",
	"block.mcwdoors.jungle_bark_glass_door":"Porta de Vidro de Casca de Madeira da Selva",
	"block.mcwdoors.acacia_bark_glass_door":"Porta de Vidro de Casca de Acácia",
	"block.mcwdoors.dark_oak_bark_glass_door":"Porta de Vidro de Casca de Carvalho Escuro",
	"block.mcwdoors.crimson_stem_glass_door":"Porta de Vidro de Casca Carmesim",
	"block.mcwdoors.warped_stem_glass_door":"Porta de Vidro de Casca Distorcida"
	}

**Comment by sketchmacaw** [comment]
Added in 1.0.6
