### ISSUE TITLE
[mcw-windows-2.0.0-mc1.16.5] Window crafting recipe mixed up and window hammer bug

### ISSUE THREAD

**Issue by DeltaMikeDt** [sketchmacaw/MacawsModsIssues#119]
Crafting "Grille Windows" using Granite, Diorite, Andesite, and Stone requires normal window base instead of the grille version (and vice versa when crafting normal windows).

![image](https://user-images.githubusercontent.com/92635477/137589475-3b2d33bf-4657-4b09-bda1-0b03efcdb52e.png)

Also not sure if this is normal: right clicking on a window that has already been hammered does not revert it back to connected window form.

![image](https://user-images.githubusercontent.com/92635477/137589504-0a254310-1611-4484-b53d-5058af3796f5.png)

Labels: 1.16.5, Macaw's Windows, Bug

**Comment by sketchmacaw** [comment]
Window crafting recipe mixed up in the upcoming 2.0.2 Update, the hammer is normal for now but I will take this as a suggestion to make it revert back.
