### ISSUE TITLE
Biomes O' Plenty Support for Macaw's Bridges

### ISSUE THREAD

**Issue by FlionkJ** [sketchmacaw/MacawsModsIssues#120]
Adding full support for all bioms o plenty wood types

Labels: 1.16.5, suggestion, Macaw's Bridges

**Comment by sketchmacaw** [comment]
Someone actually made an addon for it

**Comment by DeltaMikeDt** [comment]
Here's the addon mod: https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty
