### ISSUE TITLE
Mosaic Glass Pane graphic issue

### ISSUE THREAD

**Issue by Maltshakes** [sketchmacaw/MacawsModsIssues#123]
Title : **Mosaic Glass Pane graphic issue**
Description: When looking at mosaic glass panes stacked on top of each other, you can see a seam between them. I have no shaders and disabling resource packs did not resolve the issue. Below links show examples, one showing how vanilla stained glass panes do not have this issue. 

https://cdn.discordapp.com/attachments/673509938219319316/913025440585744415/unknown.png
https://cdn.discordapp.com/attachments/673509938219319316/913025691912650752/unknown.png

Labels: 1.16.5, Macaw's Windows 2.0.0, Bug, Texture

**Comment by sketchmacaw** [comment]
Will be fixed in the next update.

**Comment by sketchmacaw** [comment]
Do you have optifine installed? Because in vanilla the classic one has the seam between them too.

**Comment by Maltshakes** [comment]
I do have optifine, but I'm not using any resource packs or shaders. I didn't realize optifine would cause that on its own
