### ISSUE TITLE
Roofs don't connect and different color corners.

### ISSUE THREAD

**Issue by MathewMantas** [sketchmacaw/MacawsModsIssues#124]
I was just about finishing my roof and I found three problems maybe only one a serious one, but others could be that are not feature's yet.

1. Spruce Planks Roof - has different color on the corners even though it's the same block. (Haven't experienced this on inner corners)

2. Spruce Planks Top Roof  - doesn't connect smoothly. And they don't merge with Spruce Planks Roof to make a nice corner it just leaves a gap. (Probably isn't implemented yet but I would love to see it in a new update!)

![mc roofs](https://user-images.githubusercontent.com/78929525/143661067-a6677dd6-20e2-4f45-9fff-83e05aff174e.png)

**1.16.5, Macaw's Doors, Bug, Texture, suggestion** (I would add these tags if github allowed me, this is getting on my nerves so sorry I'll leave it for you)

**Comment by sketchmacaw** [comment]
Working on fixing these in the upcoming roofs update.

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
