### ISSUE TITLE
Some furniture spawned by command are waterlogged

### ISSUE THREAD

**Issue by PeterBennyFooda** [sketchmacaw/MacawsModsIssues#126]
Title : **Some furniture spawned by command are waterlogged**
Description: Whenever I spawn a desk or simple end table with command, it is in a water block. I need to manually add `[waterlogged=false]` to avoid that. Maybe other furniture has the same issue too.

Example: `/setblock ~ ~2 ~ mcwfurnitures:spruce_desk_left`
https://imgur.com/a/XpOlLoC

Labels: 1.16.5, Macaw's Furniture, Bug

**Comment by sketchmacaw** [comment]
Fixed in 3.0.0 Update
