### ISSUE TITLE
Four Panel Trapdoor side textures upside down

### ISSUE THREAD

**Issue by Maltshakes** [sketchmacaw/MacawsModsIssues#127]
Description: When you compare the four panel trapdoors to the vanilla dark oak version, you can see that the side textures are upside down when the trapdoor is placed against a block rather than flat on the floor. 

In the image you can see how the trapdoors all match when flat on the floor, but the sides on the trapdoors up against the grass blocks are upside down
https://i.imgur.com/ylVpA3N.png

Labels: 1.16.5 Macaw's Trapdoors, Texture

**Comment by sketchmacaw** [comment]
Fixed in 1.0.2 for 1.18.1, later expect to fix it for 1.17 and 1.16.5.
