### ISSUE TITLE
Garage door and Shoji do crash

### ISSUE THREAD

**Issue by Zerkweet** [sketchmacaw/MacawsModsIssues#128]
watsup guys, on my server I have the mod install and I have somes issues when I close/open my door, it make me crash and I have this error. I think, it's for all the door the opening is different then the original door
Connection Lost
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "p_130069_" is null

Thanks !

**Comment by sketchmacaw** [comment]
Fixed in 1.0.4fix

**Comment by Zerkweet** [comment]
https://i.imgur.com/4Us2w53.png 1.0.3 fix when I download the 1.0.4, it is normal ? bc with this update, it doesn't work too
Thanks !

**Comment by sketchmacaw** [comment]
Is it the same error ?

**Comment by Zerkweet** [comment]
2 min im looking mb

**Comment by Zerkweet** [comment]
https://i.imgur.com/1HtEsAn.png

**Comment by Zerkweet** [comment]
yo sorry for the was of your time for real. it working, I just forgot to remove the old version verry sorry xd. thanks for the fast answer !

**Comment by sketchmacaw** [comment]
Oh alright awesome!
