### ISSUE TITLE
Fences missing side texture when connected to fence gate

### ISSUE THREAD

**Issue by Maltshakes** [sketchmacaw/MacawsModsIssues#129]
Description: Not sure what the technical term is for this, but when I was adding some fences as decorative bits I noticed the side of the fence connected to a fence gate was invisible, making the fence look hollow from certain angles. This occurred with all fences except the wired fence (though I assume that is because the connecting piece was small enough to be hidden by the fence gate)

https://imgur.com/a/2xCbHuR

Labels: 1.16.5, Macaw's Fences, Bug, Texture

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.2 update for Macaw's Fences (1.16.5)
