### ISSUE TITLE
Stone Bridges Do Not Let You Walk Up Them East and South

### ISSUE THREAD

**Issue by ace4x0** [sketchmacaw/MacawsModsIssues#130]
When you walk up from any type of staircase to specifically a stone bridge, the Minecraft character will not ascend the step. They get stuck when walking East and South up to a stone bridge block. When doing the same thing ascending North or West it works, but only if a non-transparent block is placed underneath the stone bridge block. I did this same test with a rope bridge block and there was no issue. The problem may be related to stone bridges being one pixel taller than rope bridges are.

Labels: 1.18: Macaw's Bridges, mcw-bridges-2.0.0-mc1.18.jar

**Comment by sketchmacaw** [comment]
Fixed in 1.0.2 for 1.18.1, later expect to fix it for 1.17 and 1.16.5.
