### ISSUE TITLE
Macaws Fences Update Checker useses the wrong URL

### ISSUE THREAD

**Issue by Silverminer007** [sketchmacaw/MacawsModsIssues#132]
As said in the title, Macaw's Fences and Walls specifies the wrong URL for the Update checker and check fails. Change `https://github.com/sketchmacaw/macawsmods/blob/master/fences.json` to `https://github.com/sketchmacaw/macawsmods/raw/master/fences.json` in the `mods.toml` file to fix that issue
[latest.log](https://github.com/sketchmacaw/MacawsModsIssues/files/7693805/latest.log)

Labels: 1.18 (probably more), Macaws Fences and Walls, Bug

**Comment by sketchmacaw** [comment]
Fixed in 1.0.2 for 1.18.1, later expect to fix it for 1.17 and 1.16.5.
