### ISSUE TITLE
Bridge stair are messing up next to stairs

### ISSUE THREAD

**Issue by sketchmacaw** [sketchmacaw/MacawsModsIssues#135]
Birch bridge stairs, when up against a solid block, (Dacite Brick Stairs from Oh the Biomes You'll go, in this instance), it xrays the ground and shows sky/underground.
Looks like it does it up against any stair.

![image](https://user-images.githubusercontent.com/60577275/146655300-1d78ddac-2505-47fb-8297-3df56e23b941.png)
![image](https://user-images.githubusercontent.com/60577275/146655301-b70d71b0-3474-4655-812f-78bb97007dd3.png)

**Comment by Samlegamer** [comment]
I also noticed this
![2022-01-16_16 53 25](https://user-images.githubusercontent.com/83614614/149668277-392475d3-ef0f-4cc4-8fd2-e7ed7736cb25.png)
:

**Comment by sketchmacaw** [comment]
Fixed in 2.0.2 Update
