### ISSUE TITLE
[suggestion] barn door adjustments (recipe, behavior)

### ISSUE THREAD

**Issue by esotericist** [sketchmacaw/MacawsModsIssues#141]
the first thing i noticed is that windowless barn doors require windowed barn doors to craft first, resulting in a strange glass tax for a door that won't have a window in it. it wold be nice if a recipe that doesn't require glass.

the second thing is i was rather surprised to discover the barn doors don't behave like the stable doors; most barn doors i've dealt with irl were on tracks and slid sideways. i was really hoping for something that behaved like the stable doors, but didn't have a window, so if these aren't made to do that, another door with that behavior would be really nice.

**Comment by sketchmacaw** [comment]
Recipe adjusted in 1.0.6
I will see what I can do about the other issue in another update
