### ISSUE TITLE
[suggestion] blackstone all the things, and maybe basalt too

### ISSUE THREAD

**Issue by esotericist** [sketchmacaw/MacawsModsIssues#143]
i mean. maybe not ALL the things. but blackstone is quite a lovely material, and even if you can't incorporate all of its variants, having some more blackstone objects than the bridge and fence bits would be very nice. (in particular i'd like to see blackstone arrow slits, and gothic windows.

basalt could also use some love (but admittedly it's hideously shortchanged in vanilla, too)

**Comment by sketchmacaw** [comment]
I will be slowly adding to all updates blackstone variant, deepslate too.
