### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by ZEROX7** [sketchmacaw/MacawsModsIssues#144]
server crash log
[crash-2021-12-26_19.42.23-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/7780704/crash-2021-12-26_19.42.23-fml.txt)
:

**Comment by sketchmacaw** [comment]
Sorry for the late reply, but I believe that I've fixed it in the next update, have you tested it?

**Comment by ZEROX7** [comment]
yeah tahts fixed like a long time ago XD
