### ISSUE TITLE
missing texture macaw's trapdoors 1.12

### ISSUE THREAD

**Issue by Anarchy079** [sketchmacaw/MacawsModsIssues#151]
![unknown (2)](https://user-images.githubusercontent.com/30153463/151713734-7ea3ef0e-6bf4-45f1-9bb5-25b68b139ef8.png)

yes i noticed the texture missing on the sides. with the john smith legacy resource pack/texture. om the trap doors. is it due to the trap door sides using 16? while the texture pack is 32? or some weird error? and no i tried it without the texture pack and it works fine
also sorry first time using github text chat. so i dont entirely know how to do the labels.. and yes theres a guide but im very tired and the people who are having issues with it didnt bother doing it themselves.

**Comment by Anarchy079** [comment]
sorry for the trouble

**Comment by sketchmacaw** [comment]
What trouble? You just reported an issue (:
