### ISSUE TITLE
[Suggestion] Allow wooden objects to be used as furnace fuel

### ISSUE THREAD

**Issue by LivingLandmine** [sketchmacaw/MacawsModsIssues#152]
I suggest making all wooden objects in this mod series valid furnace fuel so making too much of a wooden block isn't a total waste.  Simple as that.

Labels: All versions, All Macaw Mods, Suggestion, Feature

**Comment by sketchmacaw** [comment]
This is a very great suggestion!!!!!! I love it so much!

**Comment by sketchmacaw** [comment]
Added for 1.0.3 Lights

**Comment by sketchmacaw** [comment]
added in 3.0.0 Update furniture
