### ISSUE TITLE
[1.16.5 Latest CF version] Walkways go invisible when solid block on top of them

### ISSUE THREAD

**Issue by Speiger** [sketchmacaw/MacawsModsIssues#154]
![image](https://user-images.githubusercontent.com/2556269/152606264-0f189701-73cf-4f5b-abc4-715190e9607c.png)
Fairly simple. The upwards facing quads of the walkway should not cull.

Might be worth fixing especially if crawling is a thing.

**Comment by sketchmacaw** [comment]
Fixed in 2.0.2 Update
