### ISSUE TITLE
[Macaw's Windows 2.0.2] Windows not syncing properly

### ISSUE THREAD

**Issue by Johnny2525** [sketchmacaw/MacawsModsIssues#155]
So basically on multiplayer the windows placed are not synced properly when placed by other players
(There are placed windows in the empty spaces)
![MC_windows_2022-02-05_b1](https://user-images.githubusercontent.com/4202240/152657433-19de69b2-f419-409f-a876-7aefed236c86.jpg)
Relogging fixes the blocks:
![MC_windows_2022-02-05_b2](https://user-images.githubusercontent.com/4202240/152657459-22975f18-0726-46e0-a8f9-88298dabbe18.png)

Also there is another bug where players don't see when other player opens/closes the windows.
So the player that opened the windows can walk through the open window but other players see the window as closed and cannot pass through it.

(I did not know how to add labels so I'll write them down here)
[1.16.5] [Macaw's Windows 2.0.2] [Bug]

**Comment by sketchmacaw** [comment]
Hello! I would like to ask if you use Macaw's Bridges or Roofs too?

**Comment by Johnny2525** [comment]
Hello,
No I am using Macaw's Windows by itself

**Comment by Nothic** [comment]
This seems similar to #186 , @Johnny2525 have you noticed 'ghost' blocks with other mods on your server too?

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
