### ISSUE TITLE
Furniture Mod bad URL

### ISSUE THREAD

**Issue by PanoptesDreams** [sketchmacaw/MacawsModsIssues#156]
The Furniture mod sends you to "https://www.curseforge.com/minecraft/mc-mods/macaws-furnitures" when it need to go here "https://www.curseforge.com/minecraft/mc-mods/macaws-furniture"
The difference being a single 's' on the end of the URL

Macaw's Furniture 2.0.1
MC 1.18.1

Bug

**Comment by sketchmacaw** [comment]
Fixed in 3.0.0 Update
