### ISSUE TITLE
enchanted tools have no effect

### ISSUE THREAD

**Issue by samplb** [sketchmacaw/MacawsModsIssues#158]
If you use a tool to destroy or simply remove a misplaced fence, an efficiency enchantment on the tools doesn't make the progress any faster than using a simple stone-tool. Didn't test it with any other mods yet.

Labels: mcw-fences-1.0.2-mc1.18.1, Macaw's fences, Bug,

**Comment by sketchmacaw** [comment]
Fixed in 1.0.5 for Trapdoors

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3 for Lights
