### ISSUE TITLE
Wrong texture for Lime Lamp

### ISSUE THREAD

**Issue by Jerome226** [sketchmacaw/MacawsModsIssues#160]
Basically, when you turn off a lime lamp it becomes blue

![2022-02-12_02 33 41](https://user-images.githubusercontent.com/55724525/153701934-ac42829a-9795-456d-887e-2af65cdd47d5.png)
![2022-02-12_02 33 49](https://user-images.githubusercontent.com/55724525/153701937-bd78c1be-040b-4783-af43-6be8fad3baad.png)

I use latest version for Forge 1.18.1 (1.0.2)

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3
