### ISSUE TITLE
Tinkers Construct Pattern recipie conflict with Cube Roof

### ISSUE THREAD

**Issue by starr274** [sketchmacaw/MacawsModsIssues#162]
1.18.1, Mc Caws Roofs, Cross Mod, recipie

The Cube Roof recipie set, 2 planks, 2 sticks, currently interferes with the Tinkers Construct pattern recipie by default, unless a recipie fixing mod like polymorph is used

**Comment by sketchmacaw** [comment]
Noted, will fix

**Comment by sketchmacaw** [comment]
Changed the recipe in 2.1.1, closing this issue.
