### ISSUE TITLE
[Suggestion] The ability to raise blinds

### ISSUE THREAD

**Issue by 0DeltaWaves** [sketchmacaw/MacawsModsIssues#164]
I love the appearance of the blinds but I almost never use them because they block the view. If they had a third state where they are raised, I think it would be great. Thanks for the consideration!

**Comment by sketchmacaw** [comment]
![Uploading 2022-10-01_15.37.17.png…]()
Coming in the next update

**Comment by sketchmacaw** [comment]
![2022-10-01_15 37 17](https://user-images.githubusercontent.com/60577275/193412534-ac53ea58-b0fa-47c4-a6f9-e5ec6b52473b.png)
Coming in the next update, great suggestion Thanks!

**Comment by 0DeltaWaves** [comment]
Beautiful! Thanks so much! I'm excited to use them!

**Comment by sketchmacaw** [comment]
Added in 2.1.0, you have to be crouching and right clicking on them to raise them
