### ISSUE TITLE
Server crash with Forbidden Arcanus

### ISSUE THREAD

**Issue by evhub** [sketchmacaw/MacawsModsIssues#166]
The server crashes occasionally when initializing with Macaw's Trapdoors and Forbidden Arcanus. I don't know exactly what's happening, but it looks to me like some sort of race condition due to non-threadsafe access.

Crash report: https://gist.github.com/evhub/ef44f19ec90e0cafeaf2781a63d5ac5d

Versions:
 - Macaw's Trapdoors: 1.0.4
 - Forge: 39.0.75
 - Minecraft: 1.18.1

Labels: 1.18.1, Macaw's Trapdoors, Crash

**Comment by sketchmacaw** [comment]
Have you tried any other Macaw's mod? I'm curious as if it is only with trapdoors.

**Comment by sketchmacaw** [comment]
Does this still happen in 1.0.5 too?
