### ISSUE TITLE
Error on joining Server Macaw's Lights and Lamps [Fabric]

### ISSUE THREAD

**Issue by Beleggrodion** [sketchmacaw/MacawsModsIssues#167]
I added Macaw's Lights and Lamps v1.0.2 for fabric on a custom modpack (which i play with friends) which is based on medival minecraft last week. All wokred well with the mod until today. Now i cannot join the server anymore, i receive the following error:

[https://ibb.co/tqQqq4w](https://ibb.co/tqQqq4w)

On the serverlog their is no error, only that i join an receive a disconnect.

[23:12:21] [Server thread/INFO]: Beleggrodion joined the game
[23:12:22] [Netty Epoll Server IO #4/INFO]: Priority overwritten for player . Normal: GRAVE / Robbing: INVENTORY
[23:12:22] [Server thread/INFO]: Beleggrodion lost connection: Disconnected
[23:12:22] [Server thread/INFO]: Beleggrodion left the game

Used Fabric Loader is 0.13.2 with Fabric API 0.46.4+1.18

Labels: 1.18.1, Macaw's Lights and Lamps, Bug, Fabric

**Comment by erikabourque** [comment]
Hello, I had to same error as Beleggrodion

**Comment by ninjasnipez64** [comment]
Also having the exact same issue on mod v1.0.2. 
Friends, girlfriend and myself have been playing on friend's server fine for the past week.
When I told GF that I couldn't connect she mentioned that she had placed some of the lights earlier today. Having the items in the world seems to have broke the server somehow :(


It's 2am so server owner is asleep, unlucky me. 


Also to note, Fabric is v0.13.1 & Fabric AP 0.46.4 +1.18

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3
