### ISSUE TITLE
Transparent texture of slab blocks

### ISSUE THREAD

**Issue by RedBeast1959** [sketchmacaw/MacawsModsIssues#169]
Version: 1.18.1
Forge: 39.0.88
Other mods: 1. Optifine(OptiFine HD U H4) - Complementary Shaders
2. Quark(Quark-3.1-340.jar)
![2022-02-28_00 15 55](https://user-images.githubusercontent.com/100399264/155888712-cb050b52-868f-4172-9eca-89da3802f792.png)
![2022-02-28_00 17 33](https://user-images.githubusercontent.com/100399264/155888731-927e253c-f2b2-4a58-b107-7e2408b09084.png)

When I put Top roof and Lower roof with every slab blocks, contact surface of slab blocks become transparent.
Only Top roof and Lower roof. Other roofs and window just works fine.

![2022-02-28_00 17 24](https://user-images.githubusercontent.com/100399264/155888760-379fff49-ea1d-4768-badc-55d88ffd9b41.png)

Also, this issue never happens on Full block.

P.S. I'm new to github, so I don't know how to put Labels. Sorry.

**Comment by sketchmacaw** [comment]
Fixed in 2.1.1
