### ISSUE TITLE
[Suggestion] [Doors] Make garage doors operable via redstone

### ISSUE THREAD

**Issue by wolrah** [sketchmacaw/MacawsModsIssues#171]
I would really love to be able to trigger my garage doors via redstone.  Not only would it be useful but it would be realistic.

It appears that someone was looking to request this as well in #157 but immediately closed their own issue.

**Comment by SigmaFlame** [comment]
I really need that too, like carpenter's block garage door­.

**Comment by sketchmacaw** [comment]
Added in the upcoming 1.0.7 update
