### ISSUE TITLE
[FABRIC; Fences and Walls] Mixin apply fails due to a mod incompatibility

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [sketchmacaw/MacawsModsIssues#172]
**MC** 1.18.2
**Fabric** API 0.47.10
**Macaw's Fences and Walls** 1.0.3
**[Gromov's Paintings](https://www.curseforge.com/minecraft/mc-mods/gromovs-paintings-forge-fabric)** 1.1

To reproduce:

1. Install FAPI, MFaW and GP
2. Try to launch the game
3. Crash on initializing

Log: https://gist.github.com/Footage2-Amply-Pounce/008c22c10b0c3b645ab6232f723d105a

(Not sure why your mod is showing as version 1.0.0 in the log, the jar I downloaded is "mcw-fences-1.0.3fabric-mc1.18.2")

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/lex2yhRpOM

**Comment by Footage2-Amply-Pounce** [comment]
Seems like it was fixed on Gromov's Paintings side: https://www.curseforge.com/minecraft/mc-mods/gromovs-paintings-forge-fabric/files/3735515

I'm now able to launch the game with both mods present without issues.

**Comment by sketchmacaw** [comment]
Yeah, I'm also fixing it so I'm reopening it.

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3b

**Comment by Footage2-Amply-Pounce** [comment]
Thanks! And not only that, but you also ported all your other mods to fabric, this is amazing!

**Comment by sketchmacaw** [comment]
Yeah except for furniture, but it will later come too (:
