### ISSUE TITLE
[Bug?] 1.18.1 windows mod does not load for 1.18.2

### ISSUE THREAD

**Issue by Nalwyn603** [sketchmacaw/MacawsModsIssues#173]
When trying to load the only 1.18 version of the windows mod in 1.18.2 it does not load as it requires 1.18.1. I'm unsure if this is intentional and the mod is just not yet updated, or if this version was meant to work for 1.18.2 as well

**Comment by sketchmacaw** [comment]
Mod is not yet updated, it will be ported to 1.18.1 soon

**Comment by CDAGaming** [comment]
This is referring to a 1.18.2 port, not 1.18.1 xD

**Comment by sketchmacaw** [comment]
Will be released today as 1.18.2 - v 2.0.3
