### ISSUE TITLE
1.18.2 port that fixes bugs

### ISSUE THREAD

**Issue by itsdinkd** [sketchmacaw/MacawsModsIssues#174]
This should also be released for 1.18.1 and working for 1.18.1. Many modpacks, like mine, AQM2, are stuck on 1.18.1 due to tons of mods not being updated to 1.18.2. Mods that are necessary, like FTB Quests, KubeJS, Better Nether, etc. etc. 

I'd appreciate it if you could backport the 1.18.2 changes to 1.18.1 so we can update our modpacks to fix these big problems. In the mean time, I'll have to remove the mod as there have been too many problems with the sound events. Would love to add it back with the fixes. Thanks!

**Comment by sketchmacaw** [comment]
Which mod ?

**Comment by itsdinkd** [comment]
Ah sorry, didnt know this was a general repo. 

The Lights and Lamps

**Comment by sketchmacaw** [comment]
And fabric right?

**Comment by itsdinkd** [comment]
Correct, fabric

**Comment by sketchmacaw** [comment]
Will do ASAP.

**Comment by itsdinkd** [comment]
Thank you <3 also thank you for the fast response.

**Comment by sketchmacaw** [comment]
Released a 1.0.3b version for 1.18.1 to adress this issue
