### ISSUE TITLE
[BUG] game crashes while opening

### ISSUE THREAD

**Issue by ilkerbey-01** [sketchmacaw/MacawsModsIssues#175]
**Describe the bug**
Game crashes when trying to open

**Mod name & Minecraft Version and Modloader**
https://paste.ee/p/sftKB

**Additional context**
Probably a mod incompatibly, not sure what it is tho sadly

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by ilkerbey-01** [comment]
ah I forgot to mention, as you can see in latest.log the one problematic is fences mod

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3b
