### ISSUE TITLE
Nether Brick Gothic Window placed on Grass Block crashed server

### ISSUE THREAD

**Issue by jdstankosky** [sketchmacaw/MacawsModsIssues#177]
**~~Nether Brick~~ Gothic Window placed ~~on Grass Block~~ crashed server**
One of my server members was trying out various windows by placing them ~~on the ground (Grass Block)~~ and the ~~Nether Brick~~ Gothic Window crashed the server ~~twice~~ three times. I tried to recreate the scenario but it did not crash for me. It seems to be working now, but here are the crash reports for the ~~two~~ three incidents.

Edit: They crashed the server again placing a Stone Gothic Window on a Stone Block this time. The user has been told to stop or they're grounded, hah.

**Macaw's Windows (mcw-windows-2.0.3fabric-mc1.18.2) - Installed on server and client**

[crash-2022-04-10_02.51.15-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/8458462/crash-2022-04-10_02.51.15-server.txt)
[crash-2022-04-10_02.48.47-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/8458464/crash-2022-04-10_02.48.47-server.txt)
[crash-2022-04-10_13.07.16-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/8459560/crash-2022-04-10_13.07.16-server.txt)

**Comment by sketchmacaw** [comment]
Fixed in v2.0.3b
