### ISSUE TITLE
can't craft street lamps

### ISSUE THREAD

**Issue by calliepaws** [sketchmacaw/MacawsModsIssues#178]
I am running a server with a custom made modpack I compiled and no one is able to craft Street Lamps. I can get them from creative, but the recipes do not work and when using Roughly Enough Items, the recipes do not appear for just the Lamp Post, Double Street Lamp Post, and the Soul Street Lamp Post and Soul Double Street Lamp Posts, but do for everything else. I will attach an image of all the mods that are in the client-side pack as well as the server, as it doesn't work on a singleplayer world for me either.
![client-side mods](https://user-images.githubusercontent.com/94473307/162629234-c3fe0e09-e11a-4c71-92ab-fbd1d7ac5e4c.jpg)
![server-side mods](https://user-images.githubusercontent.com/94473307/162629237-aaf2c8f4-09a1-4f15-bcff-acd2ece6ec2c.jpg)
.

(sorry this is my first time submitting an issue on github but i think i'm doing this right)

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.0.3c update
