### ISSUE TITLE
[Macaw's Lights and Lamps] Shaders compatibility

### ISSUE THREAD

**Issue by JENOVAAbsolute** [sketchmacaw/MacawsModsIssues#182]
Lamps and torches do not give off light when using SEUS PTGI HRR3

Macaw's Lights and Lamps - Forge 1.18.2

Vanilla lantern vs street lamps. I made sure to toggle the lights and lamps on and off
![2022-04-12_18 14 07](https://user-images.githubusercontent.com/60951301/163063931-a89f7d54-c0fd-4095-8706-1a9ebce2755a.png)

![2022-04-12_18 13 26](https://user-images.githubusercontent.com/60951301/163063920-4061b15e-fddd-474f-9ba0-8f6d8cfb36cd.png)

**Comment by jedcooper** [comment]
As a dirty fix I put the entities to the FIRST entry of Block.50 in the SEUS HRR3 Shader .zip block.properties:
`block.50=torch wall_torch campfire:lit=true lantern mcwlights:acacia_tiki_torch mcwlights:birch_tiki_torch mcwlights:black_ceiling_light mcwlights:black_lamp mcwlights:blue_ceiling_light mcwlights:blue_lamp mcwlights:brown_ceiling_light mcwlights:brown_lamp mcwlights:classic_street_lamp mcwlights:crimson_tiki_torch mcwlights:cyan_ceiling_light mcwlights:cyan_lamp mcwlights:dark_oak_tiki_torch mcwlights:desktop.ini mcwlights:double_street_lamp mcwlights:garden_light mcwlights:gray_ceiling_light mcwlights:gray_lamp mcwlights:green_ceiling_light mcwlights:green_lamp mcwlights:jungle_tiki_torch mcwlights:lava_lamp mcwlights:light_blue_ceiling_light mcwlights:light_blue_lamp mcwlights:light_gray_ceiling_light mcwlights:light_gray_lamp mcwlights:lime_ceiling_light mcwlights:lime_lamp mcwlights:magenta_ceiling_light mcwlights:magenta_lamp mcwlights:oak_tiki_torch mcwlights:orange_ceiling_light mcwlights:orange_lamp mcwlights:pink_ceiling_light mcwlights:pink_lamp mcwlights:purple_ceiling_light mcwlights:purple_lamp mcwlights:red_ceiling_light mcwlights:red_lamp mcwlights:soul_acacia_tiki_torch mcwlights:soul_birch_tiki_torch mcwlights:soul_classic_street_lamp mcwlights:soul_crimson_tiki_torch mcwlights:soul_dark_oak_tiki_torch mcwlights:soul_double_street_lamp mcwlights:soul_jungle_tiki_torch mcwlights:soul_oak_tiki_torch mcwlights:soul_spruce_tiki_torch mcwlights:soul_warped_tiki_torch mcwlights:spruce_tiki_torch mcwlights:warped_tiki_torch mcwlights:white_ceiling_light mcwlights:white_lamp mcwlights:yellow_ceiling_light mcwlights:yellow_lamp`

**Comment by sketchmacaw** [comment]
Could you try if this issue still happens in the newest 1.0.4 Lights update?

**Comment by JENOVAAbsolute** [comment]
> Could you try if this issue still happens in the newest 1.0.4 Lights update?

My PC is currently out of commission. Waiting to get the parts to get it back up and running. It'll be at least a week or two. I'll test when I can if nobody else has by that time. Thank you for your work.

**Comment by JENOVAAbsolute** [comment]
> Could you try if this issue still happens in the newest 1.0.4 Lights update?

Sorry it took me so long. I just tested. The issue still persists in the latest version for 1.19.2

**Comment by sketchmacaw** [comment]
This is so weird, for some shaders it works just fine like sildurs

**Comment by sketchmacaw** [comment]
I'm closing this issue, it works with some shaders, for seus you will have to do the "dirty fix" to make them work

> As a dirty fix I put the entities to the FIRST entry of Block.50 in the SEUS HRR3 Shader .zip block.properties:
> 
> `block.50=torch wall_torch campfire:lit=true lantern mcwlights:acacia_tiki_torch mcwlights:birch_tiki_torch mcwlights:black_ceiling_light mcwlights:black_lamp mcwlights:blue_ceiling_light mcwlights:blue_lamp mcwlights:brown_ceiling_light mcwlights:brown_lamp mcwlights:classic_street_lamp mcwlights:crimson_tiki_torch mcwlights:cyan_ceiling_light mcwlights:cyan_lamp mcwlights:dark_oak_tiki_torch mcwlights:desktop.ini mcwlights:double_street_lamp mcwlights:garden_light mcwlights:gray_ceiling_light mcwlights:gray_lamp mcwlights:green_ceiling_light mcwlights:green_lamp mcwlights:jungle_tiki_torch mcwlights:lava_lamp mcwlights:light_blue_ceiling_light mcwlights:light_blue_lamp mcwlights:light_gray_ceiling_light mcwlights:light_gray_lamp mcwlights:lime_ceiling_light mcwlights:lime_lamp mcwlights:magenta_ceiling_light mcwlights:magenta_lamp mcwlights:oak_tiki_torch mcwlights:orange_ceiling_light mcwlights:orange_lamp mcwlights:pink_ceiling_light mcwlights:pink_lamp mcwlights:purple_ceiling_light mcwlights:purple_lamp mcwlights:red_ceiling_light mcwlights:red_lamp mcwlights:soul_acacia_tiki_torch mcwlights:soul_birch_tiki_torch mcwlights:soul_classic_street_lamp mcwlights:soul_crimson_tiki_torch mcwlights:soul_dark_oak_tiki_torch mcwlights:soul_double_street_lamp mcwlights:soul_jungle_tiki_torch mcwlights:soul_oak_tiki_torch mcwlights:soul_spruce_tiki_torch mcwlights:soul_warped_tiki_torch mcwlights:spruce_tiki_torch mcwlights:warped_tiki_torch mcwlights:white_ceiling_light mcwlights:white_lamp mcwlights:yellow_ceiling_light mcwlights:yellow_lamp`
> 
> OFC they cannot be switched on/off, they're always lit. I know there's a redstone_lamp or rather redstone_lamp_off/on texture used, but that's ATM out of my skills to change that properly. Maybe one can help?

**Comment by ADamianAO** [comment]
> As a dirty fix I put the entities to the FIRST entry of Block.50 in the SEUS HRR3 Shader .zip block.properties:
> 
> `block.50=torch wall_torch campfire:lit=true lantern mcwlights:acacia_tiki_torch mcwlights:birch_tiki_torch mcwlights:black_ceiling_light mcwlights:black_lamp mcwlights:blue_ceiling_light mcwlights:blue_lamp mcwlights:brown_ceiling_light mcwlights:brown_lamp mcwlights:classic_street_lamp mcwlights:crimson_tiki_torch mcwlights:cyan_ceiling_light mcwlights:cyan_lamp mcwlights:dark_oak_tiki_torch mcwlights:desktop.ini mcwlights:double_street_lamp mcwlights:garden_light mcwlights:gray_ceiling_light mcwlights:gray_lamp mcwlights:green_ceiling_light mcwlights:green_lamp mcwlights:jungle_tiki_torch mcwlights:lava_lamp mcwlights:light_blue_ceiling_light mcwlights:light_blue_lamp mcwlights:light_gray_ceiling_light mcwlights:light_gray_lamp mcwlights:lime_ceiling_light mcwlights:lime_lamp mcwlights:magenta_ceiling_light mcwlights:magenta_lamp mcwlights:oak_tiki_torch mcwlights:orange_ceiling_light mcwlights:orange_lamp mcwlights:pink_ceiling_light mcwlights:pink_lamp mcwlights:purple_ceiling_light mcwlights:purple_lamp mcwlights:red_ceiling_light mcwlights:red_lamp mcwlights:soul_acacia_tiki_torch mcwlights:soul_birch_tiki_torch mcwlights:soul_classic_street_lamp mcwlights:soul_crimson_tiki_torch mcwlights:soul_dark_oak_tiki_torch mcwlights:soul_double_street_lamp mcwlights:soul_jungle_tiki_torch mcwlights:soul_oak_tiki_torch mcwlights:soul_spruce_tiki_torch mcwlights:soul_warped_tiki_torch mcwlights:spruce_tiki_torch mcwlights:warped_tiki_torch mcwlights:white_ceiling_light mcwlights:white_lamp mcwlights:yellow_ceiling_light mcwlights:yellow_lamp`
> 
> OFC they cannot be switched on/off, they're always lit. I know there's a redstone_lamp or rather redstone_lamp_off/on texture used, but that's ATM out of my skills to change that properly. Maybe one can help?

to whitch on/off you just need to add :lit=true after the name, for example:

mcwlights:iron_double_candle_holder:lit=true

and thats it, sorry for comment 3 years later xd

do you have all the item names? I'll make a list
