### ISSUE TITLE
Razor wire on Oak Wired Fences renders solid

### ISSUE THREAD

**Issue by XFactHD** [sketchmacaw/MacawsModsIssues#183]
**Describe the bug**
The razor wire on the Oak Wired Fences renders solid, all other Wired Fences work fine.

**Mod name & Minecraft Version and Modloader**
Macaw's Fences and Walls
Minecraft 1.18.2
Forge 40.0.52 (also tested on 40.0.44 with the same result)

**To Reproduce**
1. Place two Oak Wired Fences next to each other
2. Observer incorrect rendering of the razor wire

**Screenshots**
Spruce Wired Fence on the left, works fine.
Oak Wired Fence on the right, renders incorrectly.
![2022-04-15_17 32 29](https://user-images.githubusercontent.com/11262040/163590451-d5f7f5d5-5cfb-41e0-b309-fe43130e3b82.png)

**Additional context**
No other mods were installed

**Comment by sketchmacaw** [comment]
Fixed in 1.0.4
