### ISSUE TITLE
Crashed, i dont know why.

### ISSUE THREAD

**Issue by TheButterbrotMan** [sketchmacaw/MacawsModsIssues#184]
**Describe the bug**
My server crashes today, i dont know how to reproduce.

**Mod name & Minecraft Version and Modloader**
Minecraft: 1.18.2
Fabric: 0.13.3
https://www.curseforge.com/minecraft/modpacks/deathdusk

https://bytebin.lucko.me/XXyQaJaJjT

**Comment by sketchmacaw** [comment]
Looks like it's the same or similiar to [177](https://github.com/sketchmacaw/MacawsModsIssues/issues/177)

**Comment by TheButterbrotMan** [comment]
Hey Macaw, will the fix come today. Or could this take some days?

Regards

**Comment by sketchmacaw** [comment]
I will try to release a fix version tomorrow.

**Comment by sketchmacaw** [comment]
Fixed in v2.0.3b
