### ISSUE TITLE
Consistent Server Crash - Macaw's Windows [FABRIC]

### ISSUE THREAD

**Issue by CYNO-MC** [sketchmacaw/MacawsModsIssues#185]
**Describe the bug**
Each and every time I place down a Stone Brick Gothic Window, the entire server will crash. I have a plethora of mods, but am unsure whether or not a confliction is occurring. Here is the crash report:
[crash-2022-04-17_05.31.21-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/8501059/crash-2022-04-17_05.31.21-server.txt)

**Macaw Windows - 1.18.2 - Fabric Launcher**

**To Reproduce**
1. Host dedicated server; connect with a friend
2. Place down Stone Brick Gothic Window
3. Immediately after, sit back and witness the Server Crash
4. Repeat; It's quite consistent for us

**Additional context**
Within a Modpack; The crash log should indicate exactly which mods are in the pack, most likely a confliction I'm unaware of!

**Comment by sketchmacaw** [comment]
Fixed in v2.0.3b
