### ISSUE TITLE
Macaw's Trapdoor causes Tech Reborn to have ghost blocks

### ISSUE THREAD

**Issue by Nothic** [sketchmacaw/MacawsModsIssues#186]
Minecraft Version : 1.18.1 Fabric 0.13.3
Mod Version : Macaw's Trapdoors 1.0.4/1.0.5 & Tech Reborn 5.10

This bug does not occur in SSP for me. It happens only when using client and server.

You may reproduce this bug by attempting to place down any cable from tech reborn when Macaw's Trapdoors is installed.

Below is a gif with the issue as described above.

https://imgur.com/a/J0DE14I

**Comment by sketchmacaw** [comment]
The fabric version for macaw's trapdoors doesn't support 1.18.1 just 1.18.2 at the moment.
