### ISSUE TITLE
Lower Top Roof (redwood)/upper lower roof (ether wood) reversed when used for exterior corner

### ISSUE THREAD

**Issue by Mumblemonster** [sketchmacaw/MacawsModsIssues#187]
**Describe the bug**
Lower Top roof (tried Ether and redwood) is diagonally reversed when placed as an exterior corner.

**Mod name & Minecraft Version and Modloader**
Macaw's Roofs - BOP; 1.18.2; Curseforge
**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
Place two lower roofs against a block to set up exterior corner placement
Place remaining roof as corner. 
Should see that the slope is inverted.

**Screenshots**
![2022-04-26_18 38 19](https://user-images.githubusercontent.com/104469687/165406853-06f79e21-3b3c-4bec-90c2-e59a8d25b2b9.png)

**Additional context**

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Should be fixed in the upcoming 2.2.0 update
