### ISSUE TITLE
Cyan Concrete Lower Base Roof is brown

### ISSUE THREAD

**Issue by 1e1001** [sketchmacaw/MacawsModsIssues#189]
**Describe the bug**
Cyan Concrete Lower Base Roof is brown

**Mod name & Minecraft Version and Modloader**
Macaw's Roofs 2.1.2
Minecraft 1.18.2
Fabric Loader 0.14.3

**To Reproduce**
1. Place down a Cyan Concrete Lower Base Roof
2. Place down a Brown Concrete Lower Base Roof next to it
2. They're the same colour

**Screenshots**
![image](https://user-images.githubusercontent.com/22437115/166611110-49b08738-bd22-492b-8693-7a6aa0337203.png)
(The block on the right is a Brown Concrete Lower Base Roof)

**Additional context**
I'm playing with other mods but i don't think that affects this

**Comment by Guinaro** [comment]
I temporarily corrected this issue with a resource pack.
The error sits in the cyan_concrete_lower.json file located in assets/mcwroofs/models/block/lower
Correct the reference from brown_concrete to cyan_concrete and it fixes the issue.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.0 update
