### ISSUE TITLE
2x1 window connectivity issue

### ISSUE THREAD

**Issue by Mofo50C** [sketchmacaw/MacawsModsIssues#19]
2x1 windows dont connect to glass panes properly. The bottom part connects but the top doesnt find the pane.

version: latest 1.12.2

![Screen Shot 2020-05-28 at 14 39 39](https://user-images.githubusercontent.com/21063744/83149227-c6238300-a0f1-11ea-8dac-2548e49041a4.png)

Labels: 1.12.2, Macaw's Windows

**Comment by Mofo50C** [comment]
the top half of the window also doesn't have a hit box as if its only one block but its graphics were stretched to 2 blocks high

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3 for 1.16.5
