### ISSUE TITLE
Double high Gothic window issue

### ISSUE THREAD

**Issue by UdoMorgenstern** [sketchmacaw/MacawsModsIssues#191]
**Describe the bug**
Double high Gothic window causing exception 

**Mod name & Minecraft Version and Modloader**
MC 1.18.2 Forge 40.1.0
mcw-windows-2.0.3-mc1.18.2.jar

**To Reproduce**
1. grab two mcwwindows:stone_brick_gothic
2. Place down 'em on top of each other
3. check server logs

**Screenshots**
visual it looks fine (i guess?)
![2022-05-09_19 35 36](https://user-images.githubusercontent.com/90903255/167467071-26ec8ec2-f86a-4847-af35-3ae48c738476.png)

**Additional context**
server has an expectation (no crash)
[windows.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/8653959/windows.txt)

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
