### ISSUE TITLE
Ice and Snow Themed Mod Parts

### ISSUE THREAD

**Issue by Nekohime1989** [sketchmacaw/MacawsModsIssues#194]
Who doesnt love ice and snow?
I think it would be really cool to have ice and snow parts for macaws mods.

This will be really cool to make sprawling complex bases amongst towering snowy peaks and ice spikes... :D

**Comment by sketchmacaw** [comment]
This could be included in the planned mod  "Macaw's Holiday Mod" great idea!

**Comment by Nekohime1989** [comment]
???
