### ISSUE TITLE
Wrong blocks getting placed quilt 1.18.2

### ISSUE THREAD

**Issue by Isabelle00125** [sketchmacaw/MacawsModsIssues#195]
**Describe the bug**
When placing a block (example: "Birch bridge") on a Quilt server, there ends up being a different block instead. Most/all mods seem broken. It will sometimes replace with blocks from other Macaw mods too.

**Mod name & Minecraft Version and Modloader**
Quilt 0.16.1
mcw-bridges-2.0.3fabric-mc1.18.2
mcw-doors-1.0.6fabric-mc1.18.2
mcw-fences-1.0.4fabric-mc1.18.2
mcw-lights-1.0.3c+fabric-mc1.18.2
mcw-paintings-1.0.3fabric-mc1.18.2
mcw-roofs-2.1.2fabric-mc1.18.2
mcw-trapdoors-1.0.5fabric-mc1.18.2
mcw-windows-2.0.3bfabric-mc1.18.2
qsl-1.1.0-beta.4_qfapi-1.0.0-beta.8_fapi-0.51.1_mc-1.18.2

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Pick a block. Some work but it seems most dont. I know Birch Bridge is broken.
2. Place down selected block
3. You should see a different block be placed than the intended one.

**Screenshots**
![bug](https://user-images.githubusercontent.com/92893061/170554379-38294efd-873f-4971-a609-1660a2fdec73.png)

**Additional context**
I tried testing it on a fabric server too and it seems to work there. It seems only the Quilt server is bugged regardless of whether client is fabric or quilt. Also Quilt in singleplayer still works only dedicated server doesn't.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
I believe quilt and fabric are different modloaders, that could be why it doesn't work correctly.

**Comment by sketchmacaw** [comment]
Yup quilt and fabric is not working together
