### ISSUE TITLE
Hud issue

### ISSUE THREAD

**Issue by tcsummers3** [sketchmacaw/MacawsModsIssues#196]
**Describe the bug**
HuD message after crafting window grill base. "Window Grille Base 100%"

**Mod name & Minecraft Version and Modloader**
forge 36.2.33, Life in the village 2, Minecraft 1.16.5

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Craft window Grille base

**Screenshots**

**Additional context**

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Hello, do you have the latest 2.0.3 Windows version in the pack?

**Comment by tcsummers3** [comment]
Thanks for reaching out. Turns out it was a user error.

My apologies.

**Comment by sketchmacaw** [comment]
No worries, have a nice day :)
