### ISSUE TITLE
Blackstone Windows

### ISSUE THREAD

**Issue by Lafolie** [sketchmacaw/MacawsModsIssues#198]
Hello, I would like to suggest the addition of blackstone window parts to complement the other stones ones. In particular, I was disappointed to find that there are no blackstone gothic frames - the perfect material for this sort of construction!

Thanks.

**Comment by sketchmacaw** [comment]
You can expect them in the next update, great suggesstion.

**Comment by Lafolie** [comment]
Awesome, I look forward to it ^ - ^

**Comment by sketchmacaw** [comment]
Added in 2.1.0
