### ISSUE TITLE
Storage furniture has no inventory. [Multiplayer]

### ISSUE THREAD

**Issue by Zubbywolf** [sketchmacaw/MacawsModsIssues#199]
On my 1.16.5 server, cupboards and drawers have no accessible inventories to store things inside of. Right clicking does nothing at all.
These were spawned in to be tested before using the resources, if that makes any difference.
Macaw's Furniture - Minecraft 1.16.5 - Forge 36.2.35

Thanks so much!

**Comment by sketchmacaw** [comment]
If they were spawned before the 3.0.0 version then that is causing it.
