### ISSUE TITLE
[1.18.2 Forge] Dark oak furniture has an underscore (Dark_oak [...] instead of Dark oak [...])

### ISSUE THREAD

**Issue by GeorgeOrwell1** [sketchmacaw/MacawsModsIssues#201]
**Describe the bug**
As stated in the title, there is a very small spelling mistake in all of the dark oak related furniture items in Macaw's Furniture Mod.

**Mod name & Minecraft Version and Modloader**
Minecraft 1.18.2
Macaw's Furniture 3.0.0
Forge

**To Reproduce**
1. Download mod.
2. Open creative world.
3. Search for the furniture tab in the creative inventory.
4. Observe the name of dark oak furniture by hovering over them with your mouse.

**Screenshots**
![2022-06-14_15 44 33](https://user-images.githubusercontent.com/72312697/173593125-b9372ee2-76d1-4e75-a4f0-1fc20d1b0a48.png)

**Additional context**
No.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the latest 3.0.1 update
