### ISSUE TITLE
Bridge Guard Rails Suggestion

### ISSUE THREAD

**Issue by Lafolie** [sketchmacaw/MacawsModsIssues#202]
Hi, I love the bridges, but I have a suggestion that I think will make them much more intuitive to use.

Currently, using the tool to edit the rails on bridges has major caveats and limits their use (which you acknowledged in the video trailer). I tried to build a pier using them, and had to replace it with wood slabs because of this.

You may not like this suggestion as it entails a lot of work (I am a fellow mod maker so I understand the struggle haha!), but here is how I envision the scissor tool. It simple: using the tool toggles the rail, no matter what arrangement it is currently in. This would enable much more flexibility and control over how the bridge looks. The state for a bridge block only needs a 4-bit mask, with a bit for each side.

The only limitation it really needs is that a rail should not appear on any adjoining edge with another bridge block (perhaps only for blocks of the same material).

I also noticed that each material type is a distinct block, which clutters up the recipe book. It would be nice if they were grouped together like the vanilla wood blocks, using material types.

I really like the bridges. If the source was available I'd do it myself and make a PR. This issue is preventing me from using them in many parts of my castle though :(

**Comment by sketchmacaw** [comment]
I'll try to make this possible, but now in the most recent update since this is a huge change

**Comment by sketchmacaw** [comment]
Oh, I added your suggestion with the recipe book clutter! And it will be implemented in each Macaw's Mod

**Comment by Lafolie** [comment]
Awesome! Thanks so much, keep up the awesome work.

**Comment by sketchmacaw** [comment]
Fixed in 3.0.0, pliers can now toggle into every possible way
