### ISSUE TITLE
Sliding Door Make Mobs Stuck.

### ISSUE THREAD

**Issue by ardissaps** [sketchmacaw/MacawsModsIssues#204]
Maybe can reduce the colision/hitbox model?
![image](https://user-images.githubusercontent.com/82106625/175475473-4aa1a35f-1cbe-4014-a1e3-8d9e306215a3.png)

**Comment by sketchmacaw** [comment]
Great idea, will implement in next update

**Comment by sketchmacaw** [comment]
As I said it will be changed in the next update for doors closing for now, but will be implemented dont worry.
