### ISSUE TITLE
No longer compatible with "Cycle Paintings (Fabric)"?

### ISSUE THREAD

**Issue by Sinuce** [sketchmacaw/MacawsModsIssues#205]
**Description of bug**
Vanilla Minecraft paintings cycle fine with [Cycle Paintings (Fabric)](https://www.curseforge.com/minecraft/mc-mods/cycle-paintings-fabric) - but Macaw's paintings do not.

**Versions**
Macaw's Paintings [v1.0.3 / mc1.19 - Fabric](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings/files/3828045)
Minecraft 1.19, Fabric API 0.56.3
Mod Loader 0.14.8

**To Reproduce**
1. Simply try to cycle paintings by right-clicking (with another painting in hand)
2. Vanilla paintings cycle, but not Macaw's

Here's my console paste, when I try to cycle:
[https://controlc.com/2152ebaa](https://controlc.com/2152ebaa)

A similar issue has been posted [here](https://github.com/ricksouth/serilum-mc-mods/issues/1002), since I do not know which of the two mods is causing the error.

Thank you in advance.

**Comment by sketchmacaw** [comment]
Looks like the issue is on Cycle Paintings side

**Comment by ricksouth** [comment]
This has been fixed (finally) in the latest version :)
