### ISSUE TITLE
Directional lighting glitch with several of the roof blockstates

### ISSUE THREAD

**Issue by e-SonOfAnder** [sketchmacaw/MacawsModsIssues#206]
**Describe the bug**
Lighting on a handful of the roof blockstates results in strange artefacting. Screenshots included.

**Mod name & Minecraft Version and Modloader**
Mod: Macaw's Roofs 2.1.2
Modloader: Forge 40.1.31
Modpack: All The Mods 7

**To Reproduce**
1. Place an outward facing ring of roof blocks
2. Place an outward facing ring of inverted roof blocks
3. Place an inward facing ring of roof blocks (Optional - no glitches observed with these blocks)
4. Place an inward facing ring of inverted roof blocks 
5. Observe strange lighting behavior on various blockstates

**Screenshots**
North is at the top of all screenshots. The lighting issues are directional.

Outward facing roof segments
![roof blocks](https://user-images.githubusercontent.com/4420108/176024381-f79d825e-693f-47c3-974c-bdc9c5bdfc2c.png)
Northwest corner block - lighter segment at base next to corner (north side), and at top next to the corner (north side)
Northeast corner block - lighter segment at base next to corner (east side)
Southeast corner block - large light segment at base next to corner (east side), light stripe near outer corner (south side), large light strip (west side)
Southwest corner block - lighter segment at top next to corner (west side)

Outward facing inverted roof segments
![roof blocks inverted](https://user-images.githubusercontent.com/4420108/176025246-4a496700-1c4d-4c6f-895d-596880272691.png)
Northeast corner block - darker segment at peak corner (east side), dark segments at base on either side of the corner
Southeast corner block - darker segment at base corner (east side), dark stripe mid block (east side)
South block - dark stripe at base (south side)
Southwest corner block - dark segments at base on either side of the corner
Northwest corner block - dark segments at base on either side of the corner

Inward facing inverted roof segments
![roof blocks inward inverted](https://user-images.githubusercontent.com/4420108/176025881-bf80588e-ebbe-4bc9-ab08-a6963e381732.png)
North block - dark stripe at base (south side)
Northeast corner block - dark segment at base near corner (west side)

Apologies if my verbiage gets confusing on these - I tried to maintain a consistent way of referring to the locations on each block along with the related screenshot.

**Additional context**
I have not tried installing the Macaw's Roofs mod stand alone, as these issues appear to be texture and lighting related, rather than anything conflicting within the modpack. No shaders are being used. White terracotta is being used in the screenshots purely as an example as it is easier to see the issue on it than some of the other blocks, but from my testing this issue is universal across all of the materials in the same locations.

Love what you've done with the mod, and if I had any expertise in working with textures and lighting, I'd submit a PR to try and help out, but this one is outside of my realm!

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.0 update
