### ISSUE TITLE
[Crash] Placing any window causes game to crash

### ISSUE THREAD

**Issue by issuehaver** [sketchmacaw/MacawsModsIssues#207]
I am playing on 1.18 with Fabric installed, alongside various other mods. I have many other Macaws mods installed and none are giving me any problems aside from the windows. 

Every time I go into a world and place any item from Macaw's Windows, the game immediately crashes. 

The other Macaws mods behave normally.

[Here is the crash report.](https://pastebin.com/xqgAAiMn)

I'm not very savvy with this sort of stuff, so sorry if I've explained something wrong or the issue is very stupid.
Thank you very much in advance!

**Comment by sketchmacaw** [comment]
The Windows work for 1.18.2 fabric only, sorry!
