### ISSUE TITLE
Macaw's Furniture Crash with Forge 41.0.94

### ISSUE THREAD

**Issue by Gamemassa** [sketchmacaw/MacawsModsIssues#208]
**Description**
I loaded Minecraft with Macaw's furniture and got an error message and a crash.

**Minecraft version:** 1.19
**Forge version:** 41.0.94
**Mod Version:** 3.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/18667108/178521715-c5ca20c2-74f6-4836-9be8-1b28f23245c3.png)

**Additional context**

[crash-2022-07-12_10.56.47-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/9094291/crash-2022-07-12_10.56.47-fml.txt)

**Comment by sketchmacaw** [comment]
Fixed in the latest 3.0.1 update
