### ISSUE TITLE
bamboo fence and trapdoor have same recipe

### ISSUE THREAD

**Issue by t1nym0us3** [sketchmacaw/MacawsModsIssues#209]
bamboo fence and trapdoor have same recipe

**Mod name & Minecraft Version and Modloader**
Macaw's Trapdoors with Macaw's Fences and Walls in 1.19 on Fabric-0.14.8

The bamboo fence and trapdoor both share the same recipe and will always produce bamboo trapdoors.  I offer the suggestion that bamboo trapdoors are made from just 4 bamboo in a square like the vanilla iron trapdoor recipe.

![bamboo fencetrapdoor](https://user-images.githubusercontent.com/109420539/179355124-b829a0c4-1a50-498f-8f14-2aab61173374.png)

**Comment by tazzy989** [comment]
Just ran into the same issue, polymorph isn't updated to 1.19 and I don't know how to edit recipes myself. If not this, another solution would be to make the fence recipe a bit different, like this:
|               |
|       |       |
        |
        
Bamboo fencing also doesn't seem to have a gate?

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.6 update for Fences
