### ISSUE TITLE
Top roofs aren't able to switch direction unless connected to another roof of the same type

### ISSUE THREAD

**Issue by 7z99** [sketchmacaw/MacawsModsIssues#212]
**Describe the bug**
Top roofs cannot switch direction unless they're connected to another top roof of the same type. This is problematic if you're trying to create a sort of outlined roof design where the outermost layer of roofs are different material. Ideally one of three things would happen: 1, depending on the camera's orientation, it will switch directions and face the same direction as the camera, or 2, the direction of the top roof can be switched with the roofing hammer, or 3, it can connect to any other top roof, not just one of the same material.

**Mod name & Minecraft Version and Modloader**
Macaw's Roofs, Fabric 0.14.8 (MC version 1.19)

**To Reproduce**
Steps to reproduce the behaviour:
1. In a world, place any top roof. 
2. Attempt to place a different material top roof of a different material perpendicular to the direction the roof is facing, **OR** right click it with a roofing hammer, the direction will not change.
3. Observe that the top roofs do not connect/switch direction.

It's possible to bypass this behaviour with a debug stick but it obviously is not elegant if you're trying to do something and do not have admin commands to give yourself a debug stick. 

![image](https://user-images.githubusercontent.com/104286985/180882300-e23de311-edf7-40fd-8948-d1e1a1d2ade8.png)
https://user-images.githubusercontent.com/104286985/180882505-6d271c13-6dd5-45da-b9da-15092961c430.mp4

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.0 update, now after right clicking with the roofing hammer it will rotate the block
