### ISSUE TITLE
[1.19 | Forge] Render issue with bridge stairs and snow

### ISSUE THREAD

**Issue by Illios42** [sketchmacaw/MacawsModsIssues#213]
**Describe the bug**
When a bridge stair of any kind is placed in snow (up to the three layers) it'll render the sides of the snow as see-through, providing a way to see cave systems and other hidden blocks below. If one adds any more snow on top, it'll turn back to how it should look like.

**Mod name & Minecraft Version and Modloader**
- Macaw's Bridges vers. 2.0.3
- 1.19
- Forge vers. 41.0.110

**To Reproduce**
1. Place down any bridge stair (tested with bamboo & rope dark oak).
2. Surround it with snow (Up to three layers stacked).

**Screenshots**

![2022-07-27_14 55 38](https://user-images.githubusercontent.com/101580687/181262612-28e0e3be-d8b6-434d-bb0c-dc8221f6fcd1.png)
![2022-07-27_15 39 29](https://user-images.githubusercontent.com/101580687/181262705-57b7d0cd-1a0a-44b3-86b9-f0940d4e1a04.png)

**Additional context**
Also replicable with stairs from the Biomes O' Plenty compat mod and it only appear to affect the snow on the sides, not the end where you walk up from.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.0.4 update
