### ISSUE TITLE
Server crash with "Macaw's Lights and Lamp"s & "Every Compat"

### ISSUE THREAD

**Issue by Jbeuh77** [sketchmacaw/MacawsModsIssues#215]
Server crashing while starting due to conflict between Macaw's Lights and Lamps & Every Compat

Minecraft version : 1.18.2
Forge version : 40.1.68

Macaw's Lights and Lamps version : mcw-lights-1.0.4-mc1.18.2.jar (last version)
Every Compat version : everycomp-1.18.2-1.5.9.jar (last version)

Server was working fine with previous Macaw's Lights and Lamps version (mcw-lights-1.0.3-mc1.18.2.jar) and same Every Compat version.

Obviously caused by some stuff around the SoulTikiTorch

[crash-2022-08-02_08.58.37-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/9243162/crash-2022-08-02_08.58.37-fml.txt)

**Comment by sketchmacaw** [comment]
Every Compat needs to change their mod because I changed the objects

**Comment by Gamemassa** [comment]
@Jbeuh77 I noticed this issue as well. I posted it on EveryCompat's GitHub page (and their CurseForge page, which surprisingly had a separate Issues tab), but I haven't heard anything back from them.

**Comment by sketchmacaw** [comment]
Did every compat fixed this issue in their newest version?

**Comment by sketchmacaw** [comment]
I think it is fixed https://www.curseforge.com/minecraft/mc-mods/every-compat/issues/24
