### ISSUE TITLE
Items disappear when placing

### ISSUE THREAD

**Issue by Sanderbloem050** [sketchmacaw/MacawsModsIssues#216]
**Describe the bug**
When i place the items as in fence or lamp then the item doesnt got placed.
it disappears right away.

**Mod name & Minecraft Version and Modloader**
Macaw's FencesV1.0.6  and Macaw's Lights and Lamps 1.0.4

**To Reproduce**
1. Go to 'Inventory'
2. Place down 'Fence (any type)'
3. Go  ''
4. This is the issue 'There is no fence'

**Screenshots**
![2022-08-04_22 18 16](https://user-images.githubusercontent.com/58403275/182944841-a6dc67eb-97d7-41ed-8e6e-408befa759d3.png)

**Additional context**
Log files from server and client are uploaded aswel

**Thanks!**
Thank you for helping me by reporting issues c:

[latest-client.log](https://github.com/sketchmacaw/MacawsModsIssues/files/9263047/latest-client.log)

[latest.log](https://github.com/sketchmacaw/MacawsModsIssues/files/9263021/latest.log)

**Comment by Sanderbloem050** [comment]
![mods2](https://user-images.githubusercontent.com/58403275/182946141-10bc994f-3f59-434d-a579-f22b1e946a46.png)

This is the list of mods that are on the server

**Comment by Sanderbloem050** [comment]
![mods3](https://user-images.githubusercontent.com/58403275/182946303-57e352ce-b1dc-4b64-8282-9f0a7ba9db5b.png)

this is the list of mods installed

**Comment by sketchmacaw** [comment]
Do you have the mods installed on your server?

**Comment by sketchmacaw** [comment]
Have you solved it?

**Comment by sketchmacaw** [comment]
In the earlier log it looks like it is on a server without fabric/forge just Paper

**Comment by sketchmacaw** [comment]
Does this issue still persist even with the latest Macaw's updates? We tried to fix this multiple times
