### ISSUE TITLE
EveryCompat 1.19-2.02 causing conflict with Macaw's Lights & Lamps

### ISSUE THREAD

**Issue by Gamemassa** [sketchmacaw/MacawsModsIssues#217]
Minecraft Version: 1.19.1
Forge Version: 42.0.1
EveryCompat version: 2.02

Not sure if this is the same type of issue posted [here](https://github.com/sketchmacaw/MacawsModsIssues/issues/215), but a few days ago I got a mod loading error that indicated a conflict between the latest versions of EveryCompat (2.02) and Macaw's Lights & Lamps (1.04) on the latest version of Minecraft/Forge. I'm assuming the issue is with EveryCompat not reading something correctly.I have attached the crash report and latest.log files below.

Crash Report
https://gist.github.com/Gamemassa/615eb47a6748602a9cf078b5bd7fa9d7

Latest Log
https://gist.github.com/Gamemassa/2eb2d188148bcafd0777319e6e047361

**Comment by Gamemassa** [comment]
Sorry, I should clarify: I already posted this issue on the EveryCompat GitHub page a few days ago, but they haven't responded yet.

**Comment by sketchmacaw** [comment]
Did every compat fixed this issue in their newest version?

**Comment by Gamemassa** [comment]
The EveryCompat team actually haven't updated their Forge version since I posted this issue. (They also haven't responded to me over on their GitHub page.

**Comment by sketchmacaw** [comment]
I believe they fixed it in their version. https://www.curseforge.com/minecraft/mc-mods/every-compat/issues/24
