### ISSUE TITLE
Villagers cant use doors

### ISSUE THREAD

**Issue by sirben99** [sketchmacaw/MacawsModsIssues#219]
**Describe the bug**
In Fabric 1.18.2 version of Macaws Doors, villagers cant seem to open them

**Mod name & Minecraft Version and Modloader**
Mod: Macaws Door
Loader: Fabric
Minecraft Version: 1.18.2

**To Reproduce**
1. Put a door down and a bed or a work station to the other side
2. Villager just pushes it self to the door and doesent know how to open it
3. ???
4. Profit

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.7 update
