### ISSUE TITLE
[Lights &  lamps] Updating worlds to 1.18.2 causes corruption(?) 

### ISSUE THREAD

**Issue by 0DeltaWaves** [sketchmacaw/MacawsModsIssues#220]
Hi, really love your mods! Many of them are staples for any modded world I play on. 
Curiously, I have a strange issue that seems to be tied to the lamps & lights mod, which I have installed on two separate 1.18.1 worlds - I've tried to update the worlds to 1.18.2, but they both result in this error. 
![nb5zjlr637g91](https://user-images.githubusercontent.com/82335536/183303125-edd2dc86-656d-4ce5-8ee3-85cdae3d5d7c.png)
[Here's the log for one of them.](https://paste.ee/p/9N75a) 
I've updated forge + all the mods to the correct version, and even tried loading the worlds with no mods installed, but it still gives me this same error message.
I've tried replacing the world's save folder with one from backup, to no avail.
Someone on reddit said "the removal of two block-states from Macaws lights are causing the initial error and possibly the error in the level.dat file read",  which is why I'm making this issue. Are you able to confirm this? Thank you in advance.

**Comment by sketchmacaw** [comment]
Hello! I believe that this issue is because I decided to remove the sounds and decided to use the vanila ones instead. Be sure to make a backup of your world and just try to load it, it shouldn't corrupt it. If anything happens let me know.

**Comment by sketchmacaw** [comment]
[17:57:24] [Render thread/ERROR] [ne.mi.re.GameData/REGISTRIES]: Unidentified mapping from registry minecraft:sound_event
	mcwlights:block.light_switch: 1403
	mcwlights:block.torch_on: 1404

[17:57:24] [Render thread/WARN] [ne.mi.re.GameData/REGISTRIES]: Forge Mod Loader detected missing registry entries.

There are 2 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.


[17:57:24] [Render thread/WARN] [ne.mi.re.GameData/REGISTRIES]: Missing minecraft:sound_event:
    mcwlights:block.light_switch
    mcwlights:block.torch_on

**Comment by 0DeltaWaves** [comment]
Thank you for the prompt response! How do I continue and force the world to load in this case? The "safe mode" button doesn't do anything.

**Comment by sketchmacaw** [comment]
Oh my, I'll try to look it up that's very weird.

**Comment by sketchmacaw** [comment]
Should be fixed with the upcoming 1.0.5 update, damn this took longer than I wanted it to take
