### ISSUE TITLE
Mob Pathfinding Issue

### ISSUE THREAD

**Issue by BalefulHarbinger** [sketchmacaw/MacawsModsIssues#221]
I've noticed while trying to decorate a village that villagers (and mobs in general) seem to have an issue with moving around most furniture, and some lamps and roofs.

**Mod name & Minecraft Version and Modloader**
On 1.19, Forge 41.1.0, using mcw-furniture-3.0.1, lights-1.0.4, and roofs-2.1.2

**To Reproduce**
First, in creative mode create an enclosure out of any furniture item (more details will be given on specific type further in).
Then, spawn in a villager and a zombie (note I use a mod which stops mobs burning in sunlight).
As the villager attempts to run from the zombie, notice how he (the villager) just continues to run into the furniture wall without trying to jump over it.

Compare this to virtually any other block which the villager gladly jumps over. Placing furniture two blocks tall produces the same outcome, as if the villager doesn't recognize a block is in front of it. Replacing one section of blocks with a door does nothing to change the villager's behavior. The behavior of the zombie is similar, as villagers outside the enclosure won't goad it into jumping over the cabinet/wardrobe/chair to reach them either, so it continuously runs into the wall.

In a similar experiment, using magma blocks, the villager's behavior is much different. It knows there are blocks there but it can't jump on top of any of them, so it continuously runs around the enclosure. Replacing a block with a door however immediately prompts it to run for the door without any hesitation.

(For additional points, I've tested this with sheep and wolves with the same results: the sheep won't jump over a drawer/table/chair to get away from the wolf)

**Screenshots**
![2022-08-12_20 26 53](https://user-images.githubusercontent.com/111066603/184463460-7400a8f8-4349-45a1-9052-61d2e1d3ae0b.png)
The initial setup.

![2022-08-12_20 27 04](https://user-images.githubusercontent.com/111066603/184463464-a75db092-1201-49b8-8a3a-c33e6c8e6223.png)
As you can see, the villager just keeps running into the wall of drawers.

![2022-08-12_20 27 11](https://user-images.githubusercontent.com/111066603/184463490-5dcc3beb-5e00-4188-a19c-6eb246c464c9.png)
Even more villagers produce the same outcome.

![2022-08-12_20 28 09](https://user-images.githubusercontent.com/111066603/184463500-d609708d-66b0-4982-a198-be6a31695d2c.png)
A taller enclosure and a door do nothing to change the outcome.

![2022-08-12_20 28 49](https://user-images.githubusercontent.com/111066603/184463513-6ee7ba37-986b-4350-a4b1-6b1ae9060096.png)
As compared to using a block like granite, which easily saves the villager's life.

**Additional context**
I first noticed this issue while decorating a village of mine. A villager was trying to walk straight through a table I had sat out. At first I thought his AI has bugged out and tried pushing him around it, but he continued trying to walk through it as if he didn't know the table was even there. This got me around to testing this phenomena out. So through much experimentation I've compiled a small list of blocks from Macaw's mods that cause pathfinding behavior like this. It's by no means exhaustive as I didn't feel like going through every single block, but of them I've noted:

Furniture:
Wardrobes (All variants)
Bookshelves (all variants)
Tables (all variants)
Desks (all variants)
Chairs (all variants)

Lights:
Lamps
Paper Lamps
Ceiling Lamps

Roofs:
Attic Roofs
Cube Roofs

**Comment by sketchmacaw** [comment]
Fixed for Lights in the upcoming 1.0.5 update

**Comment by sketchmacaw** [comment]
Should be fixed in the upcoming 3.1.0 update
