### ISSUE TITLE
Footstep sounds?

### ISSUE THREAD

**Issue by crcabanillas** [sketchmacaw/MacawsModsIssues#223]
I'm not sure if this is a bug or not implemented or even not possible (fair enough), but there's no sound when walking across a bridge. Specifically, spruce bridge, 1.18.2 world.

I feel like I'm tiptoeing across bridges. Anyway, other than that, lovely mod. Thanks for all your work.

**Comment by sketchmacaw** [comment]
Yeah.. I believe is because of this Minecraft Bug
https://bugs.mojang.com/browse/MC-8820

**Comment by crcabanillas** [comment]
Fair enough, not much you can do about that then. :)
