### ISSUE TITLE
Mining tools broken

### ISSUE THREAD

**Issue by FluffyPashy** [sketchmacaw/MacawsModsIssues#225]
**Describe the bug**
Removes all Tool abilities/functions. e.g. mining speed, item-drop (it is like mining with the wrong tool or none).

**Mod name & Minecraft Version and Modloader**
mcw-roofs-2.2.0-mc1.18.2-fabric.jar
Fabric - 0.14.9

Others/Complete list of mods in use:
[modlist.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/9482829/modlist.txt)

**To Reproduce**
1. Updating from 2.1.2 to 2.2.0

**Comment by Traktool** [comment]
I can confirm that bug !
Exact same version Minecraft 1.18.2, Fabric 0.14.9, Mcw Roofs 2.2.0

**Comment by sketchmacaw** [comment]
Fixed in 2.2.0b, be sure to update
