### ISSUE TITLE
Furniture chairs cant be placed by a contraption (from create)

### ISSUE THREAD

**Issue by SrRapero720** [sketchmacaw/MacawsModsIssues#226]
**Describe the bug**
Furniture chairs (modern and normal) cannot be moved or placed by a contraption from the mod Create

**Mod name & Minecraft Version and Modloader**
- Forge: 40.1.74
- Macaw: 3.0.1

**To Reproduce**
1. Place a chair into a glued blocks and convert block into a contraption
2. Move the contraption (unplace, move, place)
3. Chair dissapear.

**Screenshots**
<video src="https://user-images.githubusercontent.com/29090346/188298167-64e69c50-092f-4eb8-b742-71f861c3a857.mp4"></video>

**Comment by sketchmacaw** [comment]
Does the "bar chair/stool" work from Macaw's mods?

**Comment by SrRapero720** [comment]
![image](https://user-images.githubusercontent.com/29090346/188544446-eaa6e361-9793-43b9-b612-a3bc0a2ba233.png)
yes

**Comment by SrRapero720** [comment]
![image](https://user-images.githubusercontent.com/29090346/188544509-9b05307f-52c0-4a7a-848e-077b84e1184a.png)

**Comment by sketchmacaw** [comment]
Awesome, will fix

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.2 update
