### ISSUE TITLE
Macaws Roof Mod Fails to load properly after new update.  

### ISSUE THREAD

**Issue by DarkestDread** [sketchmacaw/MacawsModsIssues#227]
I am playing a custom-made mod pack. The mod Macaws Roofs Updated today and after that Update I now get an error message saying that Macaws Roofs – BOP (macawsroofsbop) Failed to load correctly. The pack I am playing has both Macaws Roofs and Macaws Roofs Biomes o plenty.

**Macaws Roofs  Minecraft Version 1.16.5  Curse forge Version 36.2.21 *

**To Reproduce **
1.  open the mod pack  '
2. Wait for the Game to load 
3. Then you will get an error saying that Macaws Roofs – BOP (macawsroofsbop) Failed to load correctly.  
4. Finish 

**Screenshots**  Here is a Screenshot of the Error message I received 
![image](https://user-images.githubusercontent.com/112810985/188315946-8016cac5-8dbb-4375-bd54-c325e2ce0f26.png)

**Additional context**
This Custom mod pack uses all of the 
Macaws mods and  
 all of there Biomes o plenty Extras 
Except the oh the Biome  you'll go mods.  

I have Attached a full crash report  Below 

[crash-2022-09-04_14.53.18-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/9484821/crash-2022-09-04_14.53.18-fml.txt)

**Comment by sketchmacaw** [comment]
We are not the creators of Macaws Roofs – BOP.
They need to update their version to match our Macaw's Roofs
