### ISSUE TITLE
Goat horns dropped from goats crash other players when played.

### ISSUE THREAD

**Issue by jonah-rogers** [sketchmacaw/MacawsModsIssues#229]
**Description:**
The title pretty much says it all. Horns dropped from goats crash other players that hear the horn when it's played. It does not crash the player that uses the horn. We only tested it with the _seek_ and _feel_ horns, but I imagine it does it with the rest of them as well.

**Mod Name:** Macaw's Paintings
**Minecraft Version:** 1.19.2
**Modloader:** Forge 1.19.2-forge-43.1.1

**Steps to reproduce the behavior:**
1. Get a horn to drop from a goat.
2. Play the horn next to another player.
3. The player that hears the horn should crash and get the following error: _The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: applyTransform() must not be called on a vanilla ArmPose!_

**Comment by sketchmacaw** [comment]
Could you send me the whole log?

**Comment by sketchmacaw** [comment]
Not an issue from Macaw's Paintings.
Forge hotfixed this https://github.com/MinecraftForge/MinecraftForge/issues/8985
