### ISSUE TITLE
Global lighting bug

### ISSUE THREAD

**Issue by HeberonYT** [sketchmacaw/MacawsModsIssues#23]
Most bridges have lighting issues when using shaders.
forge 14.23.5.2847
mcw-bridges-1.0.4-mc1.12.2
Sildurs Vibrant Shaders v1.27 Extreme

![Screenshot_2](https://user-images.githubusercontent.com/13698597/84206895-bc950600-aa75-11ea-9602-bcea586f2714.png)
![Screenshot_3](https://user-images.githubusercontent.com/13698597/84206896-bdc63300-aa75-11ea-86c9-d0eaa4e40b0f.png)
![Screenshot_1](https://user-images.githubusercontent.com/13698597/84206898-bef76000-aa75-11ea-90cf-0af108ed2313.png)

>Labels: 1.12.2, Macaw's bridges, Bug, lighting

**Comment by sketchmacaw** [comment]
Going to fix in next update

**Comment by boneskull** [comment]
This seems to affect both furniture and bridges, e.g. large bookshelves are slightly transparent

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.0.0 Bridges Update
