### ISSUE TITLE
[Suggestion] Make the railing on bridges act the same as fences

### ISSUE THREAD

**Issue by Zygus42** [sketchmacaw/MacawsModsIssues#230]
Currently if you build a bridge, you can just walk over the banister if you have auto-jump on, as the railings act like a block, not a fence or wall.  This is particularly noticeable when you have bridges that are only 1 block wide, as you tend to walk up onto the banisters a lot.

**Comment by sketchmacaw** [comment]
Implemented suggestion in the upcoming 2.0.4 update
