### ISSUE TITLE
Paintings from other mods will not be available w/Macaw's paintings 

### ISSUE THREAD

**Issue by GodzillaFan13** [sketchmacaw/MacawsModsIssues#232]
just as the title says, paintings from other mods (such as Supplementaries and Alex's Mobs) will not be obtainable without another mod such as Cycle paintings. 

Macaw's paintings, for Forge 1.19.2-43.1.30

1. ![Screenshot (90)](https://user-images.githubusercontent.com/112220126/193396156-b07dcd77-33c2-46ff-8fc5-76120a92ff1b.png) have these mods installed on your minecraft client. 
3. load up world. place down painting.
4. place again and again, any other mod's paintings will not be available. 

**Additional context**
doesn't matter if it's on a server or on a singleplayer world, behavior affects both. 

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Yeah just tested this is weird

**Comment by sketchmacaw** [comment]
Update - I tested those two mods without macaw's paintings, and their paintings do not work.
