### ISSUE TITLE
Massive Optimization issue after hours of searching 

### ISSUE THREAD

**Issue by Zelioth** [sketchmacaw/MacawsModsIssues#233]
**Describe the bug**
Using Spark and Java Heap Dumps I was able to see what mods were doing while the client was running. I am running into an issue where a mod out of 400 mods is causing the "net.minecraft.client.renderer.block.model.multipart.KeyValueCondition$$Lambda$7662/0x0000000801076d80" to just generate so many block states it causes memory and optimization issues. After going through EVERY mod in my pack. Pulling a set group of mods that fixed the issue after being disabled the one group of mods that seemed to cause the issuse when on and fix the issue when disabled was the Macaw's mods. So i wen't in to a new Minecraft install and set each mod on it's own generating a heap stack with each set and found that Macaw's Roofs is generating over 10 Million Block states. 

This mod installed ALONE on a vanilla fresh install still shows it causing the over generation of blocks in the Heap Dumb. 

**Mod name & Minecraft Version and Modloader**
Minecraft 1.19.2
Forge - 43.1.27 - 43.1.33

This is going to be a couple of links to the Spark Heap Summarys showing the difference in block states I'll try to explain each. 

https://spark.lucko.me/bxwAdo8A6S - this one is the Macaw's Roofs turned off and all over mods off. which generated over 14Million

https://spark.lucko.me/sDzTwwX29h - this one is with NO Macaw's Mods turned on but all other mods that were suspected activate. 

https://spark.lucko.me/mCQc6JXYPI - this one is of Macaw's Furniture, fences, and walls on and not Macaw's Roofs.

**Comment by sketchmacaw** [comment]
Thank you for showing me this, this is now  my top priority to fix.
