### ISSUE TITLE
Block-Culling caused by Gutter blocks

### ISSUE THREAD

**Issue by Game-Log** [sketchmacaw/MacawsModsIssues#234]
Whenever I place a gutter of any color, the side of the block behind it becomes transparent. Furthermore for the horizontal gutters, blocks placed above it are also culled.

Macaw's Roofs (2.2.1), Minecraft 1.18.2, Fabric

1. Place a Gutter in front of a block.

![2022-10-15_10 01 54](https://user-images.githubusercontent.com/59855439/195990931-c6700012-4583-4eb8-b983-7a212cce3c43.png)

**Comment by marewey** [comment]
1.19.2 version has this as well

**Comment by sketchmacaw** [comment]
Fixed in the 2.2.2 update
