### ISSUE TITLE
mcwfences - render creative mode crash

### ISSUE THREAD

**Issue by XionioXMaster** [sketchmacaw/MacawsModsIssues#236]
**Describe the bug**
As soon as I open the 4 tab of blocks in creative mode, the crash occurs, fix it

**Mod name & Minecraft Version and Modloader**

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. [Go to '...'
2. Place down '....'
3. Open  '....'
4. This is the issue '....'](https://pastebin.com/7AX1XW2g)
As soon as I open the 4 tab of blocks in creative mode, the crash occurs, fix it

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://pastebin.com/7AX1XW2g)
**Additional context**
[Add any other context about the problem here.](https://pastebin.com/7AX1XW2g)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by XionioXMaster** [comment]
v1.0.6 / mc1.18.2 - Forge

**Comment by DonorKrovi** [comment]
Same crash, fix pls

**Comment by sketchmacaw** [comment]
Should be fixed in the upcoming 1.0.7 update
