### ISSUE TITLE
mcw-[VARIOUS] do not work on a SMP

### ISSUE THREAD

**Issue by Asylum-Media** [sketchmacaw/MacawsModsIssues#237]
**Describe the bug**
The following files do not work when used in a networked server multiplayer:
mcw-bridges-2.0.5-mc1.19.2fabric.jar
mcw-doors-1.0.7fabric-mc1.19.2.jar
mcw-lights-1.0.4fabric-mc1.19.2.jar
mcw-trapdoors-1.0.7fabric-mc1.19.2.jar
mcw-windows-2.0.3bfabric-mc1.19.jar

On recently adding the aforementioned files to our SMP (they were supposed to go in with the rest of your mods) we discovered none of the functions for these mods worked in an SMP environment.
Everything works perfectly in SSP.

**Mod name & Minecraft Version and Modloader**
mcw-bridges-2.0.5-mc1.19.2fabric.jar
mcw-doors-1.0.7fabric-mc1.19.2.jar
mcw-lights-1.0.4fabric-mc1.19.2.jar
mcw-trapdoors-1.0.7fabric-mc1.19.2.jar
mcw-windows-2.0.3bfabric-mc1.19.jar
Minecraft 1.19.2
Fabric- Launcher 0.11.1
            Loader 0.14.9

**To Reproduce**
Set up an external SMP environment
Try to use the aforementioned items (even the recipes don't show in JEI)

**Screenshots**
There wasn't really anything I could add in the way of screenshots, there is no error readout on the server/in logs etc.

**Additional context**
This only seems to be a SMP issue. SSP works without issue.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Do you have them installed on the server too or only client?

**Comment by sketchmacaw** [comment]
And are using the windows 1.19 version, it is not yet made for 1.19.2 that could cause it

**Comment by sketchmacaw** [comment]
Are you still experiencing this issue?

**Comment by sketchmacaw** [comment]
Looks like this has been resolved?
