### ISSUE TITLE
Collision model bug Macaw's Doors

### ISSUE THREAD

**Issue by MightyBunch** [sketchmacaw/MacawsModsIssues#238]
Bug with Stable doors and Stable horse Doors. It looks like you can walk through them even when they are closed, but there is an invisible door in the same position but facing a different direction that I can't walk through. I hope I explained it clearly.

Macaw's Doors 1.0.7
Minecraft 1.19.2
Forge 43.1.1

1. Place down Stable door or Stable horse door
2. Try to walk through them
3. Thats it, now you see the bug

Thank you in advance.

![111](https://user-images.githubusercontent.com/117296149/199533494-f73c5b1a-0c6f-4d90-b937-1c279f3b11c3.png)

**Comment by SpigotDE** [comment]
Same for me, you can walk through closed stable & stable_head doors 

But it blocks you on the wrong side of the block

So -> Door is facing north -> you walk from south and get blocked right at the edge of the block

You walk from north -> you can bypass / walk through the door in the middle

~ Fabric 1.19.2

**Comment by DiRtens** [comment]
https://github.com/sketchmacaw/MacawsModsIssues/issues/258#issue-1532640055

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.8 update
