### ISSUE TITLE
Fence model bug when using Diagonal Fences mod

### ISSUE THREAD

**Issue by LolJohn11** [sketchmacaw/MacawsModsIssues#239]
**Describe the bug**
When paired with the [Diagonal Fences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences) mod, some of the wooden fence models have "holes" in them when connected diagonally. See screenshots for examples. 
So far I've discovered this bug with only two types of wooden fences seen on the screenshots, the rest of them don't seem to have this model bug.

**Mod name & Minecraft Version and Modloader**
Macaw's Fences and Walls
Forge 43.1.43

**To Reproduce**
1. Have "Fences and Walls" and "Diagonal Fences" mods installed
2. Place down fences so that they connect diagonally
3. Notice the "holes" in the models as seen on the screenshots.

**Screenshots**
![2022-11-13_13 01 56](https://user-images.githubusercontent.com/49366383/201518827-15774424-aa9d-490e-9d91-a77ab4a34cc9.png)
![2022-11-13_13 02 45](https://user-images.githubusercontent.com/49366383/201518829-2615b8aa-740a-43d1-9059-4d85b9692fbd.png)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.7 update
