### ISSUE TITLE
[Question] Forge or Fabric?

### ISSUE THREAD

**Issue by systox** [sketchmacaw/MacawsModsIssues#24]
The new naming scheme for downloads is ambiguous. It's labeled as 1.16.1 while others are labeled forge. So is this compatible with fabric too now?

**Comment by sketchmacaw** [comment]
I'm so sorry! Forge, I will add a visible icon which will show forge.

**Comment by systox** [comment]
> I'm so sorry! Forge, I will add a visible icon which will show forge.

Thank you for the reply. No idea why cursegaming is disorganized lately.
