### ISSUE TITLE
[Suggestion] Support bridge corner with stairs

### ISSUE THREAD

**Issue by BurningLutz** [sketchmacaw/MacawsModsIssues#240]
As the picture, currently bridge corners are only supported with bridges. It would be very nice to have corners with stairs too!

![图片](https://user-images.githubusercontent.com/15797639/201909577-6d1a9c9b-adfd-4b20-8e07-ada9fd527343.png)
( The left-hand side is 3 bridges connected together, the right-hand side is 2 stairs at the end and 1 bridge in the middle )

**Comment by sketchmacaw** [comment]
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/60577275/fd87c71d-0925-4a7e-9401-e4f44690df8e)
In the upcoming update, there will be the option to toggle the bridge with pliers to modify it into a corner and making this possible

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.0 update
