### ISSUE TITLE
Game stuck on loading screen - Macaw's Bridges 1.19.2

### ISSUE THREAD

**Issue by SteampunkSquid** [sketchmacaw/MacawsModsIssues#241]
When I try loading Minecraft with Bridges for Forge, the game loads to 100%, unloads a bit, then stays on the Mojang loading screen (though the title screen music starts to play after a bit, nothing else happens). Removing the mod allows the game to load normally.

MC version: 1.19.2
Forge version: 43.1.52
Mod version: 2.0.5/1.19.2

Other mods I'm using:
AutoRegLib
Biomes O'Plenty
Create
Curios API
Every Compat
JEI
Moonlight Library
Quark
Supplementaries
TerraBlender
Traveler's Backpack

**Comment by sketchmacaw** [comment]
Should be fixed with the 2.0.6 performance update coming out in a few hours.
