### ISSUE TITLE
Macaw's Bridges Causes Severely Slower Loading Times

### ISSUE THREAD

**Issue by LolJohn11** [sketchmacaw/MacawsModsIssues#242]
**Describe the bug**
Enabling Macaw's Bridges increases the loading times significantly.
With other mods, but without Macaw's Bridges, my modded instance takes 55-60 seconds to load on average.
Just enabling Macaw's Bridges increases the load time to 1m45s - 1m50s. **About 80% slower.**

> **Mod name** - Macaw's Bridges 2.0.5
> **Minecraft Version** - 1.19.2
> **Modloader** - Forge 43.1.43

**To Reproduce**
1. Launch Minecraft
2. Note how long the game loads
4. Install Macaw's Bridges mod
5. Launch Minecraft again
6. Note the dramatic increase in loading time

**Logs**
["lastest.log" files](https://gist.github.com/LolJohn11/b6de1351f62257b16304522f539eee5b) that include launching the game, loading to main menu and then exiting the game - both WITH and WITHOUT Macaw's Bridges installed.

**Comment by sketchmacaw** [comment]
Should be fixed with the 2.0.6 performance update coming out in a few hours.
