### ISSUE TITLE
[1.19.2 Windows] shutters intersect each other and other blocks

### ISSUE THREAD

**Issue by 0DeltaWaves** [sketchmacaw/MacawsModsIssues#244]
Macaw's windows 2.1.0
1.19.2 forge

Place a shutter on a surface, and right click to open. Now you can place another shutter where the first one is, and the two will be occupying the same space. Shutters can also intersect solid blocks next to them when you open them.

![image](https://user-images.githubusercontent.com/82335536/204051010-a43f676b-31a5-44ea-ace0-533911e2ad48.png)
2 shutters intersecting

![image](https://user-images.githubusercontent.com/82335536/204050914-e3370fae-a33a-4c2a-b205-383458eb0590.png)
shutter inside wall

**Comment by sketchmacaw** [comment]
Works as intended, shouldn't be an issue as players can choose a side to place them and open in the window direction instead of the wall.
