### ISSUE TITLE
Can't open windows (Macaw's Windows)

### ISSUE THREAD

**Issue by LolJohn11** [sketchmacaw/MacawsModsIssues#245]
**Describe the bug**
Can't open any "openable" window from Macaw's Windows.

**Mod name & Minecraft Version and Modloader**
Minecraft 1.19.2
Forge 43.1.43
MCW Windows 2.1.0

**To Reproduce**
1. Place down any "openable" window block
2. Try opening the window
3. Fail

**Additional context**
No other mods seem to cause the issue - tested with just the MCW Windows and the issue persists.

**Comment by Eatham532** [comment]
In the most recent update of windows, Sketch removed the ability to open windows. This however will be a feature in a future update.

**Comment by esotericist** [comment]
i do hope whenever the feature gets re-added we're either able to choose between openable and non-openable windows, or able to lock them somehow. i previously found macaw's windows useless for most of my purposes because an accidental right click caused me no end of grief

**Comment by sketchmacaw** [comment]
> 

This is why I removed it for now, in the next update there will hopefully be a method to lock them or open

**Comment by sketchmacaw** [comment]
Reimplemented in the latest 2.2.0 update
