### ISSUE TITLE
[1.19.2] Textures for mangrove & crimson louvered shutters backwards

### ISSUE THREAD

**Issue by 0DeltaWaves** [sketchmacaw/MacawsModsIssues#246]
Macaw's Windows 2.1.0, forge

The texture for the mangrove louvered shutter is that of the crimson one, and vice versa.

![image](https://user-images.githubusercontent.com/82335536/204441918-46255dba-d297-43c5-b17f-166059505b0e.png)
![image](https://user-images.githubusercontent.com/82335536/204442050-9b669c2b-38ec-49ef-ab25-bf007e1fd2cc.png)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.1.1 update
