### ISSUE TITLE
Prismarine and Blackstone Parapet in 1.18.2  Macaw Windows version 2.1 are switched

### ISSUE THREAD

**Issue by Guinaro** [sketchmacaw/MacawsModsIssues#247]
The Model files of the Prismarine and Blackstone Parapets are mixed up.
Prismarine contains the data for Blackstone and vice versa

Macaw Windows 2.1.0

Prismarine Textures in Parapet Model should refer to: prismarine_bricks
Blackstone Textures in Parapet Model should refer to: polished_blackstone

Those that cannot wait, can do it themselves with a datapack.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.1.1 update
