### ISSUE TITLE
Model and Hitbox Error

### ISSUE THREAD

**Issue by mjschiermeier1** [sketchmacaw/MacawsModsIssues#248]
**Describe the bug**
The model for the gutters does not line up with the blocks. Also, the hitbox is too large for the block.

**Mod name & Minecraft Version and Modloader**
Macaw's Roofs 2.2.1
Minecraft 1.18.2 Forge 40.1.60

**To Reproduce**
1. Place the roof
2. at the base of the roof place gutter

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/119654889/205235794-90403614-2651-4d72-9515-ca241634de21.png)

**Thanks!**

Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the 2.2.2 update
