### ISSUE TITLE
Non-Full Block Culling.

### ISSUE THREAD

**Issue by Aquaeyes** [sketchmacaw/MacawsModsIssues#249]
**Describe the bug**
Path Blocks culled on QFAPI/QSL 4.0.0/3.0.0 and MccawsRoofs 

**Mod name & Minecraft Version and Modloader**
 mcw-roofs-2.2.2-mc1.19.2fabric.jar
 qfapi-4.0.0-beta.24_qsl-3.0.0-beta.24_fapi-0.68.0_mc-1.19.2.jar

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Go to path block
2. Place roof next to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/10935410/208822442-d21b11b2-6031-496c-9dda-69539ca67447.png)

**Comment by Aquaeyes** [comment]
Also occurs with lower half slabs.

**Comment by Daverkex** [comment]
I have another example with mod's blocks interaction:

![2023-02-19_13 16 35](https://user-images.githubusercontent.com/144762/219947421-a23b36bf-3bd0-46c4-8c0f-15f2bc3eaa84.png)
![2023-02-19_13 16 38](https://user-images.githubusercontent.com/144762/219947423-51b15812-1df5-4f0e-b868-7d62f7c86744.png)

This make difficult to do a beautiful roof with 2 different angles
Thank you!

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.3 update
