### ISSUE TITLE
Automatic Doors Reacting to Windows

### ISSUE THREAD

**Issue by Jimjamss** [sketchmacaw/MacawsModsIssues#25]
When running automatic Doors the mod reacts with the windows causing them to open shut/at eye level.
Running on Forge 1.15.2 - 31.231 - mcw-doors-1.0.0-mc1.15.2

>Labels: 1.15.2, Macaw's Doors, Bug, Texture

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.0.0 update
