### ISSUE TITLE
ExampleMixin Log Spam

### ISSUE THREAD

**Issue by Qendolin** [sketchmacaw/MacawsModsIssues#251]
**Describe the bug**

When starting the game may of your mods print `This line is printed by the mod mixin!`. 
It is very annoying when reading though the log and it is also very useless. 
If you want to keep the log output at least include the mod id in the print statement.

**Mod name & Minecraft Version and Modloader**

I've seen the described behavior with the following mods, but I suspect it is present on all versions:
- mcw-bridges-2.0.5-mc1.19.2fabric
- mcw-doors-1.0.7fabric-mc1.19.2
- mcw-fences-1.0.6fabric-mc1.19.2
- mcw-lights-1.0.4fabric-mc1.19.2 // Fixed in the upcoming 1.0.5 update
- mcw-paintings-1.0.4fabric-mc1.19.2
- mcw-paths-1.0.2fabric-mc1.19.2
- mcw-roofs-2.2.1-mc1.19.2-fabric
- mcw-trapdoors-1.0.7fabric-mc1.19.2
- mcw-windows-2.1.0fabric-1.19.2

**To Reproduce**
1. Start Minecraft
2. Wait for the main menu
3. Check the log

**Comment by sketchmacaw** [comment]
Removed in all 1.19.3, will remove it in the older versions later too.
