### ISSUE TITLE
"Window" type lacking recipe "Pane" type having two recipes

### ISSUE THREAD

**Issue by Kadinumoto** [sketchmacaw/MacawsModsIssues#253]
**Describe the bug**
While using Polymorph to find conflicting recipes I found the following issues. Each of them conflicts when the one mentioned after them.

`mcwwindows:dark_prismarine_four_window, mcwwindows:dark_prismarine_window2`
`mcwwindows:blackstone_four_window, mcwwindows:blackstone_window2`
`mcwwindows:diorite_four_window, mcwwindows:diorite_window2`
`mcwwindows:granite_four_window, mcwwindows:granite_window2`
`mcwwindows:prismarine_four_window, mcwwindows:prismarine_window2`
`mcwwindows:andesite_four_window, mcwwindows:andesite_window2`
`mcwwindows:stone_four_window, mcwwindows:stone_window2`

**Macaw's Windows 2.1.1 - MC 1.16.5 - Forge 36.2.39**

**To Reproduce**
1a. Try to craft one of the mentioned Windows/
1b. See the recipe with JEI/NEI
1c. Use Polymorph and run `/polymorph conflicts`

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.2.0 Update
