### ISSUE TITLE
[1.19.2] Window and Roof hammer resets blocks next door

### ISSUE THREAD

**Issue by Water-Cat1** [sketchmacaw/MacawsModsIssues#255]
**Describe the bug**
Using a hammer to adjust a single block works fine. But if a block next to it is also wanting to be adjusted the first right click resets the first block and subsequent clicks adjust the new block.

**Mod name & Minecraft Version and Modloader**
Macaw's roofs
Macaw's windows
1.19.2 - Forge 43.1.57

**To Reproduce**
1. Place two roofs or windows next to each other
2. Right click one with the corresponding hammer
3. Right click the other with the corresponding hammer
4. First block resets

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.3 update, but it requires to click on it 2x
