### ISSUE TITLE
Several Mods Causing Slower Loading Times

### ISSUE THREAD

**Issue by LolJohn11** [sketchmacaw/MacawsModsIssues#259]
**Bug description**
Enabling Macaw's Furniture mod, as well as (to a lesser extent) Roofs and Doors mods increases the loading times noticeably.
Here's a comparison of average loading times with and without the mods mentioned:
- "Stock" - 76s
- Doors - 83s (+9%)
- Roofs - 80s (+5%)
- Furniture - 110s (**+45%**)
- All - 118s (**+55%**)

While some of the mods cause negligible load time increases (less than 10% for Doors and Roofs mods), the dramatic increase in loading times caused by installing the Furniture mod is more worrying.
Seeing how this issue is very similar to the one that was present in an earlier version of Macaw's Bridges (and has since been [solved](https://github.com/sketchmacaw/MacawsModsIssues/issues/242#issue-1456664333)), hopefully, this will make it easier to fix than trying to figure it out from scratch.

> **Mod name** - Macaw's Doors (1.0.7), Roofs (2.2.2) & Furniture (3.0.2)
> **Minecraft Version** - 1.19.2
> **Modloader** - Forge 43.2.0

**To Reproduce**
1. Launch Minecraft
2. Note how long the game loads
3. Install any\all of the mods mentioned above (Doors, Roofs, Furniture)
4. Launch Minecraft again
5. Note the increases in loading times

**"Latest" Logs**
_(all involving launching a game, reaching the main menu, and closing the game)_
- ["Stock" launch](https://mclo.gs/vn4MIXg) (without any of the mods mentioned above)
- [Doors](https://mclo.gs/JalxxAc)
- [Roofs](https://mclo.gs/IjwIn2p)
- [Furniture](https://mclo.gs/fwl1ICG)
- [All](https://mclo.gs/eQBCP7S) (with all of the mods mentioned above)

**Comment by sketchmacaw** [comment]
Furniture will be fixed with the next update which should come in February. Currently I have no ideas on how to lower the loading times for doors and roofs.

**Comment by LolJohn11** [comment]
Perfect, thanks!

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.1.0 update
