### ISSUE TITLE
Corner and Cap Desks Do Not Render Legs/Walls

### ISSUE THREAD

**Issue by TecmagDiams** [sketchmacaw/MacawsModsIssues#260]
**Describe the bug**
Certain pieces of desks do not render, but have colision boxes. I've specifically noticied it with corners and end pieces (please see screenshots). The top surface of the desks still render. This happens with no other mods installed.

**Mod name & Minecraft Version and Modloader**
- **Mod**: Macaw's Furniture
- **Minecraft Version**: 1.92.2
- **Forge Version**: 43.2.0 & 43.2.2

**To Reproduce**
1. Create any desk.
2. Place desk in L-shape OR place 2 desks next to eachother with one turned.
3. Observe missing pieces.

**Screenshots**
![image](https://user-images.githubusercontent.com/48166478/215552181-3683ff8f-6b10-4445-8c37-b7e59e1c121e.png)
![image](https://user-images.githubusercontent.com/48166478/215552208-0beccd2a-92cd-4502-9b72-2f94fb705c3c.png)

**Additional context**
Hit boxes still exist for targetting the block.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.1.0 update
