### ISSUE TITLE
Lower top and base roofs are broken

### ISSUE THREAD

**Issue by Sion66666** [sketchmacaw/MacawsModsIssues#261]
![2023-02-04_21 54 03](https://user-images.githubusercontent.com/37846709/216789152-dd1ca258-faba-4be1-9f40-1e50cd77d541.png)
As seen in the picture, I am unable to arrange the blocks as I would like. Their state changes depending on the state of the neighboring blocks. It literally looks like when I try to fix one block with a "roofing hammer", several neighboring blocks automatically change their state to incorrect. When I fix the neighbors and try to fix the first one again, those two neighbors change again to incorrect. And so on, again and again...

I've been struggling with this for a few hours now and it's starting to really piss me off. It's interesting that the "Steep" blocks don't behave this badly. In my opinion, a change would be useful:

- that when the state of the block is changed with a "roofing hammer", from that moment its state can be changed ONLY with a "roofing hammer".
- or add a configuration file that completely disables the automatic adjustment of blocks to each other. I seriously would rather set each block manually with a hammer than get angry because each block has its own life.
- or you could do it so that state changes made with the hammer do not trigger state changes in neighboring blocks. When I use the hammer, I want to change the state ONLY of THAT ONE BLOCK, not its neighbors...

**Comment by sketchmacaw** [comment]
Partially fixed in the upcoming 2.2.3 update for 1.19 and higher with using the Hammer. But for some reason it is still changing the neighboring for 1.18.2 and lower. Will let this open to see if I can fix it in the older version too.

**Comment by osirisgothra** [comment]
yeah i hope they do bc i ran into this in 1.18 and i really would have liked to use these but they were spacing out like the picture above

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.3.0 update
