### ISSUE TITLE
1.19.2 Incompatible

### ISSUE THREAD

**Issue by ereese99** [sketchmacaw/MacawsModsIssues#265]
The furniture mod on the curseforge site says 1.19.2 but in the Curseforge app it says it's incompatible: won't come up in searches and won't allow me to import it to my modpack. May you fix this?

**Comment by ereese99** [comment]
Note: I'm using Fabric

**Comment by ereese99** [comment]
Ohhhh okay, Thanks!

**Comment by sketchmacaw** [comment]
Fabric will come out soon don't worry :)
