### ISSUE TITLE
Breaking Multiblock Doors Crashes World

### ISSUE THREAD

**Issue by ConnorHibbs** [sketchmacaw/MacawsModsIssues#267]
Breaking parts of multiblock doors such as the garage door or portcullis causes the world to crash. Noticed single doors could be broken fine, and multiblock doors could be removed with TNT.

[multiblock_door_break.log](https://github.com/sketchmacaw/MacawsModsIssues/files/10751732/multiblock_door_break.log)

**Comment by Reegmeister** [comment]
I have the same situation, and it's only an issue with the most recent update. Rolling back one release, everything works as expected.

**Comment by sketchmacaw** [comment]
Will be fixed in the upcoming update, don't worry :)

**Comment by sketchmacaw** [comment]
Fixed in the 1.0.8b update for 1.16.5
