### ISSUE TITLE
MCW mods break BYG crafting recipes (crafting tables) when "too many" MCW mods are used. 

### ISSUE THREAD

**Issue by JalapenoGremlin** [sketchmacaw/MacawsModsIssues#268]
So I was trying to use all of the Macaw's Mods (bridges, doors, fences, furniture, lights, paintings, paths, roofs, trapdoors, windows), both with and without the BYG extensions, and noticed that the BYG crafting tables could not be created in survival..
(e.g. 4 cherry planks to create a cherry crafting table). 

If I enable each "base" mod with BYG enabled, I could craft the `byg:crafting_tables`, but at some point a subset of the MCW mods would break the crafting recipe and using BYG planks would create a `minecraft:crafting_table`. 

I did not try all $2^{10} = 1024$ possible permutations, but if I enable just bridges,doors,fences,furniture,lights,painting, paths I could craft the BYG crafting tables, but adding an 8th MCW mod would no longer be able to create the BYG crafting table variants.

There seems to be some subsets of MCW mods that cause the BYG  crafting recipes to revert back to the `minecraft:crafting_table ` recipes. 

My system:
* Minecraft 1.19.2
* Forge 43.2.4
* Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
* mcw-bridges-2.0.6-mc1.19.2forge.jar
* mcw-doors-1.0.8forge-mc1.19.2.jar
* mcw-fences-1.0.7-mc1.19.2forge.jar
* mcw-furniture-3.0.2-mc1.19.2.jar
* mcw-lights-1.0.5-mc1.19.2forge.jar
* mcw-paintings-1.0.4-mc1.19.2.jar
* mcw-paths-1.0.2forge-mc1.19.2.jar
* mcw-roofs-2.2.2-mc1.19.2forge.jar
* mcw-trapdoors-1.0.8-mc1.19.2forge.jar
* mcw-windows-2.1.1-mc1.19.2forge.jar

TO reproduce. 
1. Run Minecraft 1.19.2 Forge loader with each of the MCW mods one at a time
2. Create a new world in creative mode.
3. Add  4 `byg:cherry_planks` to your inventory
4. Go into survival mode
5. Create a Crafting table with the 4 BYG planks
6. Observe that the crafting table is the special BYG version
7. Now enable all the MCW mods and repeat steps 2 through 5 and observe that the crafting table is a vanilla minecraft:crafting_table

**Comment by Eatham532** [comment]
I am almost 100% sure that the macaws mods do not modify the crafting table. Have you tried this in a fresh world? Also, please note that the BYG versions of macaws mods are not made by Sketch Macaw.

**Comment by JalapenoGremlin** [comment]
So. Every attempt was in a "fresh world" (Step 2. Create a new instance. In this case I meant a new minecraft world. I will update the issue. 

I'm not certain what to say. I can create byg crafting tables until I enable enough of macaw's mods (*and none of the byg versions of macaws mods) and all of a sudden I can no longer create a byg crafting table.

**Comment by Eatham532** [comment]
My Game definitely breaks when I join a world with BYG crafting tables. And Yeh, I notice the bug. Let me find out which mod breaks it.

**Comment by Eatham532** [comment]
I have done more testing and I can agree that when using too many of MCW mods BYG breaks. Let me add it to the bug tracker. Sketch will know what to do.

**Comment by JalapenoGremlin** [comment]
> 

Thanks

**Comment by JalapenoGremlin** [comment]
> Let me add it to the bug tracker. Sketch will know what to do.

Thanks. I appreciated you looking into it.
It didn't make sense to me since, as you said, MCW mods don't have crafting table recipes nor does it use crafting tables as part of any of its recipes.

**Comment by sketchmacaw** [comment]
Every Macaw's mod except for Windows (in the works..) has been through major optimizations. 
Is this issue still happening with the most recent versions of the mcw mods?

**Comment by JalapenoGremlin** [comment]
It seems to be fixed now.
