### ISSUE TITLE
"v3.1.0 / mc1.19.4 - Fabric" doesn't seem to work when loaded into server

### ISSUE THREAD

**Issue by ygjkuma** [sketchmacaw/MacawsModsIssues#278]
I've been trying to get the mod to work on our 1.19.4 server but this file in particular doesn't let our server start.
Not sure what more info to provide since this issue has already been resolved without the mod. 

An employee of Apex Hosting told me that it lies within the mod file. If you need more specific info please let me know and I'll be happy to provide it.

**Comment by sketchmacaw** [comment]
Please provide the log & debug files so we can figure out what is happening.

**Comment by ygjkuma** [comment]
`16.03 20:17:33 [Multicraft] Starting server!
16.03 20:17:35 [Multicraft] Updating eula.txt file
16.03 20:17:35 [Server] INFO WARNING: Published ports are discarded when using host network mode
16.03 20:17:35 [Server] INFO 025ae66ed44d886b1e9fb4436d8db54add85499c1c737a92b8274960db097a85
16.03 20:17:37 [Server] INFO Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
16.03 20:17:38 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
16.03 20:17:38 [Server] INFO [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
16.03 20:17:38 [Server] INFO [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
16.03 20:17:38 [Server] main/INFO Loading Minecraft 1.19.4 with Fabric Loader 0.14.17
16.03 20:17:38 [Server] main/INFO Loading 42 mods:
16.03 20:17:38 [Server] INFO - fabric-api 0.75.3+1.19.4
16.03 20:17:38 [Server] INFO |-- fabric-api-base 0.4.23+9ff28bced8
16.03 20:17:38 [Server] INFO |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ed8
16.03 20:17:38 [Server] INFO |-- fabric-biome-api-v1 13.0.5+fe9afa9dd8
16.03 20:17:38 [Server] INFO |-- fabric-block-api-v1 1.0.5+e022e5d1d8
16.03 20:17:38 [Server] INFO |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674d8
16.03 20:17:38 [Server] INFO |-- fabric-client-tags-api-v1 1.0.14+1134c5b8d8
16.03 20:17:38 [Server] INFO |-- fabric-command-api-v1 1.2.25+f71b366fd8
16.03 20:17:38 [Server] INFO |-- fabric-command-api-v2 2.2.4+ae0966bad8
16.03 20:17:38 [Server] INFO |-- fabric-commands-v0 0.2.42+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-containers-v0 0.1.51+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-content-registries-v0 3.5.6+ae0966bad8
16.03 20:17:38 [Server] INFO |-- fabric-convention-tags-v1 1.3.0+6baaf971d8
16.03 20:17:38 [Server] INFO |-- fabric-crash-report-info-v1 0.2.14+aeb40ebed8
16.03 20:17:38 [Server] INFO |-- fabric-data-generation-api-v1 11.3.4+5da15ca1d8
16.03 20:17:38 [Server] INFO |-- fabric-dimensions-v1 2.1.44+7f87f8fad8
16.03 20:17:38 [Server] INFO |-- fabric-entity-events-v1 1.5.12+e45f7c65d8
16.03 20:17:38 [Server] INFO |-- fabric-events-interaction-v0 0.4.42+a1ccd7bfd8
16.03 20:17:38 [Server] INFO |-- fabric-events-lifecycle-v0 0.2.50+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bfd8
16.03 20:17:38 [Server] INFO |-- fabric-item-api-v1 2.1.15+ae0966bad8
16.03 20:17:38 [Server] INFO |-- fabric-item-group-api-v1 3.0.2+e45f7c65d8
16.03 20:17:38 [Server] INFO |-- fabric-key-binding-api-v1 1.0.32+c477957ed8
16.03 20:17:38 [Server] INFO |-- fabric-keybindings-v0 0.2.30+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1d8
16.03 20:17:38 [Server] INFO |-- fabric-loot-api-v2 1.1.24+75e98211d8
16.03 20:17:38 [Server] INFO |-- fabric-loot-tables-v1 1.1.28+9e7660c6d8
16.03 20:17:38 [Server] INFO |-- fabric-message-api-v1 5.1.0+1ee8be40d8
16.03 20:17:38 [Server] INFO |-- fabric-mining-level-api-v1 2.1.36+49abcf7ed8
16.03 20:17:38 [Server] INFO |-- fabric-models-v0 0.3.29+11ba9c3bd8
16.03 20:17:38 [Server] INFO |-- fabric-networking-api-v1 1.2.21+4e68ac5bd8
16.03 20:17:38 [Server] INFO |-- fabric-networking-v0 0.3.38+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-object-builder-api-v1 7.0.0+63b515f4d8
16.03 20:17:38 [Server] INFO |-- fabric-particles-v1 1.0.22+f1e4495bd8
16.03 20:17:38 [Server] INFO |-- fabric-recipe-api-v1 1.0.5+a1ccd7bfd8
16.03 20:17:38 [Server] INFO |-- fabric-registry-sync-v0 2.1.1+a383ab97d8
16.03 20:17:38 [Server] INFO |-- fabric-renderer-api-v1 2.2.4+81e8c576d8
16.03 20:17:38 [Server] INFO |-- fabric-renderer-indigo 1.1.0+81e8c576d8
16.03 20:17:38 [Server] INFO |-- fabric-renderer-registries-v1 3.2.36+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ed8
16.03 20:17:38 [Server] INFO |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bd8
16.03 20:17:38 [Server] INFO |-- fabric-rendering-v0 1.1.39+df3654b3d8
16.03 20:17:38 [Server] INFO |-- fabric-rendering-v1 2.0.2+ae0966bad8
16.03 20:17:38 [Server] INFO |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eed8
16.03 20:17:38 [Server] INFO |-- fabric-resource-loader-v0 0.10.9+711cde8ad8
16.03 20:17:38 [Server] INFO |-- fabric-screen-api-v1 1.0.44+8c25edb4d8
16.03 20:17:38 [Server] INFO |-- fabric-screen-handler-api-v1 1.3.17+5da15ca1d8
16.03 20:17:38 [Server] INFO |-- fabric-sound-api-v1 1.0.8+75e98211d8
16.03 20:17:38 [Server] INFO |-- fabric-transfer-api-v1 3.0.1+9003cbe9d8
16.03 20:17:38 [Server] INFO \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4d8
16.03 20:17:38 [Server] INFO - fabricloader 0.14.17
16.03 20:17:38 [Server] INFO - java 17
16.03 20:17:38 [Server] INFO - mcwfurnitures 3.1.0
16.03 20:17:38 [Server] INFO - minecraft 1.19.4
16.03 20:17:38 [Server] main/INFO SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/jar/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
16.03 20:17:38 [Server] main/INFO Compatibility level set to JAVA_16
16.03 20:17:38 [Server] main/INFO Compatibility level set to JAVA_17
16.03 20:17:47 [Server] main/ERROR Failed to start the minecraft server
16.03 20:17:47 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcwfurnitures'!
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5617
16.03 20:17:47 [Server] INFO at net.kikoz.mcwfurnitures.MacawsFurniture.onInitialize(MacawsFurniture.java:43) ~[mcw-furniture-3.1.0-mc1.19.4fabric.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO ... 7 more
16.03 20:17:47 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5617
16.03 20:17:47 [Server] INFO at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
16.03 20:17:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
16.03 20:17:47 [Server] INFO at net.kikoz.mcwfurnitures.MacawsFurniture.onInitialize(MacawsFurniture.java:43) ~[mcw-furniture-3.1.0-mc1.19.4fabric.jar:?]
16.03 20:17:47 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
16.03 20:17:47 [Server] INFO ... 7 more
16.03 20:17:48 [Multicraft] Server shut down (starting)
16.03 20:17:48 [Multicraft] Restarting crashed server in 300 seconds
16.03 20:17:48 [Multicraft] Server stopped`

**Comment by ygjkuma** [comment]
Sorry not entirely sure where I can find the debug files.

**Comment by sketchmacaw** [comment]
No worries, this is enough

**Comment by LeD0c4** [comment]
i'va the same issue with fabric 1.19.2 on server (fabric-server-mc.1.19.2-loader.0.14.14-launcher.0.11.2 + fabric api 0.76-1.19.2 / fabric api 0.75.1-1.19.2). i don't know if i need to write a new issue

**Comment by Dalethium** [comment]
I can also confirm this issue

**Comment by sketchmacaw** [comment]
Fixed in 3.1.1 update
