### ISSUE TITLE
No light from lanterns

### ISSUE THREAD

**Issue by Telezhka-the-First** [sketchmacaw/MacawsModsIssues#279]
**Describe the bug**
It appears that your lamps do give dynamic light, while lanterns don't. I guess you simply forgot to add some kind of tag on them.

**Macaw's lights and lamps 1.0.5 Forge 43.2.7 Minecraft 1.19.2**

**To Reproduce**
1. Take any lantern from the mod
2. Observe the darkness

**Comment by sketchmacaw** [comment]
Are you using shaders or another mod like dynamic light?

**Comment by Telezhka-the-First** [comment]
Tested with OptiFine embedded dynamic light system and MagnesiumRubidium. Seems like the problem is inside of exactly this mod.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming1.0.6 update
