### ISSUE TITLE
Server crash when using a hopper

### ISSUE THREAD

**Issue by HollishKid** [sketchmacaw/MacawsModsIssues#281]
**Describe the bug**
When using a Macaw Furniture inventory with a hopper, the server crashes.
The full crash report is [here](https://pastebin.com/ak8EuzkV).

**Mod name & Minecraft Version and Modloader**
Mod: Macaw's Furniture
Minecraft: 1.16.5
Modloader: Forge

**To Reproduce**
The bug description provides information about how to reproduce.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.2.0 update
