### ISSUE TITLE
Is normal that MCW Roofs consums 2GB of Ram? - 1.18.2 Forge

### ISSUE THREAD

**Issue by 5stigma** [sketchmacaw/MacawsModsIssues#283]
**Describe the bug**
What the title says

**Mod name & Minecraft Version and Modloader**

Forge 1.18.2 - 40.2.0
MCW Roofs last version 1.18.2

**To Reproduce**
1. Run the Game
2. Done

**Thanks!**
Thank for your attention.

**Comment by sketchmacaw** [comment]
Are you using the latest version of roofs for sure? In the earlier versions there was a bug causing this.

**Comment by 5stigma** [comment]
It seems that Roofs mod is not the one that consumes a lot, but its compatibility with BYG.

**Comment by sketchmacaw** [comment]
Do you have the  BYG addon for roofs?

**Comment by 5stigma** [comment]
Yes, but I removed it, I will try to test it and I will send a picture.

**Comment by sketchmacaw** [comment]
Yeah, that is a separate addon which we aren't supporting. To solve the issue they would need to just update the blockstates files and the lags should be gone.

**Comment by 5stigma** [comment]
Thanks, I will close the case.
