### ISSUE TITLE
Windows no longer inteacting with walls

### ISSUE THREAD

**Issue by iylanna** [sketchmacaw/MacawsModsIssues#284]
**Describe the bug**
I've run into an issue that some of Every Compact/Macaw's windows no longer merge with walls after I updated Vault Hunters. It looks like it's the other mods' woods used in the frame. I've tested with vanilla walls as well as modded. 

**Mod name & Minecraft Version and Modloader**
Vault Hunters 3rd edition, Update 8.0.3. Minecraft 1.18.2, Forge 40.1.93 (I updated from VH 4 to 8, sorry I cant narrow it down more than that) 

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a window pane base (any) and make windows (tested with Ecologics Walnut and Quark Cherry). It does work with Vanilla Oak. 
2. Place down the pane in line with any wall. Tested with vanilla cobble as well as create calcite. 

**Screenshots**
![Artboard 1](https://user-images.githubusercontent.com/118386068/229370168-518f07a0-8e92-461b-a6ca-02893e81356b.png)

**Additional context**

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.2.0 Update
