### ISSUE TITLE
1.16.5 Furniture - [Crash]: Exception in server tick loop with the "Spoiled" mod installed.

### ISSUE THREAD

**Issue by GermanPlasma** [sketchmacaw/MacawsModsIssues#285]
**Describe the bug**
With the mod "Spoiled" installed, the game will crash automatically after a short period of time when placing furniture. I did make another bug report on the spoiled github, but it seems unsolvable on their side. It can be found [here](https://github.com/Mrbysco/Spoiled/issues/33). In my case, simply placing the storages and destroying them can cause the crash. It won't happen immediately, only after 30 seconds or so. The storages can be entirely empty, the crash will still happen regardless.

**Mod name & Minecraft Version and Modloader**
Minecraft 1.16.5
Macaw's Furniture v3.1.0
Mrbysco's Spoiled mod 1.16.5-1.5.0

**To Reproduce**
1. Place a few storage items from the furniture mod with the mod Spoiled installed, in survival mode, I assume.
2. wait 30 seconds to see if something happens
3. destroy the furniture
4. wait another 30 seconds to see if something happens, it should be crashing by now or very shortly afterwards.

**Additional context**
I attached a crash log.
[crash-2023-04-03_16.09.34-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/11142576/crash-2023-04-03_16.09.34-server.txt)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.2.0 update
