### ISSUE TITLE
[1.16.5] Right-clicking Furniture Storage blocks instead places block in hand.

### ISSUE THREAD

**Issue by nexitem** [sketchmacaw/MacawsModsIssues#287]
Playing Vahelsia 3 Modpack,

When rightclicking with a block and sometimes even weapons/tools on any furniture it might instead place the block or just don't open the box. Only works with nothing in your hand. Strangely enough this issue can get fixed by putting something in the off-hand slot and out again (so there is nothing in your off-hand).

**Macaw's Furniture & 1.16.5 and Forge 36.2.35 - Vahelsia 3 Modpack**

**To Reproduce**
1. Try to use furniture storage with block in hand, or off-hand item.
2. Will most likely place a block instead.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.2.0 update
