### ISSUE TITLE
Portcullis and Garage door ignoring redstone

### ISSUE THREAD

**Issue by Ganpan14O** [sketchmacaw/MacawsModsIssues#289]
The Portcullises and Garage doors don't seem to be openable or closable by redstone, only manual activation works

mcw-doors-1.0.9forge-mc1.18.2
Forge 1.18.2 40.2.1

1. Get any portcullis or garage door type, as well as a lever
2. Place them both next to each other
3. Flip the lever

![image](https://user-images.githubusercontent.com/85914881/234143306-1c4c5716-8a84-4a59-a548-f7aa9059f317.png)
![image](https://user-images.githubusercontent.com/85914881/234143322-0d68c96c-6257-4528-8d0e-3222e21aa262.png)

Mod is also being used in a small private modpack, which I can send if the issue doesn't occur in your testing.

**Comment by sketchmacaw** [comment]
Added redstone compatibility in the new upcoming 1.1.0 Update
