### ISSUE TITLE
Warped Ranch Trapdoor Shows Acacia Top

### ISSUE THREAD

**Issue by bcrotty** [sketchmacaw/MacawsModsIssues#290]
**Describe the bug**
The Warped Ranch Trapdoor looks like the Acacia Ranch Trapdoor from the top.

**Mod name & Minecraft Version and Modloader**
mcw-trapdoors-1.0.9-mc1.19.2forge

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Place Warped Ranch Trapdoor
2. Look at top
3. Weep in despair

**Screenshots**
![image](https://user-images.githubusercontent.com/6155964/235562702-2a5e51e4-a1e0-4cab-a5ba-b859a1deca99.png)

**Additional context**
models\block\ranch\warped_ranch_trapdoor_top.json has acacia log as the textures.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.1.0 update
