### ISSUE TITLE
[1.19.2] Doors and Trapdoors have bugged redstone powered state on a server

### ISSUE THREAD

**Issue by BhavyaSingh2611** [sketchmacaw/MacawsModsIssues#291]
**Describe the bug**
On powering the Every Compat block of Macaw's doors and trapdoors the redstone state is bugged, which I believe is macaw's issue since the compat is basically importing the block class and casting it to create new items

**Mod name & Minecraft Version and Modloader**
Macaw's Doors (v1.0.8)
Macaw's Trapdoors (v1.0.9)
Fabric API (v0.76.0+1.19.2)
Fabric Loader 0.14.18

**To Reproduce**
1. Join a server with macaw's mod and everycompat, grab any door or trapdoor from either of the mod.
2. Place them and power it using redstone, the door/trapdoor would update its hitbox but its model/render would stay the same causing weird collision when you walk forward.

**Additional context**
I have tried individual modules of EveryCompat to make sure its not everycompat that is causing the issue its the block being imported that is bugged. Which I find extremely odd considering in the Macaw's door repo it extends the DoorBlock class that should make the doors work as vanilla doors but for some reason glitch out

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Interesting, trapdoors are being registered just with the default vanila trapdoor class

**Comment by sketchmacaw** [comment]
It just doesn't makes any sense since the base mcw trapdoors and doors use vanilla classes not their own
