### ISSUE TITLE
Windows: No recipe for Andesite Windows (and some others)

### ISSUE THREAD

**Issue by VinceKezel** [sketchmacaw/MacawsModsIssues#292]
**Describe the bug**
The recipe for a few of the plain windows (not pane type) seem to be missing... and maybe other recipes are overlapping instead. See screenshot.

**Mod name & Minecraft Version and Modloader**
Macaw's Windows 2.1.2
Minecraft 1.19.2
Fabric 0.14.19

**To Reproduce**
1. Put 8 window bases around a andesite on crafting table. No output appears. Andesite Window should be the output.
2. Andesite Window appears in creative and JEI. There's no receipe shown from JEI.
3. See screenshot for how another window is not produced properly. JEI sows an overlapping recipe for the Andesite Pande window
![Capture05142023](https://github.com/sketchmacaw/MacawsModsIssues/assets/49579475/9685e55a-1fc0-4168-bb88-14325fc751c5)

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.2.0 Update
