### ISSUE TITLE
Spruce Bark Glass Door glitch

### ISSUE THREAD

**Issue by blueberry-bytes** [sketchmacaw/MacawsModsIssues#296]
One part of the glass is rotated 180 degrees. Lower left part. I use HD textures but on default ones it's visible too, just less.
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/5322956/06b22a18-604d-491c-900a-e9b85e965231)

And less annoying thing, on the upper right side the pointed line is thinner than all the others (my guess is lower left is also thin). If you know why, it would be awesome, but if not, it's not a big deal.

**Comment by blueberry-bytes** [comment]
I've fixed the first one, you can check the file.
[bark_glass_door_bot.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/11779188/bark_glass_door_bot.zip)
I don't know what to do with the second part, maybe you'll be able to.

**Comment by sketchmacaw** [comment]
Thanks! Will incorporate it in the next update with the 1.20 port too. Gonna figure out the second part.

**Comment by sketchmacaw** [comment]
Can you please tell me the name of the resourcepack you are using ? I can't really find a good pack with glass textures which are like here

**Comment by blueberry-bytes** [comment]
Of course:
https://legendaryrttextures.com
The site sometimes doesn't work.

**Comment by sketchmacaw** [comment]
Fixed in the new upcoming 1.1.0 Update
