### ISSUE TITLE
[Macaw's Furniture] Can't load game due to java error

### ISSUE THREAD

**Issue by gobinator98** [sketchmacaw/MacawsModsIssues#297]
**Describe the bug**

**Macaw's Furniture, MC 1.19.4, Forge 45.1.0**

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Open Launcher
2. Select Forge 45.1.0 profile
3. Open the game
4. The game shows a java error.

**Screenshots**

**Additional context**

**Thanks!**
Thank you for helping me by reporting issues c:

Log:
[latest.log](https://github.com/sketchmacaw/MacawsModsIssues/files/11742377/latest.log)

Screenshot of Error:
![Screenshot (156)](https://github.com/sketchmacaw/MacawsModsIssues/assets/136560862/80666254-1ea2-4cd4-9774-beec4059d8e6)

**Comment by gobinator98** [comment]
Even loading this mod by itself, it still throws the same exact error.

**Comment by sketchmacaw** [comment]
It is not yet updated for 1.19.4

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.2.0 update for 1.20+
