### ISSUE TITLE
1.20.1 Update request

### ISSUE THREAD

**Issue by Zorro8183** [sketchmacaw/MacawsModsIssues#300]
can you update Macaw's doors and trapdoors to 1.20.1 please?

**Comment by sketchmacaw** [comment]
Yes, why wouldn't we update it ? Trapdoors should get released today/tomorrow and we are still working on the new door textures (cherry).

**Comment by sketchmacaw** [comment]
Doors 1.20 / 1.20.1 will be out today, closing this
