### ISSUE TITLE
Pushing curtain with piston crashes client

### ISSUE THREAD

**Issue by Probably-Idiot** [sketchmacaw/MacawsModsIssues#302]
**Describe the bug**
When pushing a curtain into another curtain on a modded, multiplayer server, the client crashes. Here's a video: https://imgur.com/a/AM47OBY

**Mod name & Minecraft Version and Modloader**
Minecraft 1.19.2, Fabric, Macaw's Window Additions

**To Reproduce**
1. Place a curtain on a wall
2. Place another curtain perpendicular to it
3. Push the second curtain with a piston

**Additional context**
Ran on a multiplayer server with several other mods.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.2.0 Update
