### ISSUE TITLE
mcaw fences and other mcaw mods causes rendering issues with create mod moving builds 

### ISSUE THREAD

**Issue by DeadmanTheGod** [sketchmacaw/MacawsModsIssues#306]
**Mod name & Minecraft Version and Modloader**
mcw-bridges-2.0.6-mc1.19.2forge.jar
mcw-doors-1.0.9forge-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-furniture-3.1.0-mc1.19.2.jar
mcw-lights-1.0.6-mc1.19.2forge.jar
mcw-paths-1.0.3forge-mc1.19.2.jar
mcw-roofs-2.2.4-mc1.19.2forge.jar
mcw-trapdoors-1.1.1-mc1.19.2forge.jar
mcw-windows-2.1.1-mc1.19.2forge.jar
create-1.19.2-0.5.1.c.jar
 Forge 1.19.2  43.2.14

**To Reproduce**
1. Place down a sticky mechanical piston, underneath that a piston extension pole  and a creative motor to the side
2. watch the piston extend 
3. This is the issue : see the piston go invisible after it finishes moving. does this with a mechanical bearing too sometimes it add blocks  

**Screenshots**
![2023-07-11_09 59 21](https://github.com/sketchmacaw/MacawsModsIssues/assets/116610696/42c813f5-aab0-489d-85f0-3cdded3ed196)
![2023-07-11_09 59 24](https://github.com/sketchmacaw/MacawsModsIssues/assets/116610696/6c3d3c22-cdcc-4017-9282-b3831fbc9a77)
![2023-07-11_10 54 41](https://github.com/sketchmacaw/MacawsModsIssues/assets/116610696/be14efb3-e4e0-4214-bbab-7b5d704a037c)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by kkrabfir** [comment]
I'm seeing this issue in the FTB One pack as well. I went through and added mods a few at a time and narrowed it down to the Macaw's mods. I'm seeing several rendering problems across different mods, including the Macaw's doors desyncing and blocking players from moving through when they appear to be open. Other examples are the RFTools builder preview not showing without rezoning and cc-tweaked turtles creating ghosts of themselves and blocks they break (see attached screenshot). 
![javaw_QCeq616Nzn](https://github.com/sketchmacaw/MacawsModsIssues/assets/52703225/2d651907-5db2-4bf7-bacd-a31f551a3741)
![javaw_sg4XmAtn3v](https://github.com/sketchmacaw/MacawsModsIssues/assets/52703225/3c26681f-53e3-4df4-b55a-c9fb619605a6)

**Comment by sketchmacaw** [comment]
Probably resolved, [pluto mod lagged the server](https://discord.com/channels/645360921673465857/1130318030023442462/1145733497252753549)
