### ISSUE TITLE
[Macaw's Bridges] Pliers not showing up in creative inventory

### ISSUE THREAD

**Issue by vinnyg0621** [sketchmacaw/MacawsModsIssues#307]
**Describe the bug**
when I opened my inventory in creative mode, I could not find the pliers. the only way I could get it is through commands

**Mod name & Minecraft Version and Modloader**
Bridges, MC 1.19.2, forge

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Open inventory
2. search for "pliers"
3. I couldn't find them at all (except through commands)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by Sedwert** [comment]
Can confirm, in fact they don't show up in survival for me either

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.1.0b update
