### ISSUE TITLE
Rubidium is not working

### ISSUE THREAD

**Issue by xXshadowWolf** [sketchmacaw/MacawsModsIssues#309]
[crash-2023-07-19_17.59.54-client.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/12100555/crash-2023-07-19_17.59.54-client.txt)
and i had to disable it for my mods to work

**Comment by Nycto97** [comment]
In general, I would try [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) instead since it is more frequently updated and is more compatible with other mods.
