### ISSUE TITLE
Bridge render issues

### ISSUE THREAD

**Issue by ben-mkiv** [sketchmacaw/MacawsModsIssues#31]
looks like face orientation is sometimes messed up for the side part of the bridge
![](https://i.imgur.com/jIdNQTt.png)
![](https://i.imgur.com/E0Iv5oE.png)

mcw-bridges-1.0.4
Minecraft 1.16.1

Client without Optifine

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.6 Update.
