### ISSUE TITLE
Paths: make stone paths stepping sounds like walking on the stone

### ISSUE THREAD

**Issue by vgrynch** [sketchmacaw/MacawsModsIssues#312]
Please, make stone paths stepping sounds like walking on the stone.
I understand that I can replace dirt with stone blocks under the paths to have the desired effect. However, for lengthy paths, this is a lot of work in survival mode to do such a replacement. Would be good if steps sounded properly to path material.

**Comment by sketchmacaw** [comment]
Implemented this suggestion since mojang added in 1.20+ the tag combination_step_sound_blocks
So this suggestion has been added to all 1.20 and higher versions
