### ISSUE TITLE
[Furniture] Z-Fighting handles

### ISSUE THREAD

**Issue by IdrisQe** [sketchmacaw/MacawsModsIssues#315]
**Describe the bug**
The handles on drawers and wardrobes in Macaw's Furniture appear to flicker/z-fight when moving, specifically the top, sides, and bottom of the handles, but not the front.

**Mod name & Minecraft Version and Modloader**
Macaw's Furniture 3.1.1, Fabric 0.14.21

**Screenshots**
Recording the screen didn't work for some reason so I could only get a still-frame but the Z-Fighting is still evident
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/40530630/44dae44b-0b70-44c5-a004-05539073f882)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 3.2.0 update
