### ISSUE TITLE
[Windows] Mobs try to pathfind through windows

### ISSUE THREAD

**Issue by IdrisQe** [sketchmacaw/MacawsModsIssues#319]
**Describe the bug**

**Mod name & Minecraft Version and Modloader**
Macaw's Windows 2.1.2, Fabric 0.14.21

**To Reproduce**
1. Make walls and place windows in the walls
2. Put beehives outside, and maybe some flowers inside, or vise-versa
3. Bees will start to either get stuck trying to get inside through the windows, or get inside another way and then get stuck trying to get outside through the windows. They seem to believe the windows are empty space and try to path through them even if another path is available. This doesn't happen with any other blocks as far as I can tell so I'm not sure why it's happening.

**Screenshots**
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/40530630/4145303c-cbd1-4467-a47b-03d610a630f3)

**Comment by sketchmacaw** [comment]
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/60577275/ee4cce66-92b4-4fea-90ca-120fd924ecea)
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/60577275/c10fb0d5-2833-49a5-9d4c-0d0c16c9c0bf)
It looks like this is a vanilla bug

**Comment by sketchmacaw** [comment]
I just tested it and it took them a minute or two, but they flew out.

**Comment by Aceplante2** [comment]
Bees have always done that

**Comment by IdrisQe** [comment]
As several people have pointed out, this is apparently a Vanilla issue, which is weird since I wasn't encountering it with other blocks, but that's RNG for you. I never really did much with bees until then, so I never saw the problem.

I should have closed this issue a while back, thanks for the ping reminding me to do so.

_...Would be nice if Mojang could fix this though... As well as other issues like bees flying off and disappearing into unloaded chunks and abandoning their hives..._
