### ISSUE TITLE
[Macaw's Roofs] Rendering issues with outer corner roofs

### ISSUE THREAD

**Issue by AlisonHuang777** [sketchmacaw/MacawsModsIssues#322]
**Describe the bug**
When any block with complete upper surface is placed under any type of outer corner roof, the bottom of the roof become transparent, leaving annoying see-through gaps.

**Versions**
- Minecraft: 1.20.1
- Forge: 47.1.44
- ![screenshot](https://github.com/sketchmacaw/MacawsModsIssues/assets/51637996/1ce49621-83ee-4163-8dce-0e2971e7b692)

**Reproduce Procedure**
1. ![2023-08-25_17 41 18](https://github.com/sketchmacaw/MacawsModsIssues/assets/51637996/76082797-af8b-471a-9d7e-8cb96a78c0d5)
2. ![2023-08-25_17 41 22](https://github.com/sketchmacaw/MacawsModsIssues/assets/51637996/6164403c-888e-47fc-86f2-f6140d34eac7)

**Comment by AlisonHuang777** [comment]
Extra screenshot:
![2023-09-10_20 07 11](https://github.com/sketchmacaw/MacawsModsIssues/assets/51637996/415fb4f1-5d50-4008-a3de-1b863af513f8)

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.3.0 update
