### ISSUE TITLE
Can't have paper lamps turned on and surrounded by blocks - will always be OFF

### ISSUE THREAD

**Issue by DragonPlushie** [sketchmacaw/MacawsModsIssues#324]
Whenever a block is paced next to a paper lamp, it turns off, same if I break a block. This means that no combination of breaking blocks, placing blocks and Turing on the lamp will allow it to stay ON while fully surrounded by stained glass for example.

Macaws lights and lamps most recent version 1.20.1.1.0.6

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.1.0 update
