### ISSUE TITLE
Macaw's Furniture Cabinet Door Recipe not producing crafted item

### ISSUE THREAD

**Issue by LegXacy** [sketchmacaw/MacawsModsIssues#325]
![2023-09-13_23 50 13](https://github.com/sketchmacaw/MacawsModsIssues/assets/98788980/7babc0e5-3dd1-4435-b01c-698115c1ae7b)

![2023-09-13_23 47 35](https://github.com/sketchmacaw/MacawsModsIssues/assets/98788980/4bf4663b-cb61-4188-a171-d76f97556597)

The recipe isn't working outside of JEI, I'm unaware as to any mod conflicts that may cause this but I thought it would be worth posting here.

Macaw's Furniture 3.2.0

**Comment by sketchmacaw** [comment]
Fabric?

**Comment by LegXacy** [comment]
Yes, sorry for the late response! this is Fabric 0.14.22 on Minecraft 1.20.1

**Comment by sketchmacaw** [comment]
It is fixed in the [3.2.0b](https://legacy.curseforge.com/minecraft/mc-mods/macaws-furniture/files/4738221) update :)
