### ISSUE TITLE
[lamps&lights][1.20.1, forge] The sound of glowstone and sea lantern is mismatched

### ISSUE THREAD

**Issue by LiAuTraver** [sketchmacaw/MacawsModsIssues#326]
the sound of walking,placing,breaking on those slab are pretty strange, and just sound like nether logs.
Hope things get better!

**Comment by LandofHeros2234** [comment]
This also affects 1.19.2, and the Shroomlight slabs use the glass sounds

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.1.0 update
