### ISSUE TITLE
Inconsistencies in roof textures/UVs

### ISSUE THREAD

**Issue by Le6barbare** [sketchmacaw/MacawsModsIssues#327]
**Describe the bug**
The textures on all the roof models have inconsistencies, clearly visible on bamboo block roofs:
- Unaligned with adjacent parts (of the model or with other roof blocks)
- Miscut/not rounded up size of UV (leaving small lines without a full pixel width)
- Unintuitive for texture makers, because the UV placement of main faces are not following a clear pattern
 (some are rotated/mirrored, some UVs seems to be selected randomly inside the texture, or repetitions of the same part of the texture (mostly the top left one))

**Mod name & Minecraft Version and Modloader**
- MC 1.20.1
- Forge 47.1.47
- MCW Roofs 2.2.4b

**To Reproduce**
1. Open a world or make a new one
2. Make an S shape with a roof block to see all the variants (normal, inner, outer, ...)
3. Repeat for each roof block types
4. Examine the various blocks in detail

**Screenshots**
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/31876aac-eea2-4228-b25d-1ad01b9de6f0)
![2023-10-01_10 45 51](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/43dad036-cb39-4ca6-b334-29f09036e464)
![2023-10-01_10 48 32](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/ea3233c4-30e3-4ddd-8e66-ad527de1ff7d)
![2023-10-01_10 48 51](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/2027c317-64c5-49e6-9ea5-4776b7a2fd59)
![2023-10-01_10 49 42](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/9a9e84d1-6a51-4462-8f88-394b4dd9ec7e)
![2023-10-01_10 49 59](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/c6464275-af85-4157-8625-004a7ec4d994)
![2023-10-01_10 50 06](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/d76c3e86-7307-4614-a30f-b63d51f15938)
![2023-10-01_10 50 14](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/4e40dbec-b1d8-4319-8875-243b0f48f760)
![2023-10-01_10 50 25](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/5e6137ce-bb68-488b-ae0a-ccee995fa595)
![2023-10-01_10 50 35](https://github.com/sketchmacaw/MacawsModsIssues/assets/3297646/5a31171b-d43a-41c9-9033-395725146777)

**Additional context**
I'm making a compatibility datapack to use the thatch block from [You've Goat to be Kidding Me!](https://www.curseforge.com/minecraft/mc-mods/goated) in recipes and texture of your thatch roof
and found those inconsistencies while trying to make a version of the roof models who doesn't rotate block textures
(Because this mod's thatch block texture make sense only top-down/vertically) 

This issue could be linked to Issue #85 

**Thanks!**

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.3.0 update
