### ISSUE TITLE
Macaws Windows opening then immediately closing

### ISSUE THREAD

**Issue by RogerMcPoggers** [sketchmacaw/MacawsModsIssues#328]
everytime i open the windows they instantly close, seems like i can get it to work if i shift click one window but when its higher than one block it seems like i cant have them open. 

thank you so much for bringing back openable windows again! im very excited to use them again and cant wait to see more updates, thanks!!

mcw-windows-2.2.0-mc1.19.2forge.jar / Minecraft 19.2

**Comment by sketchmacaw** [comment]
Do you have any other mods installed ?

**Comment by sketchmacaw** [comment]
Should be Fixed in the upcoming 2.2.1 Update
