### ISSUE TITLE
No base window recipe in 1.20.1 + Forge w. JEI, unable to craft any windows as a result.

### ISSUE THREAD

**Issue by SunGod** [sketchmacaw/MacawsModsIssues#329]
**Describe the bug**
In 1.20.1 + Forge, all the recipes require a base widow block, but no recipe exists for this block, making it impossible to craft any windows. Have Just Enough Items (JEI) installed.

**Mod name & Minecraft Version and Modloader**
1.20.1 Forge version (mcw-windows-2.2.0-mc1.20.1forge.jar)

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Go to any window recipe in JEI. Select it. Will require a base window object.
2. Search for "window base" object in recipes, doesn't exist.

**Screenshots**
![Screenshot 2023-10-11 075136](https://github.com/sketchmacaw/MacawsModsIssues/assets/2029061/7b7f2958-4ca3-42dd-a192-64cdcfe566c6)
![Screenshot 2023-10-11 080434](https://github.com/sketchmacaw/MacawsModsIssues/assets/2029061/7f71c57c-cc6a-4a2c-9105-f3a9536c8163)

**Additional context**
Have JEI installed. Have not tried it without JEI.

**Thanks!**
You are welcome. Thanks for the mod! :)

**Comment by Miszelka** [comment]
The recipe for the base window does not work in general, I have a few other mods installed, don't have JEI and also can't craft them even if the recipe is filled manually.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.2.1 Update
