### ISSUE TITLE
Block Updates turn lights and lamps on

### ISSUE THREAD

**Issue by KittyKittyKitKat** [sketchmacaw/MacawsModsIssues#330]
Whenever a lamp or ceiling light receives a block update, the light is turned on.

**Mod name & Minecraft Version and Modloader**
Macaw's Lights and Lamps v1.0.6
Fabric 0.14.22 running on Minecraft 1.19.2

**To Reproduce**
1. Go to newly generated world.
2. Place down any lamp or ceiling light and turn it off
3. Place any block besides the lamp, or otherwise cause a block update.
4. The light turns back on without the player having done so.

[macaw_bug_demo.webm](https://github.com/sketchmacaw/MacawsModsIssues/assets/57276022/b007d0f2-8bf7-49f2-a190-fe3770cf4014)

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.1.0 update
