### ISSUE TITLE
Unknown block type for 12 paths

### ISSUE THREAD

**Issue by moderninity** [sketchmacaw/MacawsModsIssues#331]
**Describe the bug**
receiving "Unknown block type" in logs for all the stone and mossy stone paving types. Log then lists all valid block types. 12 times. 

**Mod name & Minecraft Version and Modloader**
Fabric 1.20.1 
fabric-api-0.90.0+1.20.1.jar (
Macaw's paths and pavings 
mcw-paths-1.0.3fabric-mc1.20.1.jar

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Have Paths and Pavings
2. Start World

**Screenshots**
![help](https://github.com/sketchmacaw/MacawsModsIssues/assets/16236505/f982989f-21d8-4b73-b208-c0633ccb304f)

**Additional context**

https://mclo.gs/tjXJPCF

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Should be fixed in the latest 1.0.4
