### ISSUE TITLE
1.20.1 BUG when placing down blocks, they change their type into a different one

### ISSUE THREAD

**Issue by erdeilaci3** [sketchmacaw/MacawsModsIssues#333]
**Describe the bug**
When I place down a block added by any of the Macaw's mods, it changes variations, however it only happens while I'm on a server, and never in singleplayer.

**All of the Macaw's mods except the roof mod, along with all it's BOP compatibility mods, & 1.20.1 and Forge**

**I'm not sure which mod is causing it. I have like 48-49 mods or so...**

**To Reproduce**
1. Start a multiplayer server
2. Place down any block from any of the Macaw's mods 
3. The issue is that every block changes into a random variant when placed, however can be used like how they are. For example a chair looks like snow or something similar, however I can still sit on it by right clicking. This is the same for any other block that can store items.

**Screenshots**
**BEFORE:**
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/139857254/5a424280-bcbe-49e6-8122-fa3ccedf6800)

![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/139857254/29c71e82-e883-48f6-bae2-f94e2699108e)

**AFTER:**
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/139857254/e6d94620-bc32-4545-86a7-995998e64781)

 ![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/139857254/399f1ea5-b426-4533-8ff7-3d158e5ec1d7)

As you can see, this happens when I place it down. When I place down a block near it, like updating it, it reverts to the texture it's supposed to be in for like one second and then reverts to it's glitched form. I have tested other blocks from other mods like from the Trapdoors mod, and the result is the same, but it doesn't change into this texture, it changes into a completely different one.

As I have mentioned earlier, I can still use these blocks. I mean like sitting on them, but I'm pretty sure I have explained it not so badly. 

![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/139857254/277468b1-c32f-4307-933f-44db2852ce13)

**Additional context**
I tried to disable Rubidium, along with Canary, both on client and on server. However that didn't quite work out. 
My server-side modlist is: 
JEI; JourneyMap; Traveler's Backpack; Iron Chests; GraveStone Mod; BOP with TerraBlender; Croptopia; Citadel; Alex's Mobs; CreativeCore; PlayerRevive; Carry On; WTHIT with bad packets; Rubidium and all it's extras; HT's Treechop; Farmer's Delight; AppleSkin; Easy Anvils, with Puzzles Lib; Serene Seasons with it's fix; Pufferfish's Skills; Somnia Awoken, with KoreMods. These are all the server-side mods I had on. 

My client-side mods are: 
Not Enough Animations; Better Third Person; AmbientSounds 5.

(Also apologies for my english. It isn't my first language, if I need to explain in greater detail I will. TY.)

**Comment by sketchmacaw** [comment]
Try using this mod, and tell me if it helps https://www.curseforge.com/minecraft/mc-mods/connectivity

**Comment by erdeilaci3** [comment]
> Try using this mod, and tell me if it helps https://www.curseforge.com/minecraft/mc-mods/connectivity

TY for replying. I'm gonna try and tell you if it helped.

**Comment by erdeilaci3** [comment]
> Try using this mod, and tell me if it helps https://www.curseforge.com/minecraft/mc-mods/connectivity

Hey, so It didn't quite work out. Got any ideas? Perhaps I need to create a new world?

**Comment by sketchmacaw** [comment]
If the server world had different mods on the world before, and now some changed it could mess up the block id. Try to make a new world and backup this one. I'm going to see what I can find about this.

**Comment by sketchmacaw** [comment]
Or just check if all of yours mods are the same as on the server

**Comment by erdeilaci3** [comment]
Ok, thank you

**Comment by erdeilaci3** [comment]
> If the server world had different mods on the world before, and now some changed it could mess up the block id. Try to make a new world and backup this one. I'm going to see what I can find about this.

Oh my god this works, but is there any way I could save my other world? My friend and I have spent quite some time, and It would be a pain to try to do it all over again...

**Comment by sketchmacaw** [comment]
If you have recently removed a mod from the old world, you could try to return it.

**Comment by erdeilaci3** [comment]
> If you have recently removed a mod from the old world, you could try to return it.

Well, I only removed MrCrayFish furniture mod. I'll check if that works, ty for your help.

**Comment by erdeilaci3** [comment]
man... it didnt't work, which sucks. either way, thanks for your help man. i guess i'll just copy the seed of a new world, go to our base's coordinates and rebuild our base. ty tho. i guess i got what i asked for and ty for that, so ill guess ill close the issue. ty again

**Comment by sketchmacaw** [comment]
I'm sorry we couldn't help you with the old world :(

**Comment by erdeilaci3** [comment]
np i love you and your mods man. ty for being so helpful :) gn or gm or whatever time it is for you
