### ISSUE TITLE
Mcw Funiture carbinet door not craftable

### ISSUE THREAD

**Issue by Ultimategamingwaffel** [sketchmacaw/MacawsModsIssues#335]
Hello, I would like to report that with the mod Mcw Funiture you can not craft on the server nor in a single player world the Carbinet doors. What am I supposed to do? Because in version 1.19.4 it still worked.

**Comment by sketchmacaw** [comment]
Hi please, on which MC version are you currently on?

**Comment by sketchmacaw** [comment]
Will be fixed in the upcoming 3.2.2 Furnite update, thanks for reporting

**Comment by Ultimategamingwaffel** [comment]
> Hi please, on which MC version are you currently on?

It's the 1.20.1 but it's done, jei has the old rafting recipe displayed, but it has a box in the middle by now
So that's it. 😅

**Comment by sketchmacaw** [comment]
I actually found out that all of the 1.20+ Furniture versions in forge don't have the Cabinet door in the creative tabs so that issue will be fixed :D

**Comment by Ultimategamingwaffel** [comment]
> I actually found out that all of the 1.20+ Furniture versions in forge don't have the Cabinet door in the creative tabs so that issue will be fixed :D

I'm playing on fabric and there it only shows up wrong with Jei. A
If it's known anyway, I'll update it as soon as the new version is out.
