### ISSUE TITLE
Two-wide bridges don't connect to stairs

### ISSUE THREAD

**Issue by nightpool** [sketchmacaw/MacawsModsIssues#336]
**Describe the bug**
When building 2-wide bridges that alternate between stairs and bridge pieces, the bridge pieces automatically connect to each other, ignoring the stairs. This makes it impossible to traverse the bridge

**Mod name & Minecraft Version and Modloader**

Macaw's Bridges, Fabric, Minecraft 1.20.1

**To Reproduce**
1. Place two bridge stairs
2. Moving up and along 1 block, place two bridges
3. place two more bridge stairs
4. See the bridge pieces are pointing at each other, not the stairs, creating an impassible barrier

**Screenshots**

![2023-11-22_14 55 21](https://github.com/sketchmacaw/MacawsModsIssues/assets/233815/3d973a30-0bfb-481f-b8af-cbf34e0a87e4)

**Additional context**

This makes it difficult to make different kinds of arched bridges with more naturalistic curves. Also, in addition to the existing bridges and stair bridges, a half-slab bridge height may be helpful also for gentler slopes. 

In general I would find it much more intuitive if bridge pieces, like stairs, respected the orientation you placed them down in (north south or east west), rather then "snapping" towards adjacent bridge pieces like they currently do. If I wanted to customize the orientation they were placed in further, I could use a mod like Tweakaroo to "lock" the placement orientation or tweak it with a scroll wheel.

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.0 update, both pictures can now be done using pliers
