### ISSUE TITLE
Game server crashes after placing ComputerCraft blocks on the place of removed Macaw’s Furniture block

### ISSUE THREAD

**Issue by nordegraph** [sketchmacaw/MacawsModsIssues#339]
**Describe the bug**
If I try to place [ComputerCraft](https://github.com/cc-tweaked/CC-Tweaked) computer or monitor on the place where Macaw’s Furniture block was before, server crashes, presumably due to block entity for some of the blocks not being removed after corresponding block removal from the world. After that server is unable to restart until you remove either Macaw's mod or CC to remove bugged entities from the world save completely.

 See also: 
https://github.com/cc-tweaked/CC-Tweaked/issues/1670
https://github.com/FabricMC/fabric/pull/3510

**Mod name & Minecraft Version and Modloader**: 
Minecraft 1.20.1 + Fabric  0.15.3 + Macaw's Furniture 3.2.1 + cc-tweaked 1.109.3

**To Reproduce**
1. Install both Macaw's Furniture and CC-Tweaked mods 
2. Place block from Macaw's furniture that has internal inventory (e.g. bookshelf) into the world, then remove it
3. Try to place CC's Computer/Monitor on the same position.
4. Crash, world cannot be loaded without entities removal.

** Crash log **
[crash-2024-01-06_06.02.39-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13850192/crash-2024-01-06_06.02.39-server.txt)

Thank you in advance for your help!

**Comment by nordegraph** [comment]
After some time we've encountered this issue again with another combination of blocks involved, so it seems that any mod trying to check nearby entities (Modern Industrialization, Tech Reborn, etc.) can cause this bug. Hereby this issue is severe for us. 

Fabric API fix was implemented only for 1.20.4 version and won't fix the source of issue ("ghost entities" in the world)

Here's sample crash log for Modern Industrialization case from today:
[crash-2024-01-17_06.52.59-server.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13963965/crash-2024-01-17_06.52.59-server.txt)

**Comment by sketchmacaw** [comment]
Please, would you mind testing if it happens with the Double Drawer Counter and Drawer Counters too?

**Comment by sketchmacaw** [comment]
Found the issue, would you mind testing the fix version if I upload it here?

**Comment by nordegraph** [comment]
Thanks, sure I can check it. I'll get back with the result later this day if you'll upload the build here.

**Comment by sketchmacaw** [comment]
[I had to put it in a zip because jar is unsupported.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13965434/I.had.to.put.it.in.a.zip.because.jar.is.unsupported.zip)
It should work now, when you confirm that it is solved, we will release a fix version for every fabric version

**Comment by nordegraph** [comment]
Just tested it with the local copy of the world in question and your test build. 
- you forgot to include fabric.mod.json, so Fabric ignores this version of the mod
- I've added this file from the mod last released version
- attempt to start the game with this version results in crash on game loading (see attached file)
[crash-2024-01-17_17.28.41-client.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13965970/crash-2024-01-17_17.28.41-client.txt)

**Comment by sketchmacaw** [comment]
[fix version.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13966043/fix.version.zip)
I've accidentally sent you the forge version :) ... Sorry

**Comment by nordegraph** [comment]
Tested this version. Bug cannot be reproduced anymore (through it won't fix existing entities in world, so I'll be still urged to remove them forcefully). AFAIK, existing entities can only be fixed on Fabric API side, so this is fine.

**Comment by sketchmacaw** [comment]
Just released the 3.2.2 fix version, closing this.
