### ISSUE TITLE
Wrong and Unneeded Recipes found for Macaw Doors

### ISSUE THREAD

**Issue by Guinaro** [sketchmacaw/MacawsModsIssues#342]
Following Recipes are not needed and produce wrong result anyway and should be removed
	"mcwdoors:warped_mystic_door",
	"mcwdoors:crimson_nether_door"

Warped Planks with Mystic Door Print recipe produces a Warped Paper Door
Crimson Planks with Nether Door Print recipes produces a Crimson Paper Door

MC 1.20.1
Macaw Doors 1.1.0

**Comment by sketchmacaw** [comment]
Fixed in 1.1.1
