### ISSUE TITLE
Rain Gutter breaking issue

### ISSUE THREAD

**Issue by DragonGirl7567** [sketchmacaw/MacawsModsIssues#343]
**Describe the bug**
when breaking the rain gutter (not the base and not dyed) it takes a while to break and does not drop anything

**Mod name & Minecraft Version and Modloader**
Minecraft - 1.20,1
mcw-roofs-2.2.4b-mc1.20.1forge.jar
Forge - 47.2.0

**To Reproduce**
1. Go to world (survival)
2. Place down rain gutter
3. Destory with pixace

**Additional context**
Not Dyed

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.3.0 update
