### ISSUE TITLE
Macaws Fences & Walls 1.1.0 doesnt load correctly.

### ISSUE THREAD

**Issue by ItzLucaGER** [sketchmacaw/MacawsModsIssues#344]
**Describe the bug**
My server doesnt start with the newest version of Macaws Fences

Macaws Fences and Walls 1.1.0 - Forge

1. Update to 1.1.0
2. Start Server
3. Server crashes during the mod loading process

[crash-2024-01-19_07.45.25-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13989205/crash-2024-01-19_07.45.25-fml.txt)

**Comment by sketchmacaw** [comment]
[test fix version in this zip.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13991578/test.fix.version.in.this.zip.zip)
If you can I zipped you a test fix version 1.1.0b, in which I attempt to fix the issue. Could you please test if it still happens with this version in your free time?

**Comment by ItzLucaGER** [comment]
Same issue persists. I included the log.
[crash-2024-01-19_11.45.58-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13991895/crash-2024-01-19_11.45.58-fml.txt)

**Comment by sketchmacaw** [comment]
[test fix version 2 in this zip.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13992263/test.fix.version.2.in.this.zip.zip)
Thanks for testing! I think i figured it out now, sorry for bothering but I have currently no server available to test it out.

**Comment by ItzLucaGER** [comment]
No need to say sorry, Im glad to help :) The issue is indeed fixed, server started without problems and client worked just fine too. Will the hotfix be uploaded to curseforge or can I continue using the file you sent me the next update?

**Comment by sketchmacaw** [comment]
You can use the file until then,it will take a while to fix all the versions

**Comment by ItzLucaGER** [comment]
Alright, will do. Thank you ^^
