### ISSUE TITLE
mod loading error,mcw-fences-1.1.0-mc1.16.5forge

### ISSUE THREAD

**Issue by Yonk316** [sketchmacaw/MacawsModsIssues#345]
[crash-2024-01-19_13.10.12-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13992787/crash-2024-01-19_13.10.12-fml.txt)
**Describe the bug**
crash during startup due to missing Registry entry
Mod Name:mcw-fences-1.1.0-mc1.16.5forge
Minecraft version 1.16.5     Modloader:forge version:1.16.5-forge-36.2.41

**To Reproduce**
crash during loading
![Screenshot (5)](https://github.com/sketchmacaw/MacawsModsIssues/assets/42360206/c01cf9aa-3bfc-4c14-9505-523e2dbee278)

**Screenshots**
screenshot attached.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Are you playing it on a server or just client?

**Comment by LabsZero** [comment]
I can confirm this issue happens on 1.18.2 client side.

**Comment by sketchmacaw** [comment]
I'm uploading a test fix version for 1.16.5 could you please by any chance test it if the issue still persist? 
[zipped mod file.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13993696/zipped.mod.file.zip)

**Comment by sketchmacaw** [comment]
[1.18.2 zipped mod test fix.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13993752/1.18.2.zipped.mod.test.fix.zip)
Also uploading a test fix for 1.18.2 if you have the time, please test it out

**Comment by Yonk316** [comment]
client only,test fix did not work.


________________________________

**Comment by Xelbayria** [comment]
> client only,test fix did not work.

☝️  same with 1.18.2, the fix mod don't work.

**Comment by Nycto97** [comment]
Server crashes also on 1.19.2 with latest 1.1.0 version

[crash-2024-01-19_19.11.23-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13994273/crash-2024-01-19_19.11.23-fml.txt)

**Comment by sketchmacaw** [comment]
Managed to fix this issue in versions 1.19 --> 1.20.4, still trying to solve it for 1.16.5  --> 1.18.2

**Comment by Yonk316** [comment]
Ok.


________________________________

**Comment by SuperChet** [comment]
> Managed to fix this issue in versions 1.19 --> 1.20.4, still trying to solve it for 1.16.5 --> 1.18.2

[MCFencesCrash.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13999196/MCFencesCrash.txt)

Getting a crash too on fences 1.20.1

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.1.1 update, on Curseforge the files are under review for an hour so until then you can get them from Modrinth.

**Comment by Yonk316** [comment]
Version 1.1.1 update is working correctly for 1.16.5

________________________________

**Comment by Xelbayria** [comment]
great, I'll run a test on 1.18.2
