### ISSUE TITLE
Server crash mcw-fences-1.1.0mc1.20.1forge

### ISSUE THREAD

**Issue by DelviousCrafts** [sketchmacaw/MacawsModsIssues#346]
**Describe the bug**
Server crash on startup due to attempt to load a client-only class on server

**Mod name & Minecraft Version and Modloader**
- Minecraft: 1.20.1
- Forge: 47.2.19
- Macaw's Fences: 1.1.0-mc1.20.1

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Install Macaw's Fences 1.1.0 on server
2. The server crashes on startup

**Screenshots**

**Additional context**
[Crash Report](https://gist.github.com/DelviousCrafts/6667186bbce835e604bb42ce64e5d1f4)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by Nycto97** [comment]
Server crashes also on 1.19.2 with latest 1.1.0 version

[crash-2024-01-19_19.11.23-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13994279/crash-2024-01-19_19.11.23-fml.txt)

**Comment by sketchmacaw** [comment]
[1.19.2 test zipped, mod file inside this.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13994322/1.19.2.test.zipped.mod.file.inside.this.zip)
Uploading 1.19.2 to test, if it work I'm going to release it officially, I think I've got 1.19 - 1.20.4 fixed

**Comment by sketchmacaw** [comment]
> Server crashes also on 1.19.2 with latest 1.1.0 version, did not test on client since I downgraded when server crashed, without launching client
> 
> [crash-2024-01-19_19.11.23-fml.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/13994279/crash-2024-01-19_19.11.23-fml.txt)

Could you please try the test fix in the zip attached?

**Comment by Nycto97** [comment]
> [1.19.2 test zipped, mod file inside this.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/13994322/1.19.2.test.zipped.mod.file.inside.this.zip) Uploading 1.19.2 to test, if it work I'm going to release it officially, I think I've got 1.19 - 1.20.4 fixed

Server successfully launched, client successfully launched, successfully joined server with 1.1.0b on client + server 💪🏻

**Comment by sketchmacaw** [comment]
We released a hotfix for 1.19 ---> 1.20.4 for this issue https://legacy.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls/files/all be sure to update and sorry for the inconvienence!
