### ISSUE TITLE
enhancement: place roofs upside-down

### ISSUE THREAD

**Issue by boneskull** [sketchmacaw/MacawsModsIssues#35]
First: I really like the major changes recently; roofs are much easier to work with when you don't have to fuss with the corners. 

However, there doesn't seem to be a way (that I found) to place a roof upside-down. I am not sure if you could do this in the old version. 

(Sorry, I'm on my phone and am not sure how to describe what I'm asking for)

Here's a couple pictures. I would like to make this roof appear flat top & bottom, at a 45 degree angle. Think of how vanilla stairs work:

![image](https://user-images.githubusercontent.com/924465/92311791-2175d480-ef6f-11ea-9149-26a9dcfa48e0.jpeg)

But I cannot place the roof upside-down to achieve this:

![image](https://user-images.githubusercontent.com/924465/92311795-2e92c380-ef6f-11ea-817c-9413daba2f2e.jpeg)

I realize this may be complicated by the new "smart" placement system. 

Thanks!

**Comment by sketchmacaw** [comment]
It has not been implemented, but I've got it planned for the next update, I'm very happy that you like the major update changes!

**Comment by sketchmacaw** [comment]
Added in 2.1.0
