### ISSUE TITLE
Macaw's Windows - Minecraft Forge 1.20.1 - Mosaic Glass Blocks do not let light go through

### ISSUE THREAD

**Issue by SheepyShambler** [sketchmacaw/MacawsModsIssues#350]
**Describe the bug**
Mosaic Glass Blocks don't let light through them

**Mod name & Minecraft Version and Modloader**
Mod: Macaw's Windows 2.21 - (mcw-windows-2.2.1-mc1.20.1forge.jar)
Minecraft version: 1.20.1
Forge Version: 47.2.19

**To Reproduce**
1. Open minecraft with just the described macaw's windows version
2. Place down a box made out of mosaic glass blocks with any light source inside
3. The light from the light source won't go through the mosaic glass blocks, effectively acting like an opaque block, albeit with a transparent texture.

**Screenshots**
![2024-01-30_13 08 52](https://github.com/sketchmacaw/MacawsModsIssues/assets/143990979/dcc8fa4f-0b8f-44b6-8fec-087ad4f83697)
![2024-01-30_13 08 54](https://github.com/sketchmacaw/MacawsModsIssues/assets/143990979/902c95ce-3ab1-41be-99d8-9e70ea6eed8d)
![2024-01-30_13 14 26](https://github.com/sketchmacaw/MacawsModsIssues/assets/143990979/5577d770-be9e-4f4e-aac8-7a6ca7cb23b9)

DO NOTE that Mosaic glass PANES work correctly, as evidenced in the following image:
![2024-01-30_13 13 11](https://github.com/sketchmacaw/MacawsModsIssues/assets/143990979/0b4016e8-d94b-4939-897d-6be7b83c2f1a)

**Additional context**
The test was performed in a clean forge install, but the error was reported in a modpack.

**Comment by sketchmacaw** [comment]
![image](https://github.com/user-attachments/assets/ee0c14be-eaa7-4901-a68c-482ce33252a1)
Working on a fix :)

**Comment by sketchmacaw** [comment]
Fixed in 2.3.0
