### ISSUE TITLE
Crash with EMI and Lambda dynamics?

### ISSUE THREAD

**Issue by serioos** [sketchmacaw/MacawsModsIssues#351]
**Describe the bug**

I have EMI installed on top of JEI and it works well, but every time the items list on the right of the inventory shows one of the fences from Macaw Fences, it crashes for some reason. At least that's what I thought is happening by looking at the crash log. If it's something else that is crashing the game, please do let me know.

**Macaw Fences & Minecraft 1.20.1 and Fabric**

**To Reproduce**

Go to EMI items panel list on the right side of the inventory, and flip pages until it crashes'

**Additional context**

Here is my crash log:

https://pastebin.com/8GjHGNTL

**Comment by sketchmacaw** [comment]
Fixed in the latest 1.1.1 update for Fabric
