### ISSUE TITLE
Macaw's roofs see through slab

### ISSUE THREAD

**Issue by Figi8Cake** [sketchmacaw/MacawsModsIssues#353]
**Describe the bug**
when a slab is placed in front of a roof, the face of the slab touching the roof is invisable

**Mod name & Minecraft Version and Modloader**
Macaws roofs version 2.3, forge 1.19.2 (43.2.8)

**To Reproduce**
1. Place down any regular roof or steep base roof
2. Place down a slab in front of the curved side
3. You can now see under the world through the side of the slab that touches the curved side of roof

**Screenshots**
![2024-02-17_23 00 04](https://github.com/sketchmacaw/MacawsModsIssues/assets/87722837/7d42e877-80d3-490b-9ad2-b1409efe86e0)

**Comment by sketchmacaw** [comment]
Fixed in 2.3.1 update
