### ISSUE TITLE
Game loading crashes when mcw-doors-1.1.0-mc1.20.4fabric.jar is enabled.

### ISSUE THREAD

**Issue by Sparrow231129** [sketchmacaw/MacawsModsIssues#354]
**Describe the bug**
All the other Macaw mods function flawlessly, DOORS causes game loader to crash. Disable DOORS, game loads and plays. Enable DOORS, loader crashes and I never even see the red Minecraft loader screen.

**Mod name & Minecraft Version and Modloader**
Mod Name: "Macaw's Doors" aka mcw-doors-1.1.0-mc1.20.4fabric.jar
Minecraft Version: 1.20.4
Game Launcher and Mod Handler: Prism Launcher 3.0
Game Loader: Fabric, assisted with Sodium and Iris

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Define a Prism Launcher "Instance"
2. Select Modrinth as the primary source for downloading mods
3. Select Fabric as the primary game loader
4. Select various mods, resource packs, shaders, etc.
5. In the primary Prism Launcher window, highlight the instance you created
6. In the primary Prism Launcher window, click "Launch".
7. Wait for the crash screen to appear.

**Screenshots**

**Additional context**
Crash Report Log attached.
[crash-2024-02-21_01.12.18-client.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/14355237/crash-2024-02-21_01.12.18-client.txt)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Dramatic Doors needs to update to the changes that have been made in the most recent Macaw's Doors Update (removed waterlogging), they are [aware of this issue ](https://github.com/Kitteh6660/DramaticDoors/issues/79)

**Comment by Kitteh6660** [comment]
The fix is now up!
