### ISSUE TITLE
Books in the block texture of the Spruce Lower Bookshelf Drawer are upside down

### ISSUE THREAD

**Issue by BigBrainRobin29** [sketchmacaw/MacawsModsIssues#355]
**Describe the bug**
In the block texture of the Spruce Lower Bookshelf Drawer the books are upside down.

**Mod name & Minecraft Version and Modloader**
Macaw's Furnitures, 1.20.1, Fabric

**To Reproduce**
1. Place down a Spruce Lower Bookshelf Drawer

**Screenshots**
![2024-02-24_16 09 06](https://github.com/sketchmacaw/MacawsModsIssues/assets/152532785/bcd8278c-72c5-4166-b189-b84a9bdc7775)

**Comment by sketchmacaw** [comment]
Fixed in the latest update
