### ISSUE TITLE
Bamboo Bridge and Bamboo Bridge Stairs do not connect

### ISSUE THREAD

**Issue by eSonOfAnder** [sketchmacaw/MacawsModsIssues#356]
**Describe the bug**
Both Bamboo and Dry Bamboo Bridges and Bridge Stairs do not connect the same way that the other wooden Bridge and Bridge Stair types do.

**Mod name & Minecraft Version and Modloader**
Macaw's Bridges v2.1.0
Minecraft 1.20.4
Modloader Fabric 0.15.6

**To Reproduce**
1. Place either a Bamboo Bridge Stair or Dry Bamboo Bridge Stair
2. Place either a Bamboo Bridge or Dry Bamboo Bridge one block up and in the direction the stair is facing
3. Place a second Bamboo Bridge or Dry Bamboo Bridge further in the same direction the first two are facing
4. See that the top of the Stair block does not connect with the Bridge block.

**Screenshots**
Screenshot comparing the two Bamboo cases with the Oak case attached.
![2024-02-25_21 00 43](https://github.com/sketchmacaw/MacawsModsIssues/assets/4420108/37e2621a-9781-4014-9224-c6888f6736a8)

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.0 update
