### ISSUE TITLE
Waffle Door Print missing

### ISSUE THREAD

**Issue by alequipelatte** [sketchmacaw/MacawsModsIssues#357]
**Describe the bug**
When trying to craft items, there is a recipe for a Waffle Door that uses a Waffle Door Print. The Waffle Door Print crafting recipe, however, seems to be missing. Even when trying to craft a Cherry Door Print using the same mechanics as the [Wood type] Door Print, there are no results.

**Mod name & Minecraft Version and Modloader**
Macaw's Doors, Fabric 0.11.2

**Comment by sketchmacaw** [comment]
Fixed in 1.1.1
