### ISSUE TITLE
Culling between different window types when on top of each other

### ISSUE THREAD

**Issue by 1Biru** [sketchmacaw/MacawsModsIssues#358]
**Describe the bug**
When placing the resizeable window type under or over another window type, the frame of the resizeable window is culled and there is a hole between the two windows.

**Mod name & Minecraft Version and Modloader**
Macaw's Windows 2.2.1
Forge 1.18.2 40.2.0
no optifine
no other mods installed

**To Reproduce**
1. Go in the game
2. Place down any resizeable window
3. Place down any other window on top of the resizeable window
4. You should be able to see a hole between the two windows

**Screenshots**

![2024-03-07_13 05 59](https://github.com/sketchmacaw/MacawsModsIssues/assets/147753160/1afb69fe-f083-4481-b2d4-dd16dadc117c)

![2024-03-07_13 06 16](https://github.com/sketchmacaw/MacawsModsIssues/assets/147753160/c3b93125-2e89-4ff0-b703-dfd9fd2cb98e)

**Comment by sketchmacaw** [comment]
Fixed in 2.3.0
