### ISSUE TITLE
Reinforced torches from 'Macaw Lights and Torches' get placed as random 'Waystone' parts.

### ISSUE THREAD

**Issue by TommyC81** [sketchmacaw/MacawsModsIssues#359]
**Describe the bug**
Reinforced torches from 'Macaw Lights and Torches' (https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps) turn into Waystone parts from 'Waystones (Fabric Edition)' (https://www.curseforge.com/minecraft/mc-mods/waystones-fabric).

The descriptor of the reinforced torch in the toolbar uses name from 'Compass Finder' (https://www.curseforge.com/minecraft/mc-mods/compass-finder)

**Mod name & Minecraft Version and Modloader**
Minecraft 1.20.4, Fabric 0.15.7

fabric-api-0.96.4+1.20.4.jar

mcw-lights-1.0.6-mc1.20.4fabric.jar
waystones-fabric-1.20.4-16.0.4.jar
gf-compass-finder-0.8-1.20.4.jar

**If you are unsure about something**
Whether some other mod is the actual issue.

**To Reproduce**
1. Place reinforced torch.
2. Get random part from Waystones.
3. Observe the description of the reinforced torch to be referring to Compass Finder.

**Screenshots**
Not available at this time,

**Additional context**
Got many mods installed, carefully scrutinized for compatibility (or known issues) to avoid problems. All mods updated to latest version using ferium.

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Does this happen on the server or client? In many cases this happens when there is a version mismatched on the server and a different one in client

**Comment by TommyC81** [comment]
This happened on the client at the time. I have since revised server/client mod distribution and have not experienced the problem again. I'm not sure what caused the problem, but cannot rule out user error - perhaps duplicated mods on server or client causing different versions to load? This ticket can be closed, thank you for the reply and the work you put into this!
