### ISSUE TITLE
[MCW Trapdoors] Waffle trapdoors do not have a special tag

### ISSUE THREAD

**Issue by cyyynthia** [sketchmacaw/MacawsModsIssues#360]
**Describe the bug**
Waffle trapdoors do not have a special tag

**Mod name & Minecraft Version and Modloader**
Macaw's Trapdoors 1.1.2, Minecraft 1.20.1, Forge 47.2.20

**To Reproduce**
1. Look up tags for a waffle trapdoor (in any wood variant)
2. It does not have an associated `#mcwtrpdoors:waffle_trapdoors` tag

**Additional context**
This is very useful for modifying recipes in modpacks, as it allows targeting all trapdoors of a given variant type.

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.1.3 update
