### ISSUE TITLE
Bridge Support is not a full block.

### ISSUE THREAD

**Issue by Saremist** [sketchmacaw/MacawsModsIssues#363]
**Describe the bug**
Bridge supports are not a full block.
You can jump on a invisible ledge if on flat wall normal block transition to bridge supports vertically.
Also as they are not a full block villagers try to path find across them and got them self stuck on that ledge and are not able to move on their own.

**Mod name & Minecraft Version and Modloader**
Forge for 1.20.1 with Macaw's Bridges and BOP expantion

**To Reproduce**
1. Build a 2 high wall of normal block and bridge support on top
![obraz_2024-03-27_182504194](https://github.com/sketchmacaw/MacawsModsIssues/assets/56411511/b6a8c539-e586-4bb7-a45a-a7885b088a14)
2. Jump into the wall trying to get on top of the normal block
3. Player gets stuck on ledge
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/56411511/b08c1a7a-f468-4727-830f-b604864853df)
4. Look at the Z coordinate in F3 screen. it is .001 smaller then full block should give

![obraz_2024-03-27_182003021](https://github.com/sketchmacaw/MacawsModsIssues/assets/56411511/9816fca0-fa18-47c8-847e-018df29c74a9)

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.0 update
