### ISSUE TITLE
[Question] Question about the bookshelves in Macaw's Furniture

### ISSUE THREAD

**Issue by Gamemassa** [sketchmacaw/MacawsModsIssues#365]
Hi, I had asked this on Curseforge as well, but are the bookshelves in Macaw's Furniture supposed to power enchanting tables like a vanilla bookshelf, or are they just decorative?

**Comment by sketchmacaw** [comment]
They are powering the enchanting tables, like vanila bookshelves

**Comment by Gamemassa** [comment]
> They are powering the enchanting tables, like vanila bookshelves

Ok, well for some reason they're not powering Fuzs' Enchanting Infuser (which is a modded version of an enchanting table with some extra features).
