### ISSUE TITLE
3.0.0 crash at game load; 1.19.2, Forge

### ISSUE THREAD

**Issue by burghenby** [sketchmacaw/MacawsModsIssues#366]
**Describe the bug**
Game crash at load (before reaching the main menu) with version 3.0.0

**Mod name & Minecraft Version and Modloader**
Macaw's Bridge's 3.0.0 - Minecraft 1.19.2 - Forge

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1.) Update to 3.0.0 from 2.1.0
2.) Attempt to open game
3.) Game crashes when load bar finishes

**Screenshots**

**Additional context**
I updated this mod with a few others at the same time, so I had to go through the process of rolling back all of them and then updating one and a time to see who was the crash culprit. My game only crashed post-updating with Bridge 3.0.0, not with the other mods that I updated at the same time (Atmospheric, Abnormal's Delight, Embeddium, Bumblezone, Seasonhud, Polymorph). Once Bridges 3.0.0 was the last one, I downgraded it back to 2.1.0 and my game loaded without issue.

Attached the final crash report, when Bridges 3.0.0 was the last to be updated of the group.
[crash-2024-04-06_20.34.14-client.txt](https://github.com/sketchmacaw/MacawsModsIssues/files/14895391/crash-2024-04-06_20.34.14-client.txt)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
You will have to wait for everycompat to update to work with the bridges 3.0.0 update, they are aware of this.

**Comment by burghenby** [comment]
Oohhhh, gotcha! Thanks for letting me know! I can wait. ^.^
