### ISSUE TITLE
Open Macaw's Windows don't move on Create Mod contraptions

### ISSUE THREAD

**Issue by goldrat1** [sketchmacaw/MacawsModsIssues#369]
Hi there,
I've noticed that if a Window from Macaw's Windows is open, they won't connect or move on any Contraptions from the Create Mod.  Closed windows work perfectly fine and even work with rotation (yippee!) but open ones don't connect via glue or chassis at all.

Playing on 1.20.1, MCW v2.2.1.

**To Reproduce**
Steps to reproduce this behavior:
1. Build a build that includes a Macaw's Windows window and open it by right-clicking.
2. Use Super Glue or Chassis to connect these blocks together.
3. Move the connected blocks using a Mechanical Piston, Bearing, Gantry, Minecart, etc.
4. Windows that are open do not attach.

Example below:
Closed windows connect fine:
![2024-04-08_22 44 06](https://github.com/sketchmacaw/MacawsModsIssues/assets/45552594/9da8c244-3135-4a1d-97cd-9ec83dd4c910)
Open windows don't connect at all:
![2024-04-08_22 44 17](https://github.com/sketchmacaw/MacawsModsIssues/assets/45552594/d5760b7b-1650-495c-a8bf-2e100afa7e7c)

I presume this is because open windows don't count as actual blocks, as when holding CTRL to show what blocks are connected via glue, these blocks aren't included, as seen below.
![2024-04-08_22 45 24](https://github.com/sketchmacaw/MacawsModsIssues/assets/45552594/71973569-f711-43dc-9311-c5198dd9ac60)

I would love compatibility in this way as it'd make moving buildings utilising Macaw's Windows less prone to being broken (as if a contraption stops where an open window is, the window breaks).

**Comment by goldrat1** [comment]
Ought to mention that Curtains also don't connect via Glue at all :(

**Comment by sketchmacaw** [comment]
![image](https://github.com/user-attachments/assets/6dfcf4ed-027c-4b1e-a030-457f22b4d92c)
 Working on a fix ;)

**Comment by sketchmacaw** [comment]
Fixed in 2.3.0
