### ISSUE TITLE
Bridges 3.0 crash on Fabric

### ISSUE THREAD

**Issue by Lord-Greyhawk** [sketchmacaw/MacawsModsIssues#370]
After a long fight with Modrinth Error logging and a bit of trial and error, I foound that either 1 or both of the Macw's Bridge mods were causing my worlds to crash on loading. (Bridges 3.0 and Bridges BOP. I figured I needed to use both, since I run Biomes a Plenty.) It did also list errors loading Biomes o Plenty and Graveyards. I tried deactivating each and only Bridges seemed to allow the world to load when deactivated.
I am running Minecraft Jave 1.20.4 and fabric loader 0.15.9

**Comment by Lord-Greyhawk** [comment]
Update: Looks like its the Cridged mod for Biomes o Plenty that is at fault. Unfortunately, no brdges are showing up using just ththe 3.0 Bridge mod.

**Comment by sketchmacaw** [comment]
We are not the creators of the Bridges BOP addon, about the bridges 3.0 tab is not showing?

**Comment by Lord-Greyhawk** [comment]
It seems to be running, but not bridges were showing in the Work Bench. Also, Biomes O Plenty still seems to have a few conflict issues at times. I've had a couple load fails when Bridges 3.0 was active.  It's not a regular thing though. Maybe its a stacking issue, needing to place one mod above the other for loading. I thing I need to chat with the BOP version creators a bit more and see if their mod is adjusting BOP to work with Bridges.

**Comment by sketchmacaw** [comment]
Bridges should show in the workbench if you collect the necessary items to make them, for example wood for wood bridges etc. Have they figured out the issue?
