### ISSUE TITLE
Macaw's door not instaling recipes

### ISSUE THREAD

**Issue by DLJ7666** [sketchmacaw/MacawsModsIssues#372]
**Describe the bug**
The mod content seems uncraftable.

**Mod name & Minecraft Version and Modloader** Macaw's Door, 1.20.4, Frabric

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
2. Place down '....'
3. Open  '....'
4. This is the issue '....'

**Screenshots**

**Additional context**

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by DLJ7666** [comment]
I play on a server, I do have fabric installed both in my client and in the server, and I know the recipes from some tutorials I've seen. However, having also JEI installed, it doesn't show recipes for any item in the mod. For some reference, I have Macaw's Windows as well and works fine.

**Comment by DLJ7666** [comment]
**I have also tried to just craft them, with no success.

**Comment by sketchmacaw** [comment]
Do you have the same version of doors on both client and fabric? It you could send me the client & server log it would really help to find the reason behind this.

**Comment by DLJ7666** [comment]
I just realized I had different versions, would try later with the same version

**Comment by DLJ7666** [comment]
It works now, sorry to have disturbed
