### ISSUE TITLE
Datapack issue, again

### ISSUE THREAD

**Issue by owl7777** [sketchmacaw/MacawsModsIssues#375]
**Describe the bug**
The bug happens when you try to load a world or create a new one with the attached modpack installed. It says that the "datapack" is broken and i can't load the world. I use no datapacks. Of course Safe Mode does not do anything, if it was not the case i would have not been reporting anything.
**Mod name & Minecraft Version and Modloader**
1.16.5 forge 36.2.39, i use all Macaw's mods

**To Reproduce**
Download listed mods
Run Minecraft
Try to create a world, best not try to load one, i think it may be unsafe to try, although my worlds are fine
**Screenshots**
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/86301422/83cd195b-7fef-4198-96fe-022d16a98d18)

**Additional context**
I use BYG and BOG extensions for more wood types added to your mods. I'd like to say that the issue may be due to a couple of mods, but in these 91 max 3 are the problem. I have encountered no errors like that in my long time playing Minecraft, so i go write a bug report.

**Suggestion**
I know it would be a lot of trouble, but one day i'd be happy to see official support for BYG or BOG.

**MODPACK**
The original file is too big, 200 MB, so i will just add a screenshot. PS. It's definitly not Optifine
![image](https://github.com/sketchmacaw/MacawsModsIssues/assets/86301422/82173717-9b03-4584-a7c3-96f14fea93a6)

**Comment by sketchmacaw** [comment]
Can you send me the log?

**Comment by owl7777** [comment]
There may be no log since it is not a crash... but i'll look

**Comment by owl7777** [comment]
It appears i have cut down the search area to about 15 mods. Soon I'll know and tell you, of course i will generate the log

**Comment by owl7777** [comment]
[latest.log](https://github.com/sketchmacaw/MacawsModsIssues/files/15264733/latest.log)

**Comment by owl7777** [comment]
That is the log, it MAY be it and probably is

**Comment by sketchmacaw** [comment]
Have you tried removing the macawsroofsbyg? It looks like its causing many errors with recipes, it also could be corn delight causing it try to remove that one.

**Comment by owl7777** [comment]
It appears to be Corn Delight. It is an addon for my very beloved Farmer's Delight. Is the bug by any case fixable?

**Comment by sketchmacaw** [comment]
We are not the devs for corn delight and also not for byg addon, we don't know if its fixable. You have to ask the devs
