### ISSUE TITLE
"destroyer of fabric api" in macaw's trapdoors

### ISSUE THREAD

**Issue by moonmaidens** [sketchmacaw/MacawsModsIssues#379]
as far as i can tell, the new update of macaw's trapdoors (released today) installs something called "destroyer of fabric api" as a jar mod, which just causes the minecraft loader to crash. not sure how it got in there so i'm not sure if it's malicious beyond just temporarily breaking minecraft. it redownloads every time i install today's update. is this a prank or a hack?

<img width="838" alt="destroyer of fabric i" src="https://github.com/sketchmacaw/MacawsModsIssues/assets/110436317/8103fe53-5757-4b4e-827e-4b1b4742c900">

i'm using minecraft 1.20.1, fabric, but because today's update seems to have been released for every single loader and version i'm not sure how many are affected.

<img width="846" alt="mcw trapdoors ii" src="https://github.com/sketchmacaw/MacawsModsIssues/assets/110436317/055a88f7-6d4a-4cda-a1ad-ceafb92c0773">

<img width="846" alt="mcw trapdoors i" src="https://github.com/sketchmacaw/MacawsModsIssues/assets/110436317/bd994758-6700-4754-aa7c-b5663e0d7cfb">

not sure what's going on, but attempting to load minecraft with "destroyer of fabric api .jar" just ends up in continuous crashes until removed. there's not this issue when reinstalling older versions of the mod. 

edit: it appears to only happen when installed through the curseforge app, though only for "macaw's trapdoors" and no other mod i update.

another edit: might have been a dependency typo when the mod update was uploaded?

**Comment by TelepathicGrunt** [comment]
@moonmaidens i would hope it is not malicious addition lol. Likely just a typo when adding dependencies. You can open up the mod folder for your modpack instance and delete the mod jar. Then curseforge app should let you launch it without the mod and macaw doors should be ok

**Comment by sketchmacaw** [comment]
Yep fixed it, I hate it when something has the same name .......... It's just a "typo" on cf

**Comment by TelepathicGrunt** [comment]
Note, if you setup your projects to upload to CF with a gradle task like this:
https://github.com/modmuss50/mod-publish-plugin

You can manually specify the dependency with it and auto upload to CF with correct dependency every time. It is much faster than manually uploading your jars every time
