### ISSUE TITLE
Traslations es_ar es_es

### ISSUE THREAD

**Issue by Yupoman** [sketchmacaw/MacawsModsIssues#38]
I upload the translations here since the curseforge shit page marks me as spam when I put long texts

[lang es trapdoor.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/5241599/lang.es.trapdoor.zip)
[it is the same as here](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors?comment=16)

[lang es door.zip](https://github.com/sketchmacaw/MacawsModsIssues/files/5241605/lang.es.door.zip)
I added the variants for the crimson and warped doors (of course subject to changes). Hopefully they will be added in the future.

**Comment by sketchmacaw** [comment]
Yep, currently working on a new version for doors. I will add the translations to the upcoming update, which should be out in a few days.
