### ISSUE TITLE
Macaw's Doors 1.1.1 - Fabric 0.15.11- java.lang.RuntimeException

### ISSUE THREAD

**Issue by glytch-g** [sketchmacaw/MacawsModsIssues#384]
When launching the game, it crashes. The pop up error says "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcwdoors'!"

Minecraft version 1.20.6
fabric 0.15.11
mcw-doors-1.1.1fabric-mc1.20.6

1. Launch minecraft

[crash-2024-06-24_06.10.02-client.txt](https://github.com/user-attachments/files/15953605/crash-2024-06-24_06.10.02-client.txt)
![Game crash errpr](https://github.com/sketchmacaw/MacawsModsIssues/assets/71888131/698cef31-ee7c-486a-81c2-1a128a73d2cb)
[latest.log](https://github.com/user-attachments/files/15953619/latest.log)

**Comment by sketchmacaw** [comment]
Could you try it without Dramatic Doors? Just to be sure

**Comment by glytch-g** [comment]
My apologies, totally forgot I even had that and missed it when I was doing troubleshooting. I took it away and removed it. It works now. Thank you.
