### ISSUE TITLE
Long time in Loading Screen (Fences)

### ISSUE THREAD

**Issue by 5stigma** [sketchmacaw/MacawsModsIssues#386]
**Describe the bug**
Loading time is increased 6x 

**Mod name & Minecraft Version and Modloader**
mcw-fences-1.1.2-mc1.19.2forge

**To Reproduce**
1. Put the mod into the folder with mods that add woods
2. Launch Minecraft

**additional information**
I notice that CPU usage drops drastically.

**Comment by sketchmacaw** [comment]
How many wood types do you add?

**Comment by 5stigma** [comment]
Quark, Regions Unexplored, Pyromancer, Ars Noveau, Fruits Deligh, Croptopia and some others

The previous version does not have this issue

**Comment by sketchmacaw** [comment]
I will need you complete mod list to test this, you can just send me a screenshot of all the mods so it can be read..

**Comment by 5stigma** [comment]
Its Looooooooooong . __ .
Here is my mod list [modlist.txt](https://github.com/user-attachments/files/15964578/modlist.txt)

**Comment by 5stigma** [comment]
I send you my modpack?

**Comment by 5stigma** [comment]
Solve with last version of EveryCompat mod
