### ISSUE TITLE
Latest Mod version for 1.20.4 Fabric error

### ISSUE THREAD

**Issue by Anonyku05** [sketchmacaw/MacawsModsIssues#400]
**Describe the bug**
At launch it's basically this:
![image](https://github.com/user-attachments/assets/f274d967-08d4-4cc1-8355-89fab727c8bb)

**Mod name & Minecraft Version and Modloader**
Macaws Window 2.3.0 for Minecraft 1.20.4 Fabric
**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Download Latest 1.20.4 mod version for Fabric
2. Start Minecraft

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
on it, working on a quick fixed version

**Comment by sketchmacaw** [comment]
https://modrinth.com/mod/macaws-windows/version/2.3.1   or  https://legacy.curseforge.com/minecraft/mc-mods/macaws-windows/files/5589940

Will be shortly available on CF too, sorry for the inconvienence
