### ISSUE TITLE
Macaw's Windows crash when placing Gothic stone window

### ISSUE THREAD

**Issue by Sylvisuecosplay** [sketchmacaw/MacawsModsIssues#401]
**Describe the bug**
When placing the Stone Gothic window, game crashes

**Mod name & Minecraft Version and Modloader**
Macaw's Windows, Minecraft 1.21 Neoforge 21.0.148
**To Reproduce**
1. Create Gothic stone window
2. Try to place
3. Game saves and error pops up

**Screenshots**
![Screenshot 2024-08-02 200913](https://github.com/user-attachments/assets/f616744c-550b-441a-afa7-484f3fca25b6)

Love the mod and textures!

**Comment by sketchmacaw** [comment]
Fixed in the latest 2.3.2 update
