### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Leiriad** [sketchmacaw/MacawsModsIssues#402]
**Describe the bug**
When I add mcw-doors-1.1.1forge-mc1.20.1.jar or mcw-furniture-3.3.0-mc1.20.1forge.jar to my server, I'm unable to connect: the players get kicked out.

**Mod name & Minecraft Version and Modloader**
Minecraft 1.20.1

**To Reproduce**
1. Create a Minecraft 1.20.1 neoforge server
2. Add one of the two mods
3. Launch the server
4. Try to connect a player

**Screenshots**
![2024-08-03 12_44_32-](https://github.com/user-attachments/assets/9cfa72be-7968-42d4-8c46-2ecc473d6618)

**Comment by sketchmacaw** [comment]
Can you send me the log file?

**Comment by sketchmacaw** [comment]
Do you also have the mod installed, or is the mod only on the server?

**Comment by Zykana** [comment]
Having a similar issue on 1.20.1 Fabric 16.0

**Comment by sketchmacaw** [comment]
> Having a similar issue on 1.20.1 Fabric 16.0

Send me the logs

**Comment by Leiriad** [comment]
I reinstalled my server today on another hosting service. It works fine. Your mods have no issues, it was a defect on the server side.
