### ISSUE TITLE
Macaw's Paths not wokring properly

### ISSUE THREAD

**Issue by heloo2u** [sketchmacaw/MacawsModsIssues#403]
**A clear and concise description of what the bug is.**
I was booting up my game and as soon as I got in, all the pebble paths I placed down had turned into prismarine slabs with water on top. I've tried reinstalling the mod and even wiping all my mods and redownloading every single one but none of it has worked.
**Mod name & Minecraft Version and Modloader**
Macaw's Paths and Pavings; Version 1.20.4; Cursed Forge with Fabric
**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Download Macaw's Paths and Pavings
2. Create a creative world
3. Grab a pebble path
4. Place down the path

**Screenshots**
![2024-08-04_11 59 42](https://github.com/user-attachments/assets/5dabff45-6894-4f77-9e4a-2d5d2cd72b2d)

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Is this happening in singleplayer?

**Comment by heloo2u** [comment]
No, this is in a multiplayer sever

**Comment by sketchmacaw** [comment]
There is a mismatch between versions, all the mods needs to be the same on the server and client too. Otherwise if there is a newer or older mod it will have different ID's on the server and different in your client. Causing this mashup. Not just Macaw's be sure that  all of the mods on the server are the same as in the client.

**Comment by heloo2u** [comment]
Alright I'll make sure, thank you so much :)

**Comment by sketchmacaw** [comment]
Awesome, let me know if it helped :)

**Comment by heloo2u** [comment]
I am sorry, but it is not working.

**Comment by sketchmacaw** [comment]
In that case, can you send me the server and client log, and also the mod list on both?

**Comment by heloo2u** [comment]
I'll try my best

**Comment by heloo2u** [comment]
![image](https://github.com/user-attachments/assets/92296fde-11a3-4324-994f-3661c647469c)

**Comment by heloo2u** [comment]
![image](https://github.com/user-attachments/assets/bdb7cfaf-6146-43e9-b8fe-b1d3072f4891)

**Comment by heloo2u** [comment]
I GOT IT TO WORK!!!

**Comment by sketchmacaw** [comment]
Was there a different version?

**Comment by heloo2u** [comment]
yes

**Comment by heloo2u** [comment]
thank you so much Macaw

**Comment by sketchmacaw** [comment]
You're welcome, hey now you learned how to fix an issue if there is weird blocks placing :D
