### ISSUE TITLE
Crash when looking at a jungle drawer

### ISSUE THREAD

**Issue by 10Maximus10** [sketchmacaw/MacawsModsIssues#407]
**Describe the bug**
Crash when looking at a drawer on Minecraft 1.21.1

**Mod name & Minecraft Version and Modloader**
Macaw's Furniture, Minecraft 1.21.1, NeoForge 21.1.8

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Open a world or join a server.
2. Place down a drawer.
3. Look at it.

**Screenshots**

**Additional context**
https://mclo.gs/bGXte5p

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the 1.21.1 port, issue happened because of using a 1.21 version on 1.21.1

**Comment by 10Maximus10** [comment]
Thank you
