### ISSUE TITLE
Connection lost whenever i try to take item in inventory or drop it

### ISSUE THREAD

**Issue by Shingen96** [sketchmacaw/MacawsModsIssues#416]
To reproduce issue in server creative mode when i take item in my inventory or drop it i get error

**Connection lost
Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot'**

It works fine in SP 
version 1.21.1 fabric
mod version mcw-furniture-3.3.0-mc1.21.1fabric

Edit i don't see option how to properly label post in edit my apologies

**Comment by sketchmacaw** [comment]
Is the mod installed on the server too? Send me the log

**Comment by Shingen96** [comment]
> Is the mod installed on the server too? Send me the log

Yes, it's installed on the server. Here is log files from yesterday 
[2024-09-06-logs.zip](https://github.com/user-attachments/files/16917242/2024-09-06-logs.zip)
