### ISSUE TITLE
Cherry Bark Trapdoor text string is missing

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [sketchmacaw/MacawsModsIssues#432]
**Cherry Bark Trapdoor text string is missing**
Cherry Bark Trapdoor text string is missing in en_us.json

**Mod name & Minecraft Version and Modloader**
Macaw's Trapdoors
1.20.1
Forge

**If you are unsure about something**
 Ask for help on Discord ([https://discord.gg/Jmpdj8W](https://discord.gg/Jmpdj8W)) ***#support-chat*** 

**To Reproduce**
1. Go to the Creative Mode Inventory
2. Get to Macaw's Trapdoors
3. Highlight the Cherry Bark Trapdoor, which has text missing

**Thanks!**
Thank you for helping me by reporting issues c:

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.1.4 Update
