### ISSUE TITLE
Add support for Neoforge on 1.21.1 for Bridges, Doors, Fences, Lights and Trapdoors (and other)

### ISSUE THREAD

**Issue by Crossmax14** [sketchmacaw/MacawsModsIssues#446]
Starting with version 1.20, Neoforge was introduced as a replacement for Forge and almost entire Forge team joined Neoforge (as explained here: [Neoforge News](https://neoforged.net/news/2023-retrospection/#the-fork)). Since then, I’ve noticed that many mod developers are releasing versions of their mods for Minecraft 1.20.1 on Forge, Fabric, and Neoforge. However, beginning with version 1.21, many mod developers are opting to release their mods only for Neoforge and Fabric, skipping Forge entirely.
Examples of such mods include Sophisticated Backpacks, Croptopia.

Therefore, if I want to update my Minecraft server from version 1.20.1 to 1.21.1, I’ll need to switch all my mods (about 30) from Forge to Neoforge. Without making this switch, I’ll be stuck on version 1.20.1 and unable to continue updating my server without losing my world, which I’ve been building for several years.

So, my question is: are there any plans to release the mods mentioned in the title on the Neoforge loader?
And if so, when can we approximately expect this releases?

**Comment by sketchmacaw** [comment]
Those are already released https://www.curseforge.com/minecraft/mc-mods/macaws-doors/files/all?page=1&pageSize=20&gameVersionTypeId=6 here doors for example
