### ISSUE TITLE
[Suggestion] Have Windows connect to Wall

### ISSUE THREAD

**Issue by drakray** [sketchmacaw/MacawsModsIssues#46]
***Suggestion***

Simple, as the title says.
I think it would be nice, specifically for the Brick Windows, to be able to pull the wall to them(connect), so that the detailing would stick out from centered wall, instead of being encrusted in the full block one.

What do you think?

**Comment by sketchmacaw** [comment]
Sounds good

**Comment by sketchmacaw** [comment]
Added in 1.0.3 for 1.16.5
