### ISSUE TITLE
Doors allow wall hacking

### ISSUE THREAD

**Issue by MarioSMB** [sketchmacaw/MacawsModsIssues#47]
Placing some doors (for example, the western style doors) against a wall exposes the world behind the door, allowing very easy wall hacking.

**Comment by sketchmacaw** [comment]
Which Minecraft version?

**Comment by MarioSMB** [comment]
Sorry about that, my version is 1.15.2, here is a picture of the door issue: https://i.imgur.com/NkcYydX.png  
I have only tested with western doors, but this does allow seeing into caves below ground as well. It occurs on servers and with or without Optifine.

**Comment by Barerock** [comment]
Also experiencing this on 1.16.4 with Forge 35.1.10. I am running shaders too, but I've yet to test without because I have IE (which causes crashing when switching).

**Comment by sketchmacaw** [comment]
Fixed in 1.0.2
