### ISSUE TITLE
[Suggestion][1.16.3] Quark's Lock Rotation Tweak feature for Roofs

### ISSUE THREAD

**Issue by drakray** [sketchmacaw/MacawsModsIssues#48]
As the title says, I think it could be nice to have support for Quark's Lock Rotation for the Roof parts, especially if upside down roofing become available

Unless you have something planned already without (soft) dependency ;)

Labels: 1.16.3, Macaw's Roofs, ***Suggestion***

**Comment by NillerMedDild** [comment]
At the moment, placing Roof with Quark's Lock Rotation enabled allows you to dupe the Roof block, so this suggestion would be extra helpful :)

Video of dupe: https://user-images.githubusercontent.com/32136200/104107157-357d6a00-52b2-11eb-8c1d-ae8f241c0853.mp4

**Comment by sketchmacaw** [comment]
This should be fixed now, the lower and steep roof are now separated into more parts.
