### ISSUE TITLE
Incompatible Datapack(s) 

### ISSUE THREAD

**Issue by Coraline77447** [sketchmacaw/MacawsModsIssues#49]
1.16.4, Forge 1.16.4/35.1.0, Macaw's Roofs 1.16.4/2.0.0, Macaw's Windows 1.16.4/1.0.2, Datapacks

Incompatible Datapack(s) 
Hi. I'm here to report an issue involving datapacks with this mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds and when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors!!!

**Comment by sketchmacaw** [comment]
confirmed

**Comment by sketchmacaw** [comment]
- Should be fixed in the newest updates, except Windows which will get fixed in the next month.

**Comment by Coraline77447** [comment]
I've figured out what's causing the incompatible datapack problem, you need to update your mods pack_format version to 6 instead of wherever they're currently at right now or else I would have to manually update it myself when I shouldn't be the one to do that since it's your job to do that.

**Comment by sketchmacaw** [comment]
Yep, it was a big typo. I is fixed for everything except windows. I'm making an update for them which will fix it too and this issue will be closed.

**Comment by sketchmacaw** [comment]
Fixed in 1.0.3 for 1.16.5 windows
