### ISSUE TITLE
Macaw's Windows default state is waterlogged?

### ISSUE THREAD

**Issue by hvdklauw** [sketchmacaw/MacawsModsIssues#53]
At the building gadgets repo we got the following report: https://github.com/Direwolf20-MC/BuildingGadgets/issues/579
Which very much reminded us of https://github.com/Direwolf20-MC/BuildingGadgets/issues/553

As I can't seem to find the source of your mods I was wondering if this is the same basic issue where the default state of the window is that it's waterlogged?

To prevent weird things we use the default state for blocks except a few very specific state items, to prevent floods waterlogged is not one of them.

**Comment by sketchmacaw** [comment]
Should be fixed in 1.0.3 for 1.16.5
