### ISSUE TITLE
Doors texture rendering trouble

### ISSUE THREAD

**Issue by the-Shad** [sketchmacaw/MacawsModsIssues#54]
When you look at one side of the door it looks like that:

![image](https://user-images.githubusercontent.com/66843655/104580131-85b74c00-5665-11eb-8046-9a7751e10474.png)
Optifine doesn't cause this. I tried both forge 35.1.36 and 35.1.4 with 1.0.1 version. 
Labels: 1.16.4, Macaw's Doors, Bug, Texture

**Comment by sketchmacaw** [comment]
Should be fixed in 1.0.2
