### ISSUE TITLE
Use Forge tags for Crafting recipes / Uncraftable items

### ISSUE THREAD

**Issue by Brawaru** [sketchmacaw/MacawsModsIssues#55]
Consider using Forge tags in crafting recipes where applicable.

For example, when using Quark mod, it adds different wooden chests, replacing vanilla recipe. This effectively makes things like Drawer uncraftable due to them using only vanilla `minecraft:chest` instead of [`forge:chests/wooden`](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/generated/resources/data/forge/tags/blocks/chests/wooden.json).

Labels: 1.16.4, Macaw's Furniture, Bug, Suggestion

**Comment by sketchmacaw** [comment]
Fixed in 2.0.1
