### ISSUE TITLE
GL error with shaders

### ISSUE THREAD

**Issue by MJRamon** [sketchmacaw/MacawsModsIssues#59]
The first second I've placed roof block, I begun to recieve messages about GL error. No noticable log records about that in console. eventually, I've got a big impact on FPS the more roof blocks I've placed.

Versions:
Minecraft 1.16.4
Forge 35.1.28
OptiFine_1.16.4_HD_U_G5
mcws-roofs-2.0.0-mc1.16.4

Shaders: Sildurs Vibrant Shaders v1.281 Lite

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
