### ISSUE TITLE
Bug AI - Mobs stopped at any point while crossing bridge

### ISSUE THREAD

**Issue by sketchmacaw** [sketchmacaw/MacawsModsIssues#6]
I tested it with a Custom NPC but also tested with a Regular Creeper to make sure this was a general AI problem. The AI seem to manage walking across sometimes but if they are stopped at any point while crossing like say being hit or something they will just sit there staring.

**Comment by Lafolie** [comment]
I have also noticed this. I have also noticed that their response to the bridge blocks is to try and jump over them, so they will continuously jump whilst traversing them.

**Comment by sketchmacaw** [comment]
Fixed in upcoming 3.0.0 update
