### ISSUE TITLE
Item Duplication with Mana and Artifice mod

### ISSUE THREAD

**Issue by crcabanillas** [sketchmacaw/MacawsModsIssues#65]
Macaw's Roofs 2.0.1-mc1.16.4
Mana-and-Artifice-1.2.1.9

Spruce Planks Lower Roof, Oak Planks Lower Roof, Probably other wood types as well.

When you use a M&A Break Spell on the front "block" of the lower roof model the 2 block roof piece doesn't break but an item does drop. Using the spell on the back half removes the block from the world and drops another lower roof block. This doesn't happen when I've used a Vanilla axe.

Unrelated to this specific issue but I can't for the life of me figure out how to place the lower roof block in the direction I intend. I'll keep clicking till I figure it out.

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
