### ISSUE TITLE
Other Platform Accessibilities For Mods

### ISSUE THREAD

**Issue by AardvarkBlossom** [sketchmacaw/MacawsModsIssues#67]
Mister Macaw, 

I understand you might not have the time for this, but please take my suggestion seriously. I've taken a look at your mods. From what I've seen there really isn't any way for us Bedrock Edition players (I'm a Windows 10 player myself) to get your mods. I've looked. I've tried converting them, but as I'm not great at the whole modding scene it didn't work out well. 

When I first discovered them, I was extremely excited. But upon further investigation I noticed your mods run only for the Java version, which was to my utter shock and pure disappointment. I was hoping that you might be able to make a version for at very least Windows 10, as many Windows 10 versions of mods can be shared with Pocket Edition and vice versa. 

I don't personally expect to see it make a path in this direction as I'm sure you are busy adding to your Java Edition mods and have other personal responsibilities and obligations. However, should you decide to follow my suggestion, assuming you have the free time to spare for such a large undertaking, and make a version for a wider branch of us Minecraft fans, I'll be very happy to be the first to test it out. 

I do still enjoy watching your mod update videos and imagining how I could incorporate the designs of your unique items into some of my worlds and builds. Perhaps I'll continue to cheer you on from the sidelines. Thank you for your hard work and dedication to these simple people pleasers, and for taking the time to read this, it means quite a bit more than I'd like to admit.

Sincerely,
Aardvark_Blossom

**Comment by sketchmacaw** [comment]
I plan to look into bedrock this year, I can't promise anything. But I would love to expand my mods for other platforms

**Comment by sketchmacaw** [comment]
Added to roadmap
