### ISSUE TITLE
Placing fence on snow with "Snow Real Magic" mod installed

### ISSUE THREAD

**Issue by pjlasl** [sketchmacaw/MacawsModsIssues#69]
Description: 
When adding a fence on a block that has snow, the texture shown is the "Snow Real Magic" texture and not your texture.

Here is a screenshot:
[Imgur](https://i.imgur.com/BIgfqT4.png)

Labels: Macaw Fence 1.0.0

Workaround:
I have to clear the snow before I place your fence

**Comment by sketchmacaw** [comment]
Issue is caused from snow real, can't fix it on my side
