### ISSUE TITLE
Standing/ Walking on the railing is considered flying by the server.

### ISSUE THREAD

**Issue by sketchmacaw** [sketchmacaw/MacawsModsIssues#7]
I am using mcw-bridges-1.0.4 1.15.2. While walking on the bridge is fine, if you walk on the railing of the bridge the server kicks you for flying.

**Comment by Dum4G** [comment]
Also happens on 1.16.4

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.0.0 Bridges Update
