### ISSUE TITLE
Tall blinds drop as items when breaking them in creative mode

### ISSUE THREAD

**Issue by ochotonida** [sketchmacaw/MacawsModsIssues#72]
Title. This happens both when you break the top or the bottom block.
(also, it doesn't seem like I can add labels. This happens in the 1.16 version of Macaw's Windows)

**Comment by sketchmacaw** [comment]
Tall Blinds have been removed in the upcoming 2.0.0 update, they can now be stacked up to make a new two block tall blind. Meaning this is fixed.
