### ISSUE TITLE
[1.16.5] Shoji doors have no sound

### ISSUE THREAD

**Issue by MarioSMB** [sketchmacaw/MacawsModsIssues#74]
Opening and closing Shoji doors produces no sound. Villagers do trigger regular door sounds when using them.

**Comment by sketchmacaw** [comment]
Issue is fixed in the upcoming 1.0.3 update

**Comment by matteoturini** [comment]
I don't know if this is a regression, but I have the same issue. Fabric 1.19.2.

**Comment by matteoturini** [comment]
Neither does the glass door.

**Comment by matteoturini** [comment]
Also, there is no animation. They instantly go into position.

**Comment by yusifsaladin** [comment]
Missing sound bug for Shoji doors also occurring on 1.19.2 (forge loader), on version 1.0.9.  (I believe it was working before upgrading - from v1.0.7 - checking on limited client (without all the other mods I have installed in case that's messing things up)).
