### ISSUE TITLE
Vein-mining duplicates large furniture

### ISSUE THREAD

**Issue by arrisar** [sketchmacaw/MacawsModsIssues#79]
**Description**
When vein mining (in this case using Project MMO) the multiple large bookshelves, each touching furniture item is dropped per the number of blocks it occupies.

Consider the example of 2 large bookshelves next to each other. When vein mining, the broken block drops a single item, the connected bookshelf takes up 2x2 blocks, as such dropping 4 items. This results in 5 items.

**Labels**
1.16.5, Macaw's Furniture, Bug, Mod Compatibility

**Comment by sketchmacaw** [comment]
Fixed in 3.0.0 Update
