### ISSUE TITLE
Provided enchant power from bookshelves

### ISSUE THREAD

**Issue by arrisar** [sketchmacaw/MacawsModsIssues#80]
**Description**
Your large bookshelves are undoubtedly beautiful, but are only practical for aesthetics.

**Suggestion**
Provide enchant power for each block the bookshelf occupies.

e.g. for the 2x2 large bookshelf, provide a total of 4 enchant power.

**Labels**
1.16.5, Macaw's Furniture, Suggestion

**Comment by sketchmacaw** [comment]
Currently there is no easy way of implementing this, since minecraft has the bookshelf enchant power hardcoded..

**Comment by sketchmacaw** [comment]
Found a way to implement, reopened

**Comment by sketchmacaw** [comment]
Added in 3.0.0 Update
