### ISSUE TITLE
Lower Roofs texture doesn't line up with other

### ISSUE THREAD

**Issue by sketchmacaw** [sketchmacaw/MacawsModsIssues#85]
![image](https://user-images.githubusercontent.com/60577275/114401745-80ee2f80-9ba3-11eb-89fc-0e1feef38b18.png)

**Comment by PerfyNormal** [comment]
In addition to this texture issue, it seems the texture mapping on multiple pieces is flipped, stretched or misaligned. Also corner pieces seem to have lightning issues as they look brighter.
<img src=https://cdn.discordapp.com/attachments/837997702250758144/847305933923418122/unknown.png />
<img src=https://cdn.discordapp.com/attachments/837997702250758144/847306036083294228/unknown.png />

**Comment by sketchmacaw** [comment]
Fixed in 2.1.0
