### ISSUE TITLE
[1.16.5] Double interaction animation with Macaw's Doors

### ISSUE THREAD

**Issue by MarioSMB** [sketchmacaw/MacawsModsIssues#86]
When opening and closing doors (tested with the Nether spruce door) from this mod, the player will occasionally play an additional action animation with their hand. This is most reliably reproduced when opening the door from the outside, but can occur either way.

**Comment by sketchmacaw** [comment]
I'm unable to reproduce this issue, do you have any other mods with it?

**Comment by MarioSMB** [comment]
It seems I am unable to reproduce this in a clean environment either... it does seem likely that another mod is triggering it, but I have no clue which.  
Here's the server's mod list:  
https://paste.ubuntu.com/p/FGdTGfSFSs/  
I tested with Performant and Quark in the clean environment as well and could not reproduce the issue.

**Comment by sketchmacaw** [comment]
Yeah this issue is caused by another mod conflict, I'm unable to fix it.
