### ISSUE TITLE
[1.12.2] Doors duplication

### ISSUE THREAD

**Issue by ExDomino** [sketchmacaw/MacawsModsIssues#88]
Hello

The doors from your mod can be duplicated if the top is broken. Can you fix that in 1.12.2 please ?
We are currently using the 1.0.0 version, that is the only version for 1.12.2.
We cannot update the minecraft version because a LOT of mods are still for 1.12.2.

Thank you in advance.

**Comment by sketchmacaw** [comment]
Issue is fixed in the upcoming 1.0.3 update for 1.12.2
