### ISSUE TITLE
[Door/Trapdoor, 1.16.5, bug] Incorrect Map Colors for Warped and Crimson Doors and Trapdoors

### ISSUE THREAD

**Issue by Syrikal** [sketchmacaw/MacawsModsIssues#89]
Warped and Crimson doors and trapdoors appear brown on maps rather than cyan and reddish as their vanilla counterparts do.
![2021-05-28_12 11 05](https://user-images.githubusercontent.com/76715986/119933247-f4120080-bfad-11eb-90b5-d0330f755486.png)
![2021-05-28_12 11 19](https://user-images.githubusercontent.com/76715986/119933255-f7a58780-bfad-11eb-8428-236540d8d90a.png)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 1.0.3 update.

**Comment by sketchmacaw** [comment]
Also fixed in the upcoming trapdoors update...
