### ISSUE TITLE
[enhancement] add support for  MrCrayfish's Vehicle Mod

### ISSUE THREAD

**Issue by enricotagliavini** [sketchmacaw/MacawsModsIssues#90]
I'm using Minecraft 1.16.5, vehicle-mod-0.45.2-1.16.3.jar, mcw-bridges-1.0.5-mc1.16.5-4.jar on forge 36.1.18.

When going on a bridge made with Macaw's Bridges blocks the vehicle lose power, similar to other situations when the wheels are not touching the ground. This is likely due to an implementation on the bridges. Bridges are very useful when using land vehicles to cross rivers etc, it would be nice to be able to use them and have them working on the vehicles.

I'm not sure on which mod the change would be better implemented, so I opened an enhancement request also on the Vehicle mod side: https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/462

Cheers

**Comment by sketchmacaw** [comment]
Added in the newest update for bridges, you can now make wide bridges.
