### ISSUE TITLE
Breaking Furniture Causes Server Crash - Macaw's Furniture 1.16.5

### ISSUE THREAD

**Issue by MikeZillaa** [sketchmacaw/MacawsModsIssues#98]
As title. Unsure of the extent of this, tested with Spruce Vertical Cabinet, and is reliably repeatable. The crash is instant on breaking the block, requiring the server to be rebooted.

**Comment by MikeZillaa** [comment]
Further testing, this behaviour extends to other wooden items with inventories. Birch Double Draw Nightstand and Spruce Complex Dresser confirmed. Oak Chair, Jungle Simple End Table, and Acacia Glass Desk confirmed do not exhibit this behaviour.

Similar reports:
https://github.com/sketchmacaw/MacawsModsIssues/issues/76
https://github.com/sketchmacaw/MacawsModsIssues/issues/87

**Comment by sketchmacaw** [comment]
Should be fixed in 3.0.0 Update
