### ISSUE TITLE
Window texture glitching when looking from far distance or at big angle (1.16.4)

### ISSUE THREAD

**Issue by biauk** [sketchmacaw/MacawsModsIssues#99]
Looking at a window in way described in title results in seeing something similar to vanilla glass panes.
Yes, I have Optifine - maybe problem is here?
![2021-07-09_20 34 38](https://user-images.githubusercontent.com/58109852/125122424-b26c8d80-e0f5-11eb-829c-0821eb07551b.png)
![2021-07-09_20 35 14](https://user-images.githubusercontent.com/58109852/125122441-b8626e80-e0f5-11eb-8b10-0e129dcb860b.png)

**Comment by sketchmacaw** [comment]
Fixed in the upcoming 2.0.0 update
